### ISSUE TITLE
How to limit/lock max peers of one room?

### ISSUE THREAD

**Issue by ScrewChineseCommunist** [andyet/SimpleWebRTC#133]
1st client: android 4.2.2 (cm 10.1.3 su640) phone, chrome
2nd client: kindle fire hdx, chrome
3rd client: ubuntu 12.04 @AMD A8 5500, chromium

Now SimpleWebRTC doesn't limit max peers of room. But vp8 software encoding/decoding can't afford 3 videos. Even for snapdragon 800, 2 remote videos cause bad definition. And on AMD A8 5500, cpu>60%. So I modified simplewebrtc.bundle.js, I insert

if($('video',container).length>0){
    return;
}

in 3rd lines of SimpleWebRTC.prototype.handlePeerStreamAdded, but it only hided the 3rd video, audio peer is still added. And the 3rd client can still see the 2nd video.

**Comment by szimek** [comment]
[signalmaster](https://github.com/andyet/signalmaster) has an options to specify [max number of peers in a room](https://github.com/andyet/signalmaster/blob/master/server.js#L102). You can then listen to `'error'` event, which is triggered when a peer tries to connect to a full room.
