### ISSUE TITLE
Remote control - part of WebRTC?

### ISSUE THREAD

**Issue by tjacobs** [andyet/SimpleWebRTC#183]
So the screensharing put into Chrome 34 is great. 

For an application I'm developing, I'll need not just screensharing, but also the ability for a user to accept having the connected user move their mouse and type on their keyboard, ala VNC, LogMeIn, or TeamViewer.

I KNOW it sounds crazy and dangerous. Yes, I know this. But with the correct provisions, it will enable a huge new class of applications, and will be amazing.

TeamViewer does this. The user has to install it though. I'm looking to be able to do this by a Chrome extension. Even if Chrome doesn't currently support this, what is a potential (even if crazy) approach to getting a Chrome extension to be able to move and click the mouse, and type on the keyboard? Is there a JNI native like ability for Chrome to access system APIs on Mac and PC? Is there any assisted install that can be done via a Chrome extension that might open this up?

Crazy I know. So looking for a crazy solution.

Cheers,
Tom.

**Comment by fippo** [comment]
see https://github.com/maxogden/screencat
