### ISSUE TITLE
Only chat without cam or mic dosn't fire the videoAdded event in the previous peers.

### ISSUE THREAD

**Issue by hectomg** [andyet/SimpleWebRTC#185]
I'm ding an application with first, only chat connection, it is working fine, but I have noticed that the event "videoAdded" doesn't fire for previous peers i.e. if peerA creates the room, then peerB joins the room, only peerB has the videoAdded event fired but peerA don't. Is there any way to solve this in simplewebrtc.js or in signalmaster?

Regards, Hector

**Comment by VadimDez** [comment]
@hectomg, you need to use "createdPeer" event instead, i hope

**Comment by xdumaine** [comment]
I'm going to close this as stale. We don't have bandwidth to do a lot of old issue maintenance and upkeep. Please reopen if you would like more feedback.
