### ISSUE TITLE
Upgrade Socket.io to version 1.x.x

### ISSUE THREAD

**Issue by changgb** [andyet/SimpleWebRTC#190]
Our security Audit want us to record client's IP address when client try to join a meeting, it seems socket.io 0.9.16 don't support it, it show 127.0.0.1 only. Can you upgrade Socket.io version to 1.x.x? seems that version works. thanks!

**Comment by klopfdreh** [comment]
+1

**Comment by skatpgusskat** [comment]
+1

**Comment by xdumaine** [comment]
@fippo Thoughts on doing this when there's a major version bump? Could version signal master with it. Maybe InIn could help host the sandbox for a new version of signal master...

**Comment by fippo** [comment]
@xdumaine might as well do it then. Is there a way to distinguish incoming 1.x and 0.x connections?

**Comment by xdumaine** [comment]
Yes... I'll have to dig to check how we were doing it. Dropped support for 0.9 a while ago.

**Comment by xdumaine** [comment]
```javascript
_onConnect: function: (socket) {
    if (socket.handshake.hasOwnProperty('id')) {
        // socket io.0.9
    } else {
        // socket io.1.x
    }
}
```

**Comment by fippo** [comment]
hrm. I want to do it another way:
1) change the sandbox signaling hostname when making the next major version bump (soon)
2) continue to run old socket.io-0.9 signalmaster at signaling.simplewebrtc.com
3) run socket.io-1.x signalmaster at sandbox.simplewebrtc.com
(both behind nginx as reverse proxy)

How does that sound?

**Comment by xdumaine** [comment]
Yeah that's the better way IMO. The hack for detecting the incoming connection is only necessary if you *must* keep the same host name.

**Comment by fippo** [comment]
doing that in #351
