### ISSUE TITLE
it stopped workng..

### ISSUE THREAD

**Issue by martianmartian** [andyet/SimpleWebRTC#198]
Hi there,

so i copied the code and tried to run it. didn't work. well it used to be able to work. i wonder if there's something wrong somewhere?..

**Comment by fippo** [comment]
Does the http://simplewebrtc.com/demo.html demo still work for you?
If not: any console output?

**Comment by peterwilli** [comment]
For me it doesnt work either, the demo works, but I copied all the example code from http://simplewebrtc.com/ to a html file, run it on a local server without changes and nothing happens. I can see myself but not the other guy

**Comment by jakebian** [comment]
Looks like the default signalling server stopped working, run [signalmaster](https://github.com/andyet/signalmaster) locally and [point your webrtc object to it](http://simplewebrtc.com/notsosimple.html).
