### ISSUE TITLE
 define(e); throwing TypeError in Almond.js

### ISSUE THREAD

**Issue by NikkiDreams** [andyet/SimpleWebRTC#205]
I am building an Ember.js app with simplewebrtc.bundle.js included. Almond.js is being used as the AMD. SimpleWebRTC is not playing nice. The browser throws an error where SimpleWRTC determines which module loader is being used.

else if("function"==typeof define&&define.amd){
        define(e);
}

The browser error is"
Uncaught TypeError: Cannot read property 'splice' of undefined

define(e) is returning the SimpleWRTC functions but is causing the TypeError in the process. Almond seems to be expecting define("id", []); But It seems that is what is contained in "e"?

**Comment by fippo** [comment]
have you tried require-ing simplewebrtc directly instead of including the bundled version? I doubt almond likes bundles generated by browserify.

**Comment by NikkiDreams** [comment]
Almond seems to do fine with the bundling. It just does not like that line. When I comment it out everything works fine bundle and all. SimpleWebRTC works like a charm.
