### ISSUE TITLE
Remote Video stream freezes/fails on Chrome

### ISSUE THREAD

**Issue by wfaler** [andyet/SimpleWebRTC#245]
Hi,
I Have tried the simplest possible example with signalmaster running locally, and it seems to work fine with Firefox to Firefox video calls, but video consistently fails/freezes for the remote stream on Chrome (you get a frozen frame in the video tag).
The failure is silent, there is no error output in the Chrome console indicating any problem.

Client code is in the following gist: https://gist.github.com/wfaler/33a860b75496e495b9f0

**Comment by tarantindigital** [comment]
Hi,

Maybe what you need is to suppress adding them to the remote video container by passing an empty string for the container id (remoteVideos).

I hope it works

**Comment by namnemet** [comment]
@tarantindigital suggestion works

but then videoRemoved does not...

any suggestions?

**Comment by tarantindigital** [comment]
Hi!
Try this:
webrtc.on('videoRemoved', function(video, peer) {
$('#' + webrtc.getDomId(peer)).remove();
}

**Comment by namnemet** [comment]
Thank you @tarantindigital  :-)
