### ISSUE TITLE
Screen sharing in Firefox.

### ISSUE THREAD

**Issue by eshengsky** [andyet/SimpleWebRTC#247]
I found that screen sharing in Firefox could only share some window instead of whole desktop, I wonder is it possible to share the whole desktop like Chrome?

**Comment by fippo** [comment]
I think there is a way to pass specific constraints to https://github.com/HenrikJoreteg/getScreenMedia/blob/master/getscreenmedia.js#L85-86
to accomplish that but don't know where that is documented. @jan-ivar?

**Comment by xdumaine** [comment]
Not sure about official documentation, but [Muaz's docs](https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/) show that you can pass `'screen'` or `'window'` which works.

**Comment by jan-ivar** [comment]
Yes there's `screen`, `application`, `window` and `browser` (tab sharing).

Here's a test page https://mozilla.github.io/webrtc-landing/gum_test.html

The demo doesn't show tab sharing, but I know tab sharing works in Firefox Hello.

**Comment by xdumaine** [comment]
So it seems we just need the dependency chain for `startScreenShare` (i.e., localMedia)` to accept constraints and pass those on to getscreenmedia, and allow those to be passed in to `shareScreen` or provided as a config option. I can tackle that, if that sounds good - @fippo?

**Comment by fippo** [comment]
hm... @legastero?

**Comment by eshengsky** [comment]
I modified the source, and it seems works fine. I have a new question:
In Firefox, when I start to share screen, others peers will trigger event 'videoAdded', it's correct, but when I stop share by clicking on Shared Indicator or the icon in Url bar, others peers do not trigger event 'videoRemoved', while write 'webRtc.stopScreenShare()' manually it works fine.
local screen has the same issue: use 'webRtc.stopScreenShare()' manually can triggle 'localScreenStopped' event, but select stop share on Shared Indicator or the orange icon in Firefox Url Bar, it fails.
Is it a bug?
thank you!

**Comment by xdumaine** [comment]
Firefox doesn't emit the ended event for MediaStream or MediaStreamTrack objects yet, so the handler to fire the `localScreenStopped` event on end doesn't work.

**Comment by fippo** [comment]
that is supposed to be detected by https://github.com/HenrikJoreteg/getScreenMedia/blob/master/getscreenmedia.js#L89-103
-- does that not work anymore?

**Comment by xdumaine** [comment]
Just tested in firefox and nightly. The timeout keeps running and the stream.currentTime just keeps on ticking forward.

**Comment by tgabi333** [comment]
Resolved
