### ISSUE TITLE
dynamiac multiple rooms

### ISSUE THREAD

**Issue by namnemet** [andyet/SimpleWebRTC#251]
i would like to produce this scenario:
users A B C D

any user can subscribe to any of the other user
lets say user A subscribed to users B and C
while user B subscribed to users A and B

when user A subscribed to the users she chose - it means that she can now see user B and C- but they can not see her... and so on...

my logic:
2 options:
either:
1. create multiple rooms   - one for each user. user A will subscribe to the appropriate rooms (but they should not see user A)
or
2. perhaps there is only one room which contains  all the users - but i can somehow filter the users so user A will only see users B and C .....

do you have any suggestions? code sample? tutorials?

which can point me in the right direction?

Thank you

**Comment by tgabi333** [comment]
That's more than simplewebrtc can do. Maybe you can fork it and change.
