### ISSUE TITLE
How to listen for it when myself leaving room?

### ISSUE THREAD

**Issue by eshengsky** [andyet/SimpleWebRTC#253]
I want to do something before leave room , if I use:
  webrtc.stopLocalVideo();
  webrtc.leaveRoom();
it's easy to add other scripts before that.
But if I close the window/tab to leave room, how to listen for it?
Is there any event like: webrtc.on("localDisconnect",function(){...})?
Thanks!

**Comment by tgabi333** [comment]
You can play with 'beforeunload' and 'unload' event on window

Or you can catch event at server side when a socket.io client disconnects.
