### ISSUE TITLE
How to change Nickname

### ISSUE THREAD

**Issue by jfs77** [andyet/SimpleWebRTC#264]
Hello,

I can set the "nick" propertie when I created the webrtc 
    
    var webrtc = new SimpleWebRTC({
        ...
        nick: 'inconnu',
        ...
    });

But I would like to change the nick in a second time without use the channel message

**Comment by xdumaine** [comment]
The nick field is used for passing the user nick so it's immediately available in the offer/answer. If you need to broadcast or update information to peers later, the data channel messaging is your best bet.

**Comment by jfs77** [comment]
Do you have more information about offer/answer ?
I dont understand difference between offer and answer.

So if you have an exemple, how to use, juste like another data channel ?

**Comment by tiger2380** [comment]
Did you ever figure out how to change nick after initialization?

**Comment by tgabi333** [comment]
You should make it manual using `sendDirectlyToAll`. Send the new nick name to every participant and they can update the nick field.
