### ISSUE TITLE
support safari

### ISSUE THREAD

**Issue by PraxisCreativa** [andyet/SimpleWebRTC#271]
Is it possible to be compatible with the Safari browser.?

**Comment by cremfert** [comment]
As far as I know, safari is not supported natively, as WebRTC is not built into safari. I found a plugin for this (https://temasys.atlassian.net/wiki/display/TWPP/WebRTC+Plugins) but didn't had the chance to test it yet.

Maybe you could report if it is working?

Thanks and best regards,
Chris

**Comment by xdumaine** [comment]
SimpleWebRTC doesn't at this time support the Temasys plugin.
