### ISSUE TITLE
Peer MediaStream with WebAudio not working

### ISSUE THREAD

**Issue by gerhardberger** [andyet/SimpleWebRTC#272]
Hi

When want to use the WebAudio API on the received peer's MediaStream, it doesn't output any sound, but when I do it with the local MediaStream, it works fine. I'm using the latest version of Chrome. What could be the issue?
Here is my code:
``` js
webrtc.on('videoAdded', function (video, peer) {
    var panner = audioCtx.createPanner()
    panner.setOrientation(1,0,0)
    panner.coneInnerAngle = 360
    panner.coneOuterAngle = 0

    var source = audioCtx.createMediaStreamSource(peer.stream)
    source.connect(panner)
    panner.connect(audioCtx.destination)

    peer.videoEl.muted = 'muted'
})
```

Thanks for any help!

**Comment by fippo** [comment]
Am 03.07.2015 um 21:24 schrieb Gerhard Berger:
> Hi
>
> When want to use the WebAudio API on the received peer's MediaStream, it doesn't output any sound, but when I do it with the local MediaStream, it works fine. I'm using the latest version of Chrome. What could be the issue?

Sadly, remote streams can't be hooked up with webaudio in chrome:
https://code.google.com/p/chromium/issues/detail?id=121673

long story :-(
