### ISSUE TITLE
How to Setup Server Side Authentication for Room Access

### ISSUE THREAD

**Issue by daryl3** [andyet/SimpleWebRTC#301]
I am trying to do some sort of server side authentication to allow only specific clients to join a SimpleWebRTC Room.

Right now, any client that goes to the SimpleWebRTC "demo" page can join the room.

Here is an example of my setup:
&nbsp;_____________ &nbsp;&nbsp;&nbsp;   ________________  &nbsp;&nbsp;  _______________ &nbsp;&nbsp;   ________________
| &nbsp;&nbsp;   Web Server &nbsp;&nbsp;&nbsp; | &nbsp; |&nbsp;&nbsp; Haproxy Server &nbsp;&nbsp;| &nbsp; |&nbsp;&nbsp; Signal Master &nbsp; &nbsp;&nbsp;&nbsp;| &nbsp; | Restund Server &nbsp;&nbsp;&nbsp; |
| SimpleWebRTC &nbsp;|--|&nbsp;&nbsp;&nbsp;  Load Balancer &nbsp;&nbsp;&nbsp;|--|  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Server  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   |--|&nbsp;&nbsp;&nbsp;Stun/Turn Server&nbsp;&nbsp;|
|______________|  &nbsp;|________________| &nbsp; |_______________| &nbsp; |_______________ |

I'm having difficulty understanding how I allow access to only the end users I want, instead of anyone who goes to the page and guesses the room name.

I could create a room name that is so unique it would be highly unlikely to ever be guessed. But I'm trying to avoid the "security through obscurity" method.

**Comment by xdumaine** [comment]
You just perform authentication check in signalmaster. When a client attempts to join a room, check permissions/auth, then reject if not allowed.

**Comment by cremfert** [comment]
I did this by checking the user in the "join" event of the signalmaster. If authentication is wrong, I send a message back with ```client.emit("wrongPassword");```and return the function.

Hope that helps. Otherwise drop me a message!
