### ISSUE TITLE
leave event not firing for initiatior

### ISSUE THREAD

**Issue by thg1101** [andyet/SimpleWebRTC#325]
When a room is created with createRoom, the leave event isn't fired for the initiator because the first check for leaveRoom (https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.js#L262) returns false. 
This can be easily avoided by manually setting the room name after room creation, but it would make more sense for this to be done in the library.
Just add 
this.roomName = name;
before https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.js#L448

This would've probably been clearer in a pull request but I'm not yet confortable with git.

**Comment by fippo** [comment]
Now that is how I like issues described. See #325 for the PR (will merge tomorrow)

Thank you!

**Comment by xdumaine** [comment]
👍🏽

**Comment by thg1101** [comment]
Looks great, thanks. Will try to feed back fixes to any other problems I come across.
