### ISSUE TITLE
Chrome - Firefox screensharing error

### ISSUE THREAD

**Issue by thg1101** [andyet/SimpleWebRTC#327]
OK folks, this one's a doozy. When joining a room with two people, one using Chrome, the other Firefox, and the Chrome user starts screen sharing, the Firefox user is just fine, but the Chrome user receives an additional, empty feed video stream, labeled as coming FROM the Firefox user (e.g:
<FFPEERID>_screen_broadcasting).

This can be reproduced using https://simplewebrtc.com/demo.html but you have to start screensharing form the console since the click handler for the button doesn't actually work. Might wanna fix that, btw.

I've spent several hours trying to debug this, to no avail, for my use case I can just not add any streams labeled broadcasting, but that's treating the symptom, not the problem. Here's hoping you fare better!

**Comment by bear** [comment]
Screenshare click handler sub issue fixed in PR #328

**Comment by fippo** [comment]
I vaguely recall working around this issue. Do you have a chrome://webrtc-internals dump?

**Comment by thg1101** [comment]
I've re-created the issue and recorded an internals dump you can view here https://gist.github.com/thg1101/8f11e3c2c7274f114536

**Comment by fippo** [comment]
to me that looks like a chrome issue... it shouldn't trigger addStream here.
We can suppress this in 
https://github.com/andyet/SimpleWebRTC/blob/master/peer.js#L228
by looking at the sharemyscreen property of peer since screensharing streams are always one-way.

@thg1101 until I get around doing that, can you try that in peerStreamAdded / videoAdded?

**Comment by thg1101** [comment]
Yes, I already suppressed the extra video in videoAdded, but as I've said, I'd rather treat the root of the problem. Still, this isn't your run of the mill bug, so as long as someone's keeping a watch on things, I'm happy.

**Comment by fippo** [comment]
filed https://code.google.com/p/webrtc/issues/detail?id=5054 -- thanks for testing and debugging this!

**Comment by thg1101** [comment]
Happy to help. One thing of note though: Talky.io doesn't seem to exhibit the same behavior. Since it's based on SimpleWebRTC I found this curious. Different handling? Food for thought.

**Comment by fippo** [comment]
fix should roll out in Chrome 48
