### ISSUE TITLE
better dokumentation

### ISSUE THREAD

**Issue by Trinitas** [andyet/SimpleWebRTC#33]
There's so little dokumentation on this project. example: "webrtc.joinRoom" is in the dokumentation but not "webrtc.leaveRoom" why is that?

Also, how do you end the local stream after leaving the room?

**Comment by jlouazel** [comment]
+1

**Comment by namnemet** [comment]
I'm sorry 
where is the documentation ?
(link pls :-) )

**Comment by xdumaine** [comment]
Not a replacement for good documentation, but check out https://simplewebrtc.com/notsosimple.html for some more advanced examples (in progress).

**Comment by namnemet** [comment]
thank you :-)
