### ISSUE TITLE
Android WebView incompatibility (window.chrome)

### ISSUE THREAD

**Issue by pavlospt** [andyet/SimpleWebRTC#330]
Hello all. 

I have opened an issue on Android Platform relating to the WebView application. After a long long conversation with the developers there, it seems that the SimpleWebRTC is not working because of the window.chrome check. 

Is there something that could be done in order to resolve this? 

Thank you in advance.

P.S.:The link of the bug report -> https://code.google.com/p/chromium/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=532196

**Comment by fippo** [comment]
that should be working again once https://github.com/webrtc/adapter/pull/142 is merged
(we're using adapter)

**Comment by pavlospt** [comment]
Can we at least provide an experimental latest.js with these changes. I am trying to set it up locally and build it but i get rejected because it declines non same origin stuff, and i kind off been stuck at a deadend with it.

**Comment by fippo** [comment]
i'd suggest downloading the latest bundle and replacing the window.chrome check (also, please don't use latest.js for anything but experiments).

Where does it get rejected due to same origin checks? the default sandbox server is not supposed to do that.

**Comment by pavlospt** [comment]
That's what i have done. I have downloaded the latest bundle and made the same changes. Then where should i load the file from?

**Comment by fippo** [comment]
that is supposed to work. we just kicked the poor sandbox server.

if that doesn't help, did you try running your own https://github.com/andyet/signalmaster ?

**Comment by pavlospt** [comment]
Got it working. But now the main problem is that the WebRTC is not getting load or initialized. Tried loading the HTML page that you have shared in the PR on webrtc, and it correctly shows a version number, which for my phone and the webview version installed, is number 46. 

So i guess that something else is wrong. If you are familiar with Android I can share more details, in order to be as thorough as possible to resolve this issue.

**Comment by pavlospt** [comment]
The latest WebView broke the WebRTC functionality. I can not seem to find any errors or something going wrong. Can someone please provide some insight on this. Is it working ok for you with the latest version of the beta WebView?

**Comment by fippo** [comment]
did the samples from https://webrtc.github.io/samples/ also break? If yes can you open a bug there and provide a link here?
