### ISSUE TITLE
Disable volume change event

### ISSUE THREAD

**Issue by modder2** [andyet/SimpleWebRTC#332]
How can I disable fire volume change event?
This event demands a lot of resources and I do not need it.

**Comment by xdumaine** [comment]
Pass the option `detectSpeakingEvents: false`

**Comment by modder2** [comment]
@xdumaine Thanks.
Where I can find full documentation or the options list?

**Comment by xdumaine** [comment]
@modder2 unfortunately we don't have comprehensive docs. That's on the todo list.
