### ISSUE TITLE
too many STUN requests

### ISSUE THREAD

**Issue by namnemet** [andyet/SimpleWebRTC#334]
I'm sending a lot of stun requests for each user.

sending offer 
on
simplewebrtc.bundle.js:5523 sending offer Object 
and 
simplewebrtc.bundle.js:586 sending offer Object 
are fired continuously 

did anyone encountered such an issue?

**Comment by xdumaine** [comment]
Which stun servers are you using? You'll likely see a handful of these, but *continuously* is not good...

**Comment by namnemet** [comment]
thanks :-)

Well , they do stop.after a few seconds - after firing a lot...

I'm using xirsys - and still on simpleWebRTC signaling  server.

I had a problem with freezing and blackened videos - xirsys told me that the STUN request are sent literally hundreds of times while the TURN is being requested

I had black videos issue for occasional for one or two users - a while back  - but freezing or all users experiencing blackened videos - only the last couple of days 

I've used joinRoom for every user - while every other user can join any other room

still... I'm only in experimental stage so there are about 10  users online....

any ideas?

Thank you :-)

**Comment by namnemet** [comment]
Is it normal that lines :
simplewebrtc.bundle.js:5523  
and
simplewebrtc.bundle.js:586
are fired about 80 time - within about a second
(and then stop)
?

usually after that everything works fine - the videos connect and everything is fine.

am I doing something wrong or is it something on Xirsys side - like problems connecting to their server?

**Comment by namnemet** [comment]
O.K. - the firing  of those lines do not seem to make a difference
nor does the amount of rooms I open

still - continuous STUN request....

**Comment by fippo** [comment]
when you're saying "continuous STUN request" -- are you seeing those in Wireshark or are you referring to ice candidate events in JS?

**Comment by namnemet** [comment]
Wireshark :-)

**Comment by fippo** [comment]
that is likely consent checks. Chrome sends them quite often to figure out if the peer still wants to receive data.

**Comment by namnemet** [comment]
Thank you @fippo 
The document says they should be randomized resulting in consent checks between 4-6 seconds

I see them between 2 in a second to once in 7 seconds

still O.K.?

**Comment by namnemet** [comment]
solved thank you

**Comment by namnemet** [comment]
solved - thank you
