### ISSUE TITLE
How to get full list of rooms of video-chat which active now?

### ISSUE THREAD

**Issue by webgrig** [andyet/SimpleWebRTC#336]
How to get full list of rooms of video-chat which active now?

**Comment by fippo** [comment]
you'll basically have to modify your server (e.g. https://github.com/andyet/signalmaster) to return a list of rooms and add something that reports whether there are 'active' chats in the room back to the server.

**Comment by cremfert** [comment]
I just did this by having JS object where I put the rooms in/out on join/leave. I return this object as JSON upon request. Hope that helps!

**Comment by xdumaine** [comment]
Closing as this requires a modification of signalmaster, a different project.
