### ISSUE TITLE
Join room without camera and microphone

### ISSUE THREAD

**Issue by illide** [andyet/SimpleWebRTC#338]
Hello!
I'm add text-chat to SimpleWebRtc use 
```javascript
 webrtc.sendToAll('chat', {message: msg, nick: webrtc.config.nick});
```
Now i have audio, video and text chat.
But if user join room without camera and without microphone: 
he will not get anything! he can not listen , watch or use the chat.

function local media error
```javascript
webrtc.on('localMediaError', function (err) {
  console.log(err);  
});
```
return "DevicesNotFoundError".
Okay i haven't any devices, but i want use this AWESOME functional.

How i can use it without devices?
Thk for attention.

**Comment by tgabi333** [comment]
webrtc.sendToAll uses webrtc datachannel, try to add this functionality to socket server (signalmaster)

**Comment by xdumaine** [comment]
`.sendToAll` should be using the socket, `.sendDirectlyToAll` uses the data channel.
