### ISSUE TITLE
Video resizing

### ISSUE THREAD

**Issue by juanferrari** [andyet/SimpleWebRTC#339]
Hi, I would like yo know if it is possible to resize the video according to the browser's window size, so that all the elements are correctly diplayed. I tried using boostrap classes for the container of the video. But it doesn't work. 
Whenever I make my browser's window smaller the video always keep it's initial size.

**Comment by xdumaine** [comment]
This is a CSS issue - I suggest posting on StackOverflow and including some example code of what you've tried (a codepen or fiddle showing the problem will get you the furthest).
