### ISSUE TITLE
Starting audio call only

### ISSUE THREAD

**Issue by tuser110** [andyet/SimpleWebRTC#341]
Hello Guys,
First of all thanks for SimpleWebRTC I love this application.
I want to start audio call only but i can't see any function for this. I am using following code
with autoRequestMedia:false :-
```
 webrtc = new SimpleWebRTC({
       localVideoEl: 'local-videos-container',
       remoteVideosEl: 'videos-container',
       autoRequestMedia: false,
       url: 'https://192.168.1.51:8001/'
});
```

So when user click on audio call i just want to start audio call only not video 
i can see the method webrtc.startLocalVideo(). so is there any function for audio only? 

Thanks

**Comment by xdumaine** [comment]
Thanks for using it! Just pass `media: { audio: true, video: false }` to the constructor.

**Comment by tuser110** [comment]
Hello !

Thanks for your help now its working fine i need another help can i enable video without recreating the constructor. For example if i want to enable video on button click after set media  `media: { audio: true, video: false }`?.

Thanks again

**Comment by tgabi333** [comment]
Currently, the simplest solution is to destroy the old SimpeWebRTC object and create a new one.
