### ISSUE TITLE
peerConnectionConfig

### ISSUE THREAD

**Issue by github4f** [andyet/SimpleWebRTC#343]
According to the webrtc, in order to configure the ICE server, we need to use "RTCPeerConnection". However, according to simplewebrtc, it seems we should work with peerConnectionConfig! why is that?

**Comment by fippo** [comment]
SimpleWebRTC is a highlevel wrapper around the lower-level RTCPeerConnection API.

**Comment by github4f** [comment]
Still is it possible to use RTCPeerConnection? we already have some clients and it might be hard to develop it from scratch?

**Comment by fippo** [comment]
simplewebrtc is using rtcpeerconnection under the hood.

The typical way to pass custom ice servers is to send them from your own signalmaster server. Or you override this in https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.js#L163-L172
The data there is just passed down straight to the RTCPeerConnection.

**Comment by github4f** [comment]
Oki. We would also lite to have android/ios version. I have noticed that you mentioned, it should be based on "signalmaster" project. It means that, we cannot use SimpleWebRTC? Do we need to have two different signalling? I appreciate your comment?

**Comment by fippo** [comment]
https://github.com/andyet/signalmaster is the default signaling server for simplewebrtc, it is meant to be used together with simplewebrtc

**Comment by github4f** [comment]
Got it, thank you very much...
