### ISSUE TITLE
Send message to Signalmaster

### ISSUE THREAD

**Issue by cremfert** [andyet/SimpleWebRTC#344]
I want to send a message only to the signalmaster.
I tried 
```webrtc.emit("message", "test");```
as well as
```webrtc.connection.emit("message", "test");```
but the signalmaster does not receive the message.

What do I wrong?

Best regards,
Chris

**Comment by fippo** [comment]
if you're reusing 'message' this might get caught here: https://github.com/andyet/signalmaster/blob/master/sockets.js#L21-L29

does your custom message appear in the browsers networking console?

**Comment by cremfert** [comment]
Got it! Thanks!
