### ISSUE TITLE
Serious problem, how do you verify if the call was host to host, srflx or relay/turn?

### ISSUE THREAD

**Issue by shamun** [andyet/SimpleWebRTC#347]
I am having some lypsync problem and everybody is blaming its our SimpleWebRTC framework causing but i refused. 

1) But now i was doing call test such as, in same PC with 2 tab: https://mydomainof-simplewebrtc.com/meeting-join and then going to chrome://webrtc-internals to verify if its host or srflx or relay, its showing me relay? 

2) then i used the same url from that same PC to the same lan another PC. i checked the log and its still saying: relay

3) then i used proxy server, and different complicated firewall networks, i checked the log and its still saying: relay

why its showing relay if its tab to tab or even the call is in lan to lan. how can i verify in which cases i have the calls as: host to host and srflx 

is this a BUG? that all the calls are relay and its not doing host to host anymore in SimpleWebRTC?

**Comment by shamun** [comment]
How can i make one connection and be 100% sure if the call type was: host or srflx or relay please?

**Comment by fippo** [comment]
if there is a lip-sync problem it can't be solved by javascript.
Are you passing 'relay' as iceTransportPolicy in the constructor?

Having a dump from chrome://webrtc-internals would be helpful. Are you already looking at the googLocalCandidateType and googRemoteCandidate fields of the bold connection on the right side of that page?

if you want to query that from javascript use getStats on the iceconnectionstatechange to connected and see https://github.com/webrtc/apprtc/blob/master/src/web_app/js/infobox.js#L105-L116 for an example.

**Comment by shamun** [comment]
Please find the log as below.

i have done several call from Canary to Google Chrome in same PC with 2 browser, where the call should be host to host, srflx (not relay). 

But remotely when i switch off the turnserver Canary and Google Chrome still stay connected, which means the call is alive even the turn-server is down, the call must be host to host or srflx not relay, and still there is lip-sync even if its host to host. 

I am exactly not sure if i am forcing the call to do relay at all. Because in my code i have not mentioned it anywhere by force to use relay / fallback always as default.



i have the turn-server settings as below via signal master:

```
        credentials.push({
          username: 'root',
          credential:'root',
          urls:['turn:relay.doman.com....']
        });
```


"Are you passing 'relay' as iceTransportPolicy in the constructor?"

chrome://webrtc-internals shows, constructor shows as below: 
```https://domain.com/test, { servers: [stun:stun.l.google.com:19302, turn:relay.domain.com, turn:relay.domain.com:80?transport=tcp, turns:relay.domain.com:443?transport=tcp], iceTransportType: all, bundlePolicy: balanced, rtcpMuxPolicy: negotiate }, optional: {DtlsSrtpKeyAgreement:true}```


chrome://webrtc-internals shows log as below while being connected (and even if turn-server is switched off in the server) : 

```
Channel-audio-1
Statistics Channel-audio-1
timestamp	11/13/2015, 2:15:54 AM
selectedCandidatePairId	Conn-audio-1-0
googComponent	1
dtlsCipher	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
localCertificateId	googCertificate_28:C2:90:A0:A7:EA:BF:0E:83:CB:1A:BE:03:3C:B4:6F:94:9F:25:CA:0A:35:2D:CE:DA:1C:14:A2:97:43:A8:07
remoteCertificateId	googCertificate_B7:E3:A9:BB:1F:3C:42:96:5E:19:FE:48:A0:48:7F:76:9A:D5:CC:3E:3E:25:8E:68:BD:12:EC:87:99:8D:0C:9E
srtpCipher	AES_CM_128_HMAC_SHA1_32


Conn-audio-1-0
Statistics Conn-audio-1-0
timestamp	11/13/2015, 2:16:05 AM
googActiveConnection	true
bytesReceived	141267882
bytesSent	119368148
packetsSent	146253
googReadable	true
googChannelId	Channel-audio-1
googLocalAddress	[2a02:a018:203:3700:14:226f:26c5:5f4]:52053
localCandidateId	Cand-QHURQDt9
googLocalCandidateType	local
googRemoteAddress	[2a02:a018:203:3700:14:226f:26c5:5f4]:64265
remoteCandidateId	Cand-RB7FXknE
googRemoteCandidateType	local
googRtt	1
packetsDiscardedOnSend	0
googTransportType	udp
googWritable	true


Cand-QHURQDt9
Statistics Cand-QHURQDt9
timestamp	11/13/2015, 2:06:57 AM
ipAddress	2a02:a018:203:3700:14:226f:26c5:5f4
networkType	wlan
portNumber	52053
priority	2122262783
transport	udp
candidateType	host


Cand-RB7FXknE
Statistics Cand-RB7FXknE
timestamp	11/13/2015, 2:06:57 AM
ipAddress	2a02:a018:203:3700:14:226f:26c5:5f4
portNumber	64265
priority	2122262783
transport	udp
candidateType	host


Conn-audio-1-1
Statistics Conn-audio-1-1
timestamp	11/13/2015, 2:16:36 AM
googActiveConnection	false
bytesReceived	0
bytesSent	0
packetsSent	0
googReadable	true
googChannelId	Channel-audio-1
googLocalAddress	192.168.1.17:50319
localCandidateId	Cand-ZrYq6ZY+
googLocalCandidateType	local
googRemoteAddress	192.168.1.17:61389
remoteCandidateId	Cand-XaO9IuAu
googRemoteCandidateType	local
googRtt	1
packetsDiscardedOnSend	0
googTransportType	udp
googWritable	true


Cand-ZrYq6ZY+
Statistics Cand-ZrYq6ZY+
timestamp	11/13/2015, 2:06:57 AM
ipAddress	192.168.1.17
networkType	wlan
portNumber	50319
priority	2122194687
transport	udp
candidateType	host


Cand-XaO9IuAu
Statistics Cand-XaO9IuAu
timestamp	11/13/2015, 2:06:57 AM
ipAddress	192.168.1.17
portNumber	61389
priority	2122194687
transport	udp
candidateType	host


Conn-audio-1-2
Statistics Conn-audio-1-2
timestamp	11/13/2015, 2:06:59 AM
googActiveConnection	false
bytesReceived	0
bytesSent	0
packetsSent	0
googReadable	false
googChannelId	Channel-audio-1
googLocalAddress	192.168.1.17:50319
localCandidateId	Cand-ZrYq6ZY+
googLocalCandidateType	local
googRemoteAddress	217.136.224.18:61389
remoteCandidateId	Cand-gbnHNuXg
googRemoteCandidateType	stun
googRtt	3000
packetsDiscardedOnSend	0
googTransportType	udp
googWritable	false


Cand-gbnHNuXg
Statistics Cand-gbnHNuXg
timestamp	11/13/2015, 2:06:57 AM
ipAddress	217.136.224.18
portNumber	61389
priority	1685987071
transport	udp
candidateType	serverreflexive


Conn-audio-1-3
Statistics Conn-audio-1-3
timestamp	11/13/2015, 2:06:59 AM
googActiveConnection	false
bytesReceived	0
bytesSent	0
packetsSent	0
googReadable	false
googChannelId	Channel-audio-1
googLocalAddress	192.168.1.17:50319
localCandidateId	Cand-ZrYq6ZY+
googLocalCandidateType	local
googRemoteAddress	188.x.x.x:59090
remoteCandidateId	Cand-jnqp/M+a
googRemoteCandidateType	relay
googRtt	3000
packetsDiscardedOnSend	0
googTransportType	udp
googWritable	false

Cand-jnqp/M+a
Statistics Cand-jnqp/M+a
timestamp	11/13/2015, 2:06:57 AM
ipAddress	188.x.x.x
portNumber	59090
priority	25042687
transport	udp
candidateType	relayed


ssrc_3859203608_recv
Statistics ssrc_3859203608_recv
cname:js/qQk19Pw5M7ySd
msid:iKbSfYp3EdGMalkjgmSTdqfUnn7EHeAPRjLc 8bec8161-e479-4f6f-99b3-e94d1076c27a
mslabel:iKbSfYp3EdGMalkjgmSTdqfUnn7EHeAPRjLc
label:8bec8161-e479-4f6f-99b3-e94d1076c27a
timestamp	11/13/2015, 2:17:42 AM
audioOutputLevel	0
bytesReceived	879322
packetsLost	0
packetsReceived	32560
ssrc	3859203608
transportId	Channel-audio-1
googAccelerateRate	0
googCaptureStartNtpTimeMs	-1
googCodecName	opus
googCurrentDelayMs	75
googDecodingCNG	0
googDecodingCTN	65211
googDecodingCTSG	0
googDecodingNormal	65043
googDecodingPLC	68
googDecodingPLCCNG	100
googExpandRate	0
googJitterBufferMs	38
googJitterReceived	0
googPreemptiveExpandRate	0
googPreferredJitterBufferMs	20
googSecondaryDecodedRate	0
googSpeechExpandRate	0
googTrackId	8bec8161-e479-4f6f-99b3-e94d1076c27a

```

Also before placing call i have switched the turn-server and then made Canary to Google chrome the connection, while doing this the call clearly shows "srflx" and no "relay" in logs. What does this mean please? that Chrome, Canary introduced a new BUG? if it find turn-server it use the turnserver / relay and ignores the srflx or host to host? which was not in past, in past the order was: try host to host first and if fail do srflx to srflx if that also failed then finally try relay. Is this not anymore the logic? if this is the case then it must be Google Chrome/Canary introduced this new issue and that is why the lip-sync suddenly reported by many at once, before it was not the issue.

Please advise. thank you

**Comment by shamun** [comment]
I just now did following:

1) i switched off the turnserver 
2) from Canary to Google chrome i made the call connection 
3) i checked the log, it clearly saying:

```
sdpMid: video, sdpMLineIndex: 1, candidate: a=candidate:2563637125 1 udp 1685987071 217.136.224.18 53135 typ srflx raddr 192.168.1.17 rport 53135 generation 0


Cand-DjUGUREV
Statistics Cand-DjUGUREV
timestamp	11/13/2015, 2:33:00 AM
ipAddress	192.168.1.17
portNumber	53135
priority	2122194687
transport	udp
candidateType	host

Cand-toqDDfQP
Statistics Cand-toqDDfQP
timestamp	11/13/2015, 2:32:42 AM
ipAddress	2a02:a018:203:3700:14:226f:26c5:5f4
networkType	wlan
portNumber	53328
priority	2122262783
transport	udp
candidateType	host

Cand-biw1vHl9
Statistics Cand-biw1vHl9
timestamp	11/13/2015, 2:32:42 AM
ipAddress	2a02:a018:203:3700:14:226f:26c5:5f4
portNumber	53542
priority	1853827327
transport	udp
candidateType	peerreflexive
```


host not relay, but when i switch on the turn-server and make same call immediately same log shows candidate type: relayed

is this a new bug introduced by Google Chrome/Canary team? it was not like this before as far as i remember. which means all our calls are now forced automatically into "relayed" the reason why at once lip-sync is killing us.


Please advise, waiting for your valuable inputs. thank you

**Comment by fippo** [comment]
The first logs shows a local-local connection. I marked the fields to look at in bold
Conn-audio-1-0
Statistics Conn-audio-1-0
timestamp   11/13/2015, 2:16:05 AM
**googActiveConnection**    **true**
bytesReceived   141267882
bytesSent   119368148
packetsSent 146253
googReadable    true
googChannelId   Channel-audio-1
googLocalAddress    [2a02:a018:203:3700:14:226f:26c5:5f4]:52053
localCandidateId    Cand-QHURQDt9
**googLocalCandidateType**  **local**
googRemoteAddress   [2a02:a018:203:3700:14:226f:26c5:5f4]:64265
remoteCandidateId   Cand-RB7FXknE
**googRemoteCandidateType** **local**
googRtt 1
packetsDiscardedOnSend  0
googTransportType   udp
googWritable    true

in the second call, what you're seeing is candidate stats. Chrome will (and has for years) usually gather relay candidates but not use them. Unless those candidates are referenced by the connection (ind remoteCandidateId and localCandidateId) that has googActiveConnection true they're not used.

**Comment by shamun** [comment]
Sir, then its a problem, because i took down the turn-server completely and i can make connection from PC with 2 browser or 2 PC in same lan in same network. 

even the call is local and not going via turn-server still causing always lip-sync.

do you have any idea what could be causing this lip-sync even in LAN? 
Could this be that Google Chrome stable/current version or Canary might have introduced any new BUG? 
(it was not before in my experience till now.)

**Comment by xdumaine** [comment]
You should open this on Discuss-webrtc where you'll have a larger audience, meaning this team as well as the Chrome dev team, who could lend their knowledge from the browser point of view.
