### ISSUE TITLE
TURN configuration

### ISSUE THREAD

**Issue by cremfert** [andyet/SimpleWebRTC#348]
I have installed coturn as a turn server. Due to this, my question is:

1) How can I specify a static username/password in the signalmaster configuration? Is "username"/"credential" the right combination for this?
1) Can anybody tell me how to configure coturn correctly for SimpleWebRTC shared secret auth?

Thanks a lot and best regards,
Chris

**Comment by fippo** [comment]
(1) static passwords are not supported. If you really want them (and this is a bad idea) then you'll have to modify https://github.com/andyet/signalmaster/blob/master/sockets.js#L111-L122 (it gets simpler)

(2) coturn calls this the 'REST API'. Looks like it is configured in https://github.com/coturn/coturn/blob/master/examples/etc/turnserver.conf#L181

**Comment by cremfert** [comment]
Can't get it to work - the only software that works with SimpleWebRTC for me is restund with the patch applied. With all other server software used, the remote video screen keeps black. No error, but nothing happens and finally, FireFox says: ICE failed. But I don't have a clue, why... Any ideas?

**Comment by cremfert** [comment]
Got a step forward: it says: "401 unauthorized" - I guess, it has something to do with the realm. Where can I set it in SimpleWebRTC/Signalmaster?

**Comment by cremfert** [comment]
Got it - set the realm to my IP, now everything is working.
Thanks for your help!

**Comment by vylan** [comment]
@cremfert , I am blocked here now. could you provide a turnserver config example? That would be very helpful.

**Comment by dfabreguette-ap** [comment]
Hey,
Did you manage to make it work with coturn ? Or did you use restund instead ?
