### ISSUE TITLE
Recommended media server

### ISSUE THREAD

**Issue by mattapperson** [andyet/SimpleWebRTC#356]
Do you have any recommendations for setting up a media server  (middleware so if I am broadcasting to multiple users, the broadcaster is streaming to a server and the other users are streaming from the server)

**Comment by fippo** [comment]
the jitsi videobridge. But it's not integrated with simplewebrtc (which is mainly p2p/full mesh) so you'll have to go for something like https://github.com/otalk/stanza.io and https://github.com/otalk/mod_muc_focus which we use for talky.io

**Comment by dmr** [comment]
@fippo Are you still using "jitsi videobridge" at talky.io?

sanza.io is the replacement for simplewebrtc that you are using for talky.io, do I understand that correctly?

**Comment by stpeter** [comment]
Correct! (Actually we don't use the JVB for two-person conferences, but we upgrade to using the bridge for larger conferences.)
