### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. 

### ISSUE THREAD

**Issue by Arabello** [andyet/SimpleWebRTC#357]
Hi,
I get this error in my SimpleWebRTC app: 
"XMLHttpRequest cannot load http://localhost:8888/socket.io/?EIO=3&transport=polling&t=1448384536181-76. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access."

I use signal-master server running on http://localhost:8888. So I don't use sandbox signaling server (as said in #263). I've tried to reinstall all signal-master and simplewebrtc dependencies.

Is it a client side or server side problem? How can I resolve it?

**Comment by fippo** [comment]
are you trying a new signalmaster with an old version of simplewebrtc? version 2.x is at https://simplewebrtc.com/latest-v2.js

**Comment by Arabello** [comment]
I'm using signal-master@0.2.2 and simplewebrtc@2.0.0

**Comment by Arabello** [comment]
I solved it. I don't know why but npm install signal-master installs a different version. I download it from github page as zip and install dependencies manually.

**Comment by fippo** [comment]
oh. I wasn't aware there is an npm package for it. Will update that one.
