### ISSUE TITLE
Using SimpleWebRTC for streaming - client doesn't need to send video

### ISSUE THREAD

**Issue by Pixcell** [andyet/SimpleWebRTC#361]
Hello,

I'm trying to use SimpleWebRTC to build a small streaming app.
One url to stream your camera feed, and one url to watch.

I tried this:

```js
function startStreaming(){
  var webrtc = new SimpleWebRTC({
    localVideoEl: 'localVideo',
    autoRequestMedia: true
  });
  
  webrtc.on('readyToCall', function () {
      webrtc.joinRoom('XXX');
      console.log('Room joined');
  });
}

function startWatching(){
  var webrtc = new SimpleWebRTC({
      remoteVideosEl: 'remoteVideos',
      media: {
        audio: false,
        video: false
      },
      autoRequestMedia: false
  });

  webrtc.joinRoom('XXX');
}
```

Calling 'startStreaming()' on the page that should stream, and 'startWatching()' on the pages that should watch.
The issue is that when I've more than one watcher, I start getting black videos from the other watchers ...
I only want the video from the streamer. I don't want watchers to send any media.

Does someone has an idea ?

Thank you very much !

**Comment by Pixcell** [comment]
Ok, my bad,

fixed:

```js
function startWatching(){
  var webrtc = new SimpleWebRTC({
      remoteVideosEl: 'remoteVideos',
      media: {
        audio: false,
        video: false
      },
      receiveMedia: {
        offerToReceiveAudio: 0,
        offerToReceiveVideo: 0
      },
      autoRequestMedia: false
  });

  webrtc.joinRoom('OpenTutorials');
}
```

It's the offerToReceive flag that needs to be set to 0.
I find the name quite missleading, I though it meant that you wanted to receive audio and video, not send.

I leave it here, it may be helpfull to someone.
Feel free to delete this issue if you prefer.

**Comment by fippo** [comment]
that name is coming from the w3c webrtc api. Glad you could solve your issue!
