### ISSUE TITLE
Chrome update blocks getUserMedia

### ISSUE THREAD

**Issue by theDude30** [andyet/SimpleWebRTC#362]
Hi,
It appears that the latest chrome update blocks permission to webcam if the source URL is coming from HTTP.
I was wondering if you have any suggestions on how to workaround it(i tried iframe from HTTPS and the site was HTTP but it didn't work) ?

**Comment by xdumaine** [comment]
Is your app deployed to a domain or are you just developing on localhost?

**Comment by fippo** [comment]
deploy https. That is the only way. Requiring a secure window.location.origin has been announced for half a year now.
