### ISSUE TITLE
Chrome 47.  stream.stop is not a function

### ISSUE THREAD

**Issue by MichaelJCole** [andyet/SimpleWebRTC#363]
Hey, just noticed this on Chrome 47
```
SimpleWebRTC.prototype.stopScreenShare = function () {
    this.connection.emit('unshareScreen');
    var videoEl = document.getElementById('localScreen');
    var container = this.getRemoteVideoContainer();
    var stream = this.getLocalScreen();

    if (this.config.autoRemoveVideos && container && videoEl) {
        container.removeChild(videoEl);
    }

    // a hack to emit the event the removes the video
    // element that we want
    if (videoEl) this.emit('videoRemoved', videoEl);
    if (stream) stream.stop();                                                   <--------------------------
    this.webrtc.peers.forEach(function (peer) {
        if (peer.broadcaster) {
            peer.end();
        }
    });
```

I was doing something like this in my UI code  self.shareScreen is a button handler.
```
  self.shareScreen = function(enabled) {
    if (enabled) {
      if (self.webrtc.getLocalScreen()) self.webrtc.stopScreenShare(); // unshare
```

**Comment by fippo** [comment]
@legastero can you take a look please? Should be resolved by updating localMedia

**Comment by MichaelJCole** [comment]
So this may or may not be related.  When I call:

`self.webrtc.stopScreenShare();`

The Chrome sharing window doesn't go away...

**Comment by thg1101** [comment]
Problem is fairly simple, and related to M47's change in stopping media streams. 
https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.js#L426
replace
```
if (stream) stream.stop();
```
with
```
if (stream) {
     stream.getTracks().forEach(function (track) { track.stop(); });
}
```

Tested in Chrome M47 and FF 42

**Comment by MichaelJCole** [comment]
See also #366 which includes a check before calling .stop()

**Comment by xdumaine** [comment]
@MichaelJCole I'd prefer to completely move to using `track.stop`

**Comment by MichaelJCole** [comment]
@xdumaine I do not disagree.  If there's a better way, let's do it :-)

**Comment by prabhuk56** [comment]
i followed thg1101 instruction it works for me... thank you thg1101 .!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
