### ISSUE TITLE
Simplewebrtc in cloud 9

### ISSUE THREAD

**Issue by gie-sakura** [andyet/SimpleWebRTC#367]
Hi,

I'm making a small website on cloud9, the problem is that when I upload the files there isn't communication I've run it local and it works, but I don't know if I have to do something different when the project is running in the cloud.

Is there a way to fix this ?

Let me know if this is not clear.

Thanks.

**Comment by blackcrack** [comment]
btw, i guess, swrtc, would look in owncloud also pretty well as popup
for able to handle the owncloud (filesupload&lifting and colaborate also :) )

best regards
Blacky

**Comment by jorgesc343** [comment]
Hello GiaSakura, i have the same problem, i had my system in a traditional host and the webrtc was working so good, but when i migrate the system to cloud architecture to other server, my WebRTC didnt work, when i run the Webrtc in local , it work.
But when i test it with different internet connection  it doesnt work.
Can you solve the problem? do you found something to solve it? 
Reagards

**Comment by tgabi333** [comment]
There should be a problem about STUN and TURN.
