### ISSUE TITLE
bug for chrome v47

### ISSUE THREAD

**Issue by kokolijk** [andyet/SimpleWebRTC#369]
chrome v47

getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

  getUserMedia = function(constraints, onSuccess, onError) {
    ...
    return navigator.webkitGetUserMedia(constraints, onSuccess, onError);
  };

**Comment by fippo** [comment]
This has been announced by the Chrome team for half a year now. No way to work around it, you must use https.
