### ISSUE TITLE
Is simplewebrtc only p2p?

### ISSUE THREAD

**Issue by txgroup** [andyet/SimpleWebRTC#373]
Just a quick one. Is the simplewebrtc peer to peer? Can it be done client to server if it is p2p?

**Comment by fippo** [comment]
it's p2p, using full mesh, i.e. everyone connects to everyone else (possibly using a TURN server)

**Comment by choubb** [comment]
good to know. the maximum parties who ever tested? the quality and bandwith?

**Comment by xdumaine** [comment]
With high end hardware and really good networks, you'd be lucky to have 6 people. In reality, 3 or 4 maximum.
