### ISSUE TITLE
Mobile to Chrome - Black Box

### ISSUE THREAD

**Issue by ryanpager** [andyet/SimpleWebRTC#374]
So recently I upgraded simplertc to the newest version (we were running a seriously old one), and everything is running great. We are using coTurn for our turn/stun setup, and everything works as expected (browser to browser, mobile to mobile, web to mobile (minus chrome)).

The one issue that Im running into is that our mobile app (iOS/Android) is not working with the web app now. We get a black box every time. To make matters more confusing it is only when the mobile app connects to a Chrome browser.

Is there any information as to where to start looking for problems, or anything going wrong. No errors in the console are present really, we are on https, and webrtc-internals isn't really showing much....so im kind of stuck.

Edit -- I also know its only when Turn is required for Chrome to mobile. If the phone is on wifi, everything works perfectly.

Does anyone have any insight on this, or any info on this problem?

**Comment by xdumaine** [comment]
Anything helpful in the console? Have you checked chrome://webrtc-internals? A dump from there would help.

**Comment by ryanpager** [comment]
Here ya go, there is literally nothing in the console.

[webrtc_internals_dump (2).txt](https://github.com/andyet/SimpleWebRTC/files/76087/webrtc_internals_dump.2.txt)
[webrtc_internals_dump (1).txt](https://github.com/andyet/SimpleWebRTC/files/76086/webrtc_internals_dump.1.txt)

**Comment by fippo** [comment]
Both dumps show a setRemoteDescriptionOnFailure -- despite creating an offer, setremotedescription is called with type=offer.

Also an ice failure, even though the other side sends a relay candidate. No local relay candidate is gathered.

**Comment by ryanpager** [comment]
@fippo 

Yea, these are 1-1 sessions. So our mobile guy is rejecting the offer I send him (from browser), and resending back an offer instead. Were doing this cross platform using Xamarin -- so we had to use the iceLink platform. I suspect that maybe where the issue is.
