### ISSUE TITLE
When call is peer to peer, how can we set the port range to limited range instead of default random?

### ISSUE THREAD

**Issue by shamun** [andyet/SimpleWebRTC#376]
Some enterprise having issues to work with random default port ranges for allowing media connection over peer to peer.

Is there anyway within SimpleWebRTC (on Google Chrome, Firefox, Opera ), to setup a port range for media instead of allowing the default unlimited / unknown ranges?

**Comment by fippo** [comment]
use TURN for relay. Also, this is not the repository for asking questions about Chrome, please use the discuss-webrtc list for that.
