### ISSUE TITLE
Signaling-master is not working on localhost.

### ISSUE THREAD

**Issue by Jp2016** [andyet/SimpleWebRTC#377]
I have create signaling server on my local machine.

I am not able to create a link from Simplewebrtc project with my own signaling server.

I have changed the url in simplewebrtc constructor.

When i tried to create room and click on create button not happen anything and getting console error.

please find the attachment of error log when i used my own signaling server.
![signalingmastererror](https://cloud.githubusercontent.com/assets/16609014/12197256/895b39d2-b62b-11e5-8097-a4a43daad6ee.png)

**Comment by xdumaine** [comment]
What version of node are you running?

**Comment by Jp2016** [comment]
I am using  v4.2.3  node.js version.

**Comment by xdumaine** [comment]
This issue belongs on Signalmaster, not SimpleWebRTC, but it looks like [this commit][1] might be the cause. Doing some more digging...

[1]:https://github.com/socketio/socket.io/commit/3b00312fa72c9183db02d1c95db72307943fe712

**Comment by xdumaine** [comment]
I have a feeling that `signalmaster:144`

```javascript
    function clientsInRoom(name) {
        return io.sockets.clients(name).length;
    }
```
should be

```javascript
    function clientsInRoom(name) {
        var adapter = io.nsps['/'].adapter;
        return Object.keys(adapter.rooms[name] || {}}.length;
    }
```

**Comment by Jp2016** [comment]
Thanks for your advise.

Yes link is creating now.

But one more issue is there i can't see peer remote connection.

Now connection is not happening between  users.

I have attach one screenshot about the console error look at the following screen shot.

![screenshot_2](https://cloud.githubusercontent.com/assets/16609014/12256348/9608dae6-b922-11e5-884b-63eda144873d.png)

**Comment by Jp2016** [comment]
I got solution its problem of socket.io version.
