### ISSUE TITLE
Only receiving host ICE candidates

### ISSUE THREAD

**Issue by sebLopezCot** [andyet/SimpleWebRTC#381]
I keep getting ICE failures, and I believe they are associated with not receiving relay candidates at times when the peers are on completely different networks.

I've implemented SimpleWebRTC in my node app and while a good amount of the time a peer connection via ICE is successfully created, on numerous attempts I only receive host candidates when I should be receiving relay candidates. Even when I try to  filter for only relay candidates, I sometimes still get host candidates in my candidate buffer. I have already confirmed that the STUN/TURN servers are connecting properly through some debugging in wireshark.

I have one reproducible case: 
- Connecting 2 computers to 2 different networks, establish a peer connection.
- Switching one of them to another network. The peers try to re-connect through the signalling server.
- I get a failure  at some stage after adding ice candidates (couldn't pinpoint the exact failure). 
- I find that I only get HOST candidates.
- Even when I try to  filter for only relay candidates, I sometimes still get host candidates in my candidate buffer.
- If I re-load the web-page for one candidate, most of the time, it connects just fine.

**KEY QUESTION**: Anyone know why I am only getting HOST candidates only in this case?

-------------------------------------------

Specs:
- Windows 8.1
- Chrome version 48.0.2564.82 m
- simplewebrtc 1.19.0
- using xirsys for STUN/TURN relays

**Comment by fippo** [comment]
typically that means your stun and turn server is not working at all -- can you attach the wireshark dump?
Check the iceConfig with https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice.

Switching to another network typically requires an ice restart which is not implemented yet.

**Comment by sebLopezCot** [comment]
Here is the pcap file from one of my testing sessions. Around packets 3674 and 3934 are where I saw the ICE failure occur (also when one of the computers was switched to another network).
[test_001.pcap.pcapng.zip](https://github.com/andyet/SimpleWebRTC/files/103540/test_001.pcap.pcapng.zip)

**Comment by sebLopezCot** [comment]
Performing an ice restart seemed to do pretty well in solving this issue.
