### ISSUE TITLE
What is Javascript code to stop sharing Webcam on simple webrtc?

### ISSUE THREAD

**Issue by hhamanh** [andyet/SimpleWebRTC#382]
I want to build a button and when user click on that button it will stop sharing webcam. I tried all ways to stop sharing webcam but it doesn't work.

> webrtc.stop();
>         	document.getElementById("localVideo").innerHTML='';	
>             	document.getElementById("localVolume").innerHTML='';
>             	document.getElementById("localVideo").src = window.URL.createObjectURL(null);
>             	var track = stream.getTracks()[0]; 
>             	track.stop();
>             	document.getElementById("localVideo").style.display="none";
>             	stream.stop();
>             	webrtc.stopLocalMedia();
>             	var pc = new RTCPeerConnection();
>             	pc.close();

YOu can notice that when open webcam on Firefox, we can see a little webcam symbol on Firefox address bar. Click on it a message box will popup and ask us whether we can stop sharing the webcam. I want to do the same thing like that but using javascript.

so, can anyone tell me

**What is Javascript code to stop sharing Webcam on simple webrtc?**

**Comment by hhamanh** [comment]
seem I found a solution http://localhost:8888/video.html

**Comment by xdumaine** [comment]
You should use `webrtc.stopLocalVideo()`
