### ISSUE TITLE
How to block / unblock remote videos?

### ISSUE THREAD

**Issue by hhamanh** [andyet/SimpleWebRTC#384]
Ok, let say if there are >2 remote videos and for some reasons, we want to block some for a while ans then unblock them if we want to.

So, How to do that properly?

**Comment by xdumaine** [comment]
What do you mean by "block"? Do you want to prevent receiving the incoming streams, or stop those from receiving your outgoing stream? Are you trying to do this for the entire room or a subset?

**Comment by hhamanh** [comment]
Hi,

I want to block incoming stream. Even though the remote users can enter the room but he can not see and hear me and I also don't want to see and hear him

**Comment by xdumaine** [comment]
You can pause, hide, or mute the video tag attached to the streams you want to "block". See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

**Comment by gazpachu** [comment]
@xdumaine adding the `muted` attribute to the remote `video` tags doesn't mute the audio from those peers. Am I missing anything here?
