### ISSUE TITLE
Is there any free and stable Signaling server out there?

### ISSUE THREAD

**Issue by hhamanh** [andyet/SimpleWebRTC#386]
Simple WebRTC suggests us to build our own signaling server. Everyone will have their own signaling server and that is very redundant.

My question is that:

**Is there any free and stable Signaling server out there so that we can just put it into our SimpleWebRTC code as the following?**

> var webrtc = new SimpleWebRTC({
> ....
> url: 'https://free-signaling-server.com/'
> });

I tried 

> url: 'https://anon.talky.me/'

 but it didn't work.

I currently develop my App Engine app that uses Simple WebRTC technique. I know nothing about **node.js** and I also don't want to host my own signaling server. Because my app hosted on Google Cloud and I don't want another host?

**Comment by xdumaine** [comment]
If you want a service that does signaling for you, you can pay for something like TokBox or Twilio. SimpleWebRTC is an open library for running your own with simple setup.

**Comment by fippo** [comment]
xirsys.com might provide hosting for signalmaster. Not for free though.

**Comment by gladkikhartem** [comment]
I've created one, but it has different protocol than  SimpleWebRTC.
I'll add connector to SimpleWebRTC in near future.
https://github.com/gladkikhartem/koshare-router

**Comment by pointlinker** [comment]
If not free it is not decentralized. The payment is a point of failure. It should be a swarm of signaling servers incentivized by access to clients localStorage, making a fast and huge memory pool for mining or whatever. The servers would need WebRTC connections to the clients apps to have access their localStorages and making a great P2P network.
