### ISSUE TITLE
SimpleWebRTC example is maintaining or somethings like that why it is working?

### ISSUE THREAD

**Issue by hhamanh** [andyet/SimpleWebRTC#387]
Just want to know the signalling server of SimpleWebRTC example will be **available all the time** or it can be **turned off for maintaining**?

Yesterday it works but today it doesn't!!!

**Comment by fippo** [comment]
there are no availability guarantees for the sandbox server. Do not use it for production things. Actually I think it is way to reliable and should be turned off randomly at least once a day for a couple of minutes.
