### ISSUE TITLE
Update the peerConnectionConfig

### ISSUE THREAD

**Issue by busychild** [andyet/SimpleWebRTC#388]
We're currently facing a issue with updating the peerConnectionConfig. As we use a service which provides the STUN and TURN servers we've to update the configuration every 20 minutes (this is the lifetime of the credentials for the TURN server). So we just implemented a timer task to update the peerConnectionConfig (`webrtc.peerConnectionConfig.iceServers = ...`).

The problem is, that the `WebRTC.prototype.createPeer` is setting the parameters (`opts.parent = this`) which won't use the configuration from the `SimpleWebRTC` instance but from the `WebRTC` instance. Therefore the `createPeer` method is always using the initial configuration and not the updated one.

We implemented a hotfix for this but maybe there is a convenient way of updating the config?

Thanks and best regards

Florian

**Comment by tgabi333** [comment]
There are events from the server side see: https://github.com/andyet/SimpleWebRTC/commit/beb4c2c3d0753eebbff85216798df153e011e773
