### ISSUE TITLE
Dificuldade com stun/turn

### ISSUE THREAD

**Issue by welberty** [andyet/SimpleWebRTC#392]
I am having problems with video transmission when made of external connections mine. I do not know how to configure the servers turn and I think that is the problem.

**Comment by xdumaine** [comment]
Please read the docs, and see https://github.com/signalmaster

**Comment by welberty** [comment]
https://github.com/signalmaster error 404

**Comment by fippo** [comment]
its at https://github.com/andyet/signalmaster
