### ISSUE TITLE
how to integrate more sophisticated UI surrounding <video> tags?

### ISSUE THREAD

**Issue by artofspeed** [andyet/SimpleWebRTC#393]
The way SimpleWebRTC works, remote `<video>` tags are created directly as children of 'remoteVideos' container. This limits the kind of user interface you can create, as sometimes you need other elements surrounding these `<video>` tags to create a more sophisticated UI. Also, since simplewebrtc uses `getRemoteVideoContainer()` natively to update video and audio elements, it's kinda scary to modify those functionalities.

My question is, are there any ways to bypass this UI limit to create more complex visual elements? Any pointers are appreciated!

Thank you all!

**Comment by fippo** [comment]
see https://simplewebrtc.com/notsosimple.html#basic-overlay
