### ISSUE TITLE
any way to use the modules inside bundle.js?

### ISSUE THREAD

**Issue by artofspeed** [andyet/SimpleWebRTC#394]
`simplewebrtc.bundle.js` has some very nice modules like `adapter.js` and `hark.js`, is there a way to access them through the webrtc object, so we don't have to include them again? Thanks!

**Comment by xdumaine** [comment]
Not at this time. The bundle is a browserified bundle so it just exposed the SimpleWebRTC module. You could include each module individually including SimpleWebRTC and not use the bundle so nothing is included twice.

**Comment by artofspeed** [comment]
thx :)
