### ISSUE TITLE
Did VP9 worked with SimpleWebRTC?

### ISSUE THREAD

**Issue by shamun** [andyet/SimpleWebRTC#395]
I need to test VP9 stability and bandwidth performance for about 1week to compare with existing Sony, Polycom, LifeSize, Skype performance test. Just arrived all hardware in my laboratory.

Has anyone worked on VP9 yet please, appreciate some feedback. Also do you guys able to capture the real-time logs like AppRTC "i" doing, good for my rubber duck debugging. 

![screen shot 2016-02-15 at 21 13 58](https://cloud.githubusercontent.com/assets/107349/13059326/a4388df6-d429-11e5-9e63-8dabfce805e3.png)

**Comment by Hirtenknogger** [comment]
Capture the real-time logs would be a great feature!
