### ISSUE TITLE
Failed to set remote offer sdp: Called in wrong state: STATE_SENTOFFER

### ISSUE THREAD

**Issue by MichaelJCole** [andyet/SimpleWebRTC#398]
Hi, I started getting an error recently, probably because of a Chrome update:

It shows up as this in the console:

```
Uncaught (in promise) Error processing ICE candidate(anonymous function) @ simplewebrtc.bundle.js:1590(anonymous function) @ simplewebrtc.bundle.js:3040(anonymous function) @ simplewebrtc.bundle.js:4873(anonymous function) @ getusermedia.bundle.js:416(anonymous function) @ attachmediastream.bundle.js:380
```

With this as the value of `err`:

`Failed to set remote offer sdp: Called in wrong state: STATE_SENTOFFER`

It doesn't appear to affect operation doing browser-to-browser on my own computer.  I'm not sure about TURN or STUN consequences.  I'm using these words without completely understanding the protocol.

FYI: https://github.com/peers/peerjs/issues/286

**Comment by xdumaine** [comment]
I'm seeing this too.

**Comment by fippo** [comment]
dump?

**Comment by xdumaine** [comment]
Looks like this isn't an issue with the peer connection so much as it is with socket.io - My issue was caused by `data.client` now being `/socket-namespace#id` which didn't mach the output of `getSessionId()` - @MichaelJCole are you using a namespaced socket, or the default namespace?

**Comment by xdumaine** [comment]
Looks like it'd cause issues here https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.bundle.js#L338

**Comment by MichaelJCole** [comment]
Hey @xdumaine I looked at this a bit, and I'm not exactly sure how to respond.  I haven't spent alot of time with socket.io:

I don't think that's the case, but here's what I've got.

Server code to create and join:
```
    // Describe room members and state
    function describeRoom(name) {
      var room = io.nsps['/'].adapter.rooms[name];
      var ret = { clients: {} };

      var socketIds = Object.keys(room.sockets || {});
      var sockets = socketIds.forEach(function(socketId) {
        var aSocket = io.sockets.adapter.nsp.connected[socketId];
        ret.clients[socketId] = aSocket ? aSocket.resources : {};
      });
      return ret;
    }
    // Join a room
    function join(name, cb) {
      // sanity check
      if (typeof name !== 'string') return warning(socket.id + ': join failed.  roomname not a string');
      // leave any existing rooms
      removeStream();
      // Join the room
      socket.join(name);
      socket.room = name;
      // Callback description of sockets in room
      var desc = describeRoom(name);
      debug(socket.id + ': join ' + name);
      if (cb) cb(null, desc);
    }

    // Create new room
    socket.on('create', function (name, cb) {
      // default room name to uuid if only cb passed
      name = name || uuid();
      debug(socket.id + ': create? ' + name);

      // find and join room
      var room = io.nsps['/'].adapter.rooms[name];  // FIXME make this a utility function
      if (room && room.length) {
        if(cb) cb('taken');
      } else {
        join(name, cb);
      }
    });
    // Join existing room.
    socket.on('join', function(name, cb) {
      if (!name) return error('cannot join room with no name');
      join(name, cb);
    });
```

Output from server:
```
  signal attaching socketio events to http server +4s
  signal socket io server started +3ms
  signal /#JoH_hh4itLIiIrF1AAAA: connected +164ms
  signal /#JoH_hh4itLIiIrF1AAAA: join zabalkapioea5dlqqynencdvrg79ocmm2cec947i69v9q08 +180ms
  signal /#51g-HSRjZ5Y0TQiVAAAB: connected +2s
  signal /#51g-HSRjZ5Y0TQiVAAAB: join zabalkapioea5dlqqynencdvrg79ocmm2cec947i69v9q08 +40ms
# Refreshed browser to reconnect here.
  signal /#ObfVQjPCvCrD8zh5AAAC: connected +51s
  signal /#ObfVQjPCvCrD8zh5AAAC: join zabalkapioea5dlqqynencdvrg79ocmm2cec947i69v9q08 +4s
```

Till now, I've chalked it up to testing on the same LAN.  Clients can conference, so I haven't put alot of attention on it.

Does this intersect what you found?  Thanks!

**Comment by MichaelJCole** [comment]
Hey, circling back to this.  I updated to the latest version and the warning went away.  Hurray!   Thanks :-)

**Comment by Shubhamatmecs** [comment]
what do you mean by latest version
can you send me the link of documentation of the latest version

**Comment by MichaelJCole** [comment]
Hey @Shubhamatmecs try the version in master from 4 days ago.

**Comment by manishvpatel** [comment]
What are the reasons for this issue ? an any one describe here ?
