### ISSUE TITLE
My media data didn't go through my own TURN server

### ISSUE THREAD

**Issue by hiepnm** [andyet/SimpleWebRTC#399]
## My situation
I cloned 2 projects: SimpleWebRTC and signalmaster. Then I built them (npm install ...) and ran them. 
All of them deployed were OK. signalmaster ran on https://public_ip:8888, and webserver that serving webrtc client ran on https://public_ip:8000.
I configured signalmaster on config/production with turn and stun server. and on simplewebrtc.bundle.js of SimpleWebRTC project I pointed signalling server to signalmaster (listened on 8888). And in my turnserver configuration, I set no-auth to skip authentication on it.

Here is a part in the configuration of signalmaster (signalmaster/config/production.json):

> "stunservers": [
>     {
>       "url": "stun:stun.l.google.com:19302"
>     }
>   ],
>   "turnservers": [
>     {
>       "urls": ["turn:118.70.12.155"],
>       "secret": "testtesttest",
>       "expiry": 86400
>     }
>   ]

I used 2 machines to test this use case. Each machine was in another plain network (different NAT).
## My Issue
I used wireshark to capture network and relized that  the media data didn't go throgh my turn server.

**Comment by fippo** [comment]
webrtc will prefer the direct path if that works.

**Comment by Hirtenknogger** [comment]
@hiepnm you can force SimpleWebRTC to use your TURN Server by passing the following code in your constructor:
```
new SimpleWebRTC({
    peerConnectionConfig:{
        iceTransports: 'relay'
    }
});
```

**Comment by xdumaine** [comment]
Thanks @Hirtenknogger
