### ISSUE TITLE
Which version is socket.io client in simplewebrtc.bundle.js?

### ISSUE THREAD

**Issue by artofspeed** [andyet/SimpleWebRTC#401]
Sometimes my `node.js` app crash due to `Error : Lone surrogate` (`socketio's utf8.js` file). I'm suspecting it's because the socket.io client in `simplewebrtc.bundle.js` is incompatible with the socket.io version in the backend. Hence, it creates packets that the backend socket.io module can not read, which throws an error.

My backend socket.io version is 1.3.7, what is the version used in `simplewebrtc.bundle.js`?

**Comment by PraxisCreativa** [comment]
I had the same problem with the version of socket.io with simplewebrtc.bundle.js client and had to implement an earlier version of simplewebrtc.bundle.js and it worked.

**Comment by Hirtenknogger** [comment]
@artofspeed @PraxisCreativa SimpleWebRTC now also uses 1.3.7.
