### ISSUE TITLE
How do I start streaming after initialization?

### ISSUE THREAD

**Issue by tiger2380** [andyet/SimpleWebRTC#404]
Hello All. Additional information to the title, I set 'autoRequestMedia' to false because I don't want to start the video on load. I have a button on the page that trigger 'startLocalStream' event. The video comes up after I triggered the 'startLocalStream' event but I don't see it on the remote side.

So how can I push the localstream to the remote peer(s)?

Thanks.

**Comment by xdumaine** [comment]
You'll need to `startLocalMedia()` and then `joinRoom('room-name')`

**Comment by tiger2380** [comment]
Thanks. Just want I needed.
