### ISSUE TITLE
Cannot get property "nick" of peer.

### ISSUE THREAD

**Issue by antoree** [andyet/SimpleWebRTC#411]
`webrtc.on('createdPeer', function (peer) {
console.log('createdPeer ', peer);
console.log('nick ', peer.nick);
});`
In console.log I can see property "nick" available but I cannot access it (undefined).
<img width="358" alt="screen shot 2016-03-15 at 4 43 02 pm" src="https://cloud.githubusercontent.com/assets/14157850/13773689/3a82f990-eacd-11e5-8473-eccf100a1b9a.png">

**Comment by gunsline2** [comment]
try on this event bellow 
webrtc.on('videoAdded', function (video, peer) {
  console.log(peer.nick);
});

**Comment by antoree** [comment]
I did it for other situation. But there are a reason I have to use 'createdPeer' event: a user join room as a watcher, not giving  video and audio.

**Comment by antoree** [comment]
I solved it by access inside a setTimeout function.

**Comment by adamsiwiec** [comment]
@antoree, can you show me the code you used, because I am having the same problem

**Comment by gabrielmosermick** [comment]
I believe a setTimeout is not a "solution". How did you manage to do this?
