### ISSUE TITLE
Are there anyelse event for disconnected user? (not using 'videoRemoved')

### ISSUE THREAD

**Issue by antoree** [andyet/SimpleWebRTC#412]
I'm detecting people who joined room without video whenever they leave the room by any reason. 
They do not stream video so I can't use 'videoRemoved'.

Any help would be appreciated. Thanks in advandce.

**Comment by xdumaine** [comment]
You could listen to the `remove` event on the connection:

`webrtc.connection.on('remove', (peer) => console.log(peer)) // { id: <peer id> }`

**Comment by antoree** [comment]
Thank you, this solved my problem.

**Comment by Hirtenknogger** [comment]
Please close the Issue. @antoree @xdumaine
