### ISSUE TITLE
Some Events not going to work when calling "startLocalVideo"

### ISSUE THREAD

**Issue by antoree** [andyet/SimpleWebRTC#413]
Hi there,
These event not going to be listened anymore after I called "startLocalVideo": 
- videoAdded
- createdPeer

Look like it creates another instance of "webrtc"?

**Comment by xdumaine** [comment]
You'll have to be more specific with what you're asking, or how you've come to that conclusion.

**Comment by antoree** [comment]
I have two client that join same room have configure autoRequestMedia = false, my aim is to whenever they click button "Call", they will activate video and audio by calling "startLocalVideo".

The test case is:
- Client A click 'Call', video show up, client B see client A video.
- Client B click 'Call', video show up, but client A cannot see client B video because event 'videoAdded' not fired any more after calling function "startLocalVideo".

**Comment by antoree** [comment]
+1
I'm waiting for a slution for this case, can anyone has experience with this?

**Comment by Hirtenknogger** [comment]
I know this problem. You can work around it by rejoining the room.

**Comment by antoree** [comment]
Thanks for suggesting.
I've tried and there're bugs when trying to rejoin the room.

Event 'videoAdded' fired 2 times.
Event 'message' on webrtc.connection fired 4 times.

My final purporse is to make a simple chatting connection at the first time. After that they can click button "Call" to make just audio call, video off as default. They can determine to turn video on later.

Here's what I do but still have no result as all: both clients connect with autoRequestMedia = false, then join the same room, whenever they want to make a call, I used 'startLocalVideo' function.

Any help would be appreciated.

**Comment by Hirtenknogger** [comment]
Try something like this:
```
var hasJoinedRoom = false;

webrtc.on('connectionReady', function(){ 
  joinRoom();
});
webrtc.on('readyToCall', function(){
  joinRoom();
});
webrtc.on('localStream', function(){
  reJoinRoom();
});

function joinRoom() {
  if (!hasJoinedRoom){
    hasJoinedRoom = true;
	webrtc.joinRoom('room name');
  }
}
function reJoinRoom() {
  if (hasJoinedRoom){
    hasJoinedRoom = false;
    webrtc.leaveRoom();
    joinRoom();
   }
}
```

**Comment by Hirtenknogger** [comment]
I agree with @antoree. it is a bug.

Example to reproduce:
1. Client A joins Room. (connectionReady fired)
2. Client A allows access to his webcam. (localStream fired)
3. Client B joins Room. (connectionReady fired)
4. Client B sees Client As Video. (videoAdded fired)
5. Client B allows access to his webcam. (localStream fired)
6. BUG: Client A does not see Client Bs Video. (videoAdded is not fired!!!)

Should we fix this @fippo?

**Comment by xdumaine** [comment]
I'm not sure I'd call this a bug. You're explicitly calling `joinRoom` before `readyToCall` then you'll get undefined behavior. If you'd like to open a PR to add this feature (ability to add stream after joining), I would certainly be willing to discuss and review.
