### ISSUE TITLE
Using SimpleWebRTC with PHP 

### ISSUE THREAD

**Issue by HamzaAbdaoui** [andyet/SimpleWebRTC#423]
Hello,
I'm developing a web site using Javascript and PHP, and i want to use the video chat service offered by SimpleWebRTC in my site, but i didn't find the right way to do that..
Any help will be appreciated.

**Comment by MichaelJCole** [comment]
@HamzaAbdaoui SimpleWebRTC is useful in the browser.  You need to make a "Single Page App" to use it.  You got alot of googlin to do my friend.
