### ISSUE TITLE
Firefox: duplicated streams

### ISSUE THREAD

**Issue by VadimDez** [andyet/SimpleWebRTC#425]
In Firefox when duplicating video element with stream only original one will work, duplicated won't show anything.

**Comment by fippo** [comment]
can you show that in a jsfiddle? I think that is a know issue in Firefox...

**Comment by VadimDez** [comment]
You can find an example here: 
https://jsfiddle.net/teoeybgL/4/

Reverting ```"attachmediastream": "^1.3.5"``` back to ```"attachmediastream": "1.0.1"``` allows to clone video elements again, found in https://github.com/andyet/SimpleWebRTC/commit/c9f94d1a6bae07cca33750a3f3c39558c30da772#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by fippo** [comment]
this looks like cloneNode can't deal with the srcObject. As a workaround I'd recommend setting the srcObject property of the cloned video to that of the original one.

@mreavy, this sounds like a Firefox issue but at least I never heard of such an issue. Maybe you did?

**Comment by VadimDez** [comment]
Tested setting the srcObject of original video to cloned one in Firefox only and it seems to work 
https://jsfiddle.net/teoeybgL/6/

**Comment by mreavy** [comment]
Sorry for the delay in responding.  This is actually an issue with Media Playback, not WebRTC or the other media areas I lead; so I needed to do some "homework".  

You've definitely found a new bug in the Firefox Playback code.  If someone with all the details can file a bug, I'd really appreciate it.  Here's the link to follow when you're ready to file the bug: https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Audio%2FVideo%3A%20Playback

**Comment by xdumaine** [comment]
Closing, since we have confirmation of bug in FF.
