### ISSUE TITLE
conect a room without cam and mic

### ISSUE THREAD

**Issue by CarlosGude** [andyet/SimpleWebRTC#427]
Hi:

I 'm trying to create an environment where only anfrition can transmit your webcam and the other can only use text chat. can gibe me any advice?

**Comment by pbojinov** [comment]
@CarlosGude you can instantiate the `SimpleWebRTC` object with the media contraints set to turn off video and audio. By default the contraints are set to `{ video: true, audio: true }`. Here's some docs on what else you can pass in as [mediaContraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Parameters).

Using the config from the [examples](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Parameters), here's the cam and mic turned off:
```javascript
var webrtc = new SimpleWebRTC({
    // the id/element dom element that will hold "our" video
    localVideoEl: 'localVideo',
    // the id/element dom element that will hold remote videos
    remoteVideosEl: 'remoteVideos',
    // turn off video and audio
    media: { video: false, audio: false} // <------------- 
});
```

Then to use text chat only, you can call `webrtc.sendDirectlyToAll` broadcast a message to all peers in the room via a dataChannel (DataChannels are turned on by default). Or `webrtc.sendToAll` to broadcasts a message to all peers in the room via the signaling channel (websocket).

**Comment by xdumaine** [comment]
@pbojinov Thanks for jumping in with some info. If you're up for it, make a PR for this to explain it in the `notsosimple.html` page.

**Comment by pbojinov** [comment]
@xdumaine that sounds good, I'll put together a PR
