### ISSUE TITLE
TURN Server with Firefox-Chrome: "ICE failed, see about:webrtc for more details"

### ISSUE THREAD

**Issue by Hirtenknogger** [andyet/SimpleWebRTC#428]
I use Coturn as TURN server with TURN REST API for authentication.
To test Coturn i forced SimpleWebRTC to use relay.
I want to use the alternate-server option for load-balancing.
Everything works good between chrome-chrome.
But there is a problem between firefox-chrome and firefox-firefox.

Fireofx console says:
ICE failed, see about:webrtc for more details

about:webrtc says:
Error processing response: Operation rejected, stun error code 0.
Message does not correspond to any registered stun ctx.

**Comment by Hirtenknogger** [comment]
I suspect firefox does not support 300 ALTERNATE_SERVER?!

**Comment by sashaegorov** [comment]
Hi,  take a look my [SO answer](http://stackoverflow.com/questions/36627529/coturn-turnserver-error-437-mismatched-allocation-wrong-transaction-id-webr/). You'll find working configs there, however, they are for **reTurn** STUN/TURN-server, not **coturn**. Works for all possible case such as NAT/Proxies/Chome/Firefox.

**Comment by fippo** [comment]
paging @nils-ohlmeier who probably knows if FF supports this

**Comment by Hirtenknogger** [comment]
@fippo I have found this one: https://bugzilla.mozilla.org/show_bug.cgi?id=857668
But there is no progress :-(

**Comment by nils-ohlmeier** [comment]
Yes @Hirtenknogger is correct: no support for ALTERNATE-SERVER yet (BTW also no support for long term auth of binding requests in case you want to try that coturn feature).

**Comment by Hirtenknogger** [comment]
@nils-ohlmeier Is there a plan to support ALTERNATE-SERVER this year?

**Comment by nils-ohlmeier** [comment]
The current priority P4 means that we are not going to get this done this year. But priorities can change if we get enough demand for a bug. So if you express your interest for that feature in the bug report we can probably bump the priority :-)

**Comment by Hirtenknogger** [comment]
@nils-ohlmeier I have expressed my interest to support bumping the priority! Would be great to see this feature in firefox :-)

**Comment by xdumaine** [comment]
OK to close this one, since we have linked FF issue @Hirtenknogger @fippo ?

**Comment by Hirtenknogger** [comment]
Yes i will close it!
