### ISSUE TITLE
Is it possible to use SimpleWebRTC with my own STUN / TURN servers?

### ISSUE THREAD

**Issue by think123** [andyet/SimpleWebRTC#429]
I've set up restund on my server. How would I configure SimpleWebRTC to work with it?

**Comment by Hirtenknogger** [comment]
Do you use Signalmaster for signaling?

**Comment by think123** [comment]
I haven't set up the signalling yet, but I'm planning to use it, yes.

**Comment by fippo** [comment]
run your own and let it give out credentials. The sandbox server is not supposed to be used for production apps (which is the reason it doesn't give out TURN credentials)

**Comment by think123** [comment]
Okay. But is there any way that I can use the simpleWebRTC plugin or something? It seems to implement the client-side media streaming aspects, and it would save me a lot of time if I could just plug it into my signaling and STUN/TURN servers.

**Comment by fippo** [comment]
configure simplewebrtc to point to your signalmaster (see [here](https://simplewebrtc.com/notsosimple.html#sandbox-server)) and things should work (if signalmaster is configured correctly and pointing to the right turn server)

**Comment by think123** [comment]
Ah, thank you very much for that link. So as long as I set up a connection to the signaling server and configure the signaling server appropriately, I only need to connect to the signaling server in simpleWebRTC, is that correct?

**Comment by fippo** [comment]
exactly. No point in making this hard :-)

**Comment by think123** [comment]
Thanks for that - I'll see what I can do. 👍

**Comment by think123** [comment]
I've installed signalmaster on my server for www.tuotr.com by downloading the gist. It says "signal master is running at: http://localhost:8888" - why can't I see it at my website URL "http://tuotr.com:8888"?

**Comment by think123** [comment]
I first ran `./scripts/generate-ssl-certs.sh`, then I ran `NODE_ENV=production node server.js`, and now instead of showing a blank page in my browser for http://tuotr.com:8888, it now shows "this site can't be reached".

**Comment by think123** [comment]
I keep getting an error of `ERR_CONNECTION_RESET` when I try to write http://www.tuotr.com:8888 in my simpleWebRTC script.

**Comment by Hirtenknogger** [comment]
secure mode is enabled. should be https://.....

**Comment by Hirtenknogger** [comment]
@think123 your production.json says:
`
"/* secure */": "/* whether this connects via https */",
"secure": true,
`
;)

**Comment by think123** [comment]
Yeah, I'm still not too sure how to get it working. I hosted the solution on my website, which uses HTTPS, and I can see two copies of my face within both browser tabs. When I load it on another computer, I can't see the other person.

**Comment by think123** [comment]
I think the problem is that somehow signalmaster or whatever is not working under a properly secure connection, because when I load it on my computer it shows that the HTTPS connection is not secure. As both of my tabs are not under a secure HTTPS connection, it loads with video and audio properly. 
![Screen Shot](https://cloud.githubusercontent.com/assets/2109121/15213772/94b82c40-188c-11e6-85be-0c41e4853a72.png)
When I load it on another computer, the connection is secure (I think this has to do with some extension that I've installed), and then I can't see their screen anymore.

**Comment by Hirtenknogger** [comment]
you have to accept your certificates first because they are self-signed.

**Comment by think123** [comment]
How would I do that?

**Comment by Hirtenknogger** [comment]
connect to https://your-signalmaster:8888 and accept them.

**Comment by think123** [comment]
The page gives me an empty screen - I try loading https://www.tuotr.com:8888 and it's empty...?

**Comment by think123** [comment]
I wrote this part inside `production.json`:

```
"turnservers": [
    {
      "urls": ["turn:www.tuotr.com:8080"],
      "secret": "turnserversharedsecret",
      "expiry": 86400
    }
  ]
```

I have run the restund server on the 8080 port.

**Comment by think123** [comment]
Hahaha ok I got it now - I just needed to open the console, and go to something like https://www.tuotr.com:8888/socket.io/... and it works for me. Thanks for your help!

**Comment by think123** [comment]
Can I buy an SSL certificate and use that for the verification?

**Comment by think123** [comment]
If so, how would I do that?

**Comment by xdumaine** [comment]
Please ask questions about SSL certs for websites on something like https://serverfault.com
