### ISSUE TITLE
peer.pc.getStats() ERROR

### ISSUE THREAD

**Issue by Hirtenknogger** [andyet/SimpleWebRTC#431]
I'm calling 
`
peer.pc.getStats(null, function(results){
    ...
});
`
in the videoAdded event (like demonstrated in http://webrtc.github.io/samples/src/content/peerconnection/constraints/) and it says:
`
e is not a function
`

When i call
`
peer.pc.getStats(function(results){
    ...
});
`
then i'm getting no Error but results is undefined.

**Comment by Hirtenknogger** [comment]
sorry i'm using a compressed version of you lib. So the error message is not correct.
`
cb is not a function
`
this error occures when you are trying to call the callback in your bundle on line 4752.

**Comment by fippo** [comment]
the getStats API is different for historical reasons. Try
```
webrtc.getPeers()[0].pc.getStats(function(err, stats) { console.log(stats); })
```

**Comment by Hirtenknogger** [comment]
@fippo it works! Thank you!!
