### ISSUE TITLE
Audio Problem

### ISSUE THREAD

**Issue by varysoft** [andyet/SimpleWebRTC#433]
Hey,

I've played around with SimpleWebRTC and the basics worked out of the box.
Which is cool ... ;-)

But I have one annoying problem when connecting with 2 smartphones: 
I always hear my own audio-stream as an echo on my phone. 
I also tried talky.io and there I have the same problem.
Is this a hardware problem or can I "adjust" this somehow ?

Thanks in advance !

**Comment by fippo** [comment]
it's a problem with physics. Echo cancellation algorithms are not designed for local testing.

**Comment by varysoft** [comment]
I have the same problem on talky.io ... So local testing should not be the problem ... or ?
When I use a headset, the echo disapears ... very strange ...

**Comment by xdumaine** [comment]
When he says local testing he means two devices in the same physical location, not localhost. 

> When I use a headset, the echo disapears ... very strange ...

This is not strange at all. Think about what is happening. The audio from one device's speaker is being picked up by the microphone on the other device. When using a headset, the speaker is not loud enough to be picked up by the other device's microphone.
