### ISSUE TITLE
Force H.264

### ISSUE THREAD

**Issue by Hirtenknogger** [andyet/SimpleWebRTC#436]
Is it possible to force h.264 codec for sdp offer instead of vp8?

**Comment by tgabi333** [comment]
You have to the sdp lines

**Comment by Hirtenknogger** [comment]
@tgabi333 I do not understand what you mean. How can I change the sdp offer/answer in SimpleWebRTC?

**Comment by fippo** [comment]
do it at the signaling server (change the order of codecs in the m= line).
SDP mangling is not supported because it's a sure way to shoot yourself into the foot.

**Comment by Hirtenknogger** [comment]
@fippo Thanks! I will try to change the order of codecs with my Signalmaster but i'm not really sure how to do so.

**Comment by tobiasps** [comment]
@janwendt did you figure out how to do this? I can seem to find this "m=" line in the signalmaster code.

**Comment by xdumaine** [comment]
@tobiasps Your code in signalmaster will have to watch the incoming messages and modify the SDP. the "m=" line is a line of text in the SDP message.

**Comment by tobiasps** [comment]
For anyone stumbling on this, here is my implementation of changing the order of the available codecs: https://github.com/tobiasps/signalmaster/commit/07fda1c76c2e4084482ebe4a82fc39ed10edae1c

Please note I'm using some logging facility that is not in the upstream code.

**Comment by fix2015** [comment]
@tobiasps is it works? for me it doesnt'
