### ISSUE TITLE
send 4 webcams from one app

### ISSUE THREAD

**Issue by alexey2baranov** [andyet/SimpleWebRTC#440]
Hello!

Is it possible to send 4 videostreams at the same time from 4 diffrerent webcams inside one webapp?

**Comment by Hirtenknogger** [comment]
@alexey2baranov #373

**Comment by alexey2baranov** [comment]
OK/ i have read #373 issue. I understand that it is possible to communicate up to 4-6 people in one room. My question is it possible to send all this streams FROM ONE WEBAPP. 

As i can see chrome let me choose only one webcam per page not more. I suppose there is a way to iterate every connected webcam programmaticaly and next maybe there is a way to connect one separate SimpleWebRTC object per each webcam and then i could stream them to somewhere independently. This is my question

**Comment by fippo** [comment]
you can use navigator.mediaDevices.enumerateDevices and then pass device ids. However, the SDP generated from this is not interoperable between browsers which blocks this from getting properly supported any time soon

**Comment by alexey2baranov** [comment]
navigator.mediaDevices.enumerateDevices  is very nice! It got me all my webcams. 

Is it pissible to connect one  SimpleWebRTC object per each webcam?

**Comment by alexey2baranov** [comment]
He there! Is any ideas for our issue?

**Comment by fippo** [comment]
yes. You might want to pass
```
            socketio: {'force new connection':true}
```
to stop socket.io from doing silly things and tune the receiveMedia options so that only one of the objects receives stuff.

**Comment by alexey2baranov** [comment]
Thanks you for reply. 
socketio: {'force new connection':true} is one step closer to our goal. It allows open few SimpleWebRTC connection form the same page and this is great. But the problem is that all this streams captured from the same webcam. We are very looking for capturing diffrenet webcams.

The final goal of our project is to write simple chrome app which will generate realtime 3D hologram piramid video like hire https://www.youtube.com/watch?v=yZDGQmwM3jE. So we need to capture 4 webcams from one chrome page.

**Comment by fippo** [comment]
did you pass the deviceId in each media.video option?

**Comment by alexey2baranov** [comment]
Oh very thank you all together. We are did it. Yes, passing deviceid to media object is the last thing we need. Now it works as expected!
