### ISSUE TITLE
can I take a snapshot of the stream?

### ISSUE THREAD

**Issue by CarlosGude** [andyet/SimpleWebRTC#443]
My question is simple, I want to put a button to take a picture of the camera that is serving. 

Thanks to all and sorry for my english

**Comment by fippo** [comment]
that is not directly related to simplewebrtc. Try [this code](https://github.com/legastero/jingle-interop-demos/blob/gh-pages/stanzaio/index.html#L158-L184), you'll probably want to change the element id. Possibly, you just want the data url and return that.
