### ISSUE TITLE
4 webcams  consumes 100% of 6-core processor

### ISSUE THREAD

**Issue by alexey2baranov** [andyet/SimpleWebRTC#448]
Why is it so much processor consumption? Is it possible to ask Chrome use videocard for video encode?

**Comment by Hirtenknogger** [comment]
Because older CPUs do not support VP8 hardware decoding and encoding!

**Comment by fippo** [comment]
realtime video encoding is hard. Try lowering the framerate or resolution

**Comment by KaptenJansson** [comment]
Resolution, color format, FPS and bitrate is very relevant determining if its consuming to much CPU. Also rendering can be expensive.

Also, what CPU is this and what OS?

**Comment by tgabi333** [comment]
Also make sure that you use the newest version of chrome

**Comment by alexey2baranov** [comment]
Thank you fir your replys. I will collect cpu, gpu, os and chrome version in a hour and notify hire. And also as i understand webrtc uses google codec vp8, right? I have readed a litle abput vp8 and found that google add the newest codec vp9 into chrome. Should we buy cpu with vp9 hardware  encoding for better perfomance? 

Thanks.

**Comment by Hirtenknogger** [comment]
VP9 takes more CPU than VP8

**Comment by KaptenJansson** [comment]
Chrome supports VP8, VP9 and H264. One of the issues you will find is that there aren't (not that I know of) any desktop/laptop grade CPU's nor any GPU's with VP8 or VP9 hardware acceleration. Lots of GPU's however support H264 and HEVC (H265) hardware acceleration.

In the mobile space there are quite a few [SOC's](http://wiki.webmproject.org/hardware/socs) supporting VP8 and VP9 hardware encode/decode.

And yes, [VP9](https://developers.google.com/web/updates/2016/01/vp9-webrtc) uses about ~20% more CPU to give the same quality as VP8 using ~30% less bits.

**Comment by Hirtenknogger** [comment]
I'm having the same Problem. I would love to see H.264 as default video codec in webrtc without modify sdp ( #436)

**Comment by KaptenJansson** [comment]
That will not happen, it will be supported but not default in Chrome that is. Changing the SDP is trivial though, example [here](https://github.com/webrtc/apprtc/blob/master/src/web_app/js/sdputils.js#L288-L296).

**Comment by alexey2baranov** [comment]
OK. Hire is a real hardware. We have 
AMD FX-6200 Six-Core-Processor 4,75GHz
NVidia GeForce GTX 960 
Default WebRTC 640x480 resolution
Windows 7 64bit 

As you can see it is enough for 4 webcams

**Comment by Hirtenknogger** [comment]
The AMD FX-6200 does not support VP8, VP9 and H264 hardware decoding and encoding!

**Comment by tgabi333** [comment]
Which x68 has support for hw encoding?

**Comment by Hirtenknogger** [comment]
Intel Broadwell and Skylake CPUs

**Comment by tgabi333** [comment]
You mean GPUs?

**Comment by Hirtenknogger** [comment]
@tgabi333 No

**Comment by KaptenJansson** [comment]
@Hirtenknogger what codecs do they support and which profile (H264 for real time video is different)? Also do they support encode and decode? I do know that most GPU and many CPU's support H264 decode and then most GPU's support encode as well.

In Chrome you can check what's active here: chrome://gpu/. It does not however list the WebRTC HW capabilities AFAIK, rather H264 decode for youtube etc.

**Comment by Hirtenknogger** [comment]
Skylake supports VP8 (encoding and decoding), VP9 (only decoding), H264 (encoding and decoding), H265 8bit (encoding and decoding) and H265 10bit (only decoding). 

If you want more information take a look at this article: http://www.anandtech.com/show/9562/intels-skylake-gpu-analyzing-the-media-capabilities

To get besser performance you can lower the resolution (<720p) and/or framerate (15-25fps) by setting this one:
```
webrtc = new SimpleWebRTC({
    media: {
        audio: true,
        video: {
          width: { max: 640 },
          height: { max: 480 },
          frameRate: { max: 15 },
        }
    }
});
```

**Comment by alexey2baranov** [comment]
OK I understand we could not ask chrome HW encode and decode streams with current hardware. Intel Skylake PC is not so chip as we like to be. So we get think into another side

**Comment by KaptenJansson** [comment]
@Hirtenknogger I see, to clarify things however, it's the GPU part in the Intel CPU's that provide those parts hence if you get a Xeon or an extreme edition (X99 etc) variant it will not have those capabilities since they do not have the GPU chips inside.
