### ISSUE TITLE
WebRTC fingerprints

### ISSUE THREAD

**Issue by Hirtenknogger** [andyet/SimpleWebRTC#452]
Why is WebRTC using fingerprints?

**Comment by Hirtenknogger** [comment]
Is it for demultiplexing?

**Comment by fippo** [comment]
the a=fingerprint in the SDP? https://tools.ietf.org/html/rfc5764 -- it is for encryption which is mandatory in WebRTC and the older a=crypto method was considered meh

**Comment by Hirtenknogger** [comment]
@fippo No, I meant the fingerprints in the TURN messages.

**Comment by fippo** [comment]
are you talking about the turn credentials? See https://github.com/andyet/signalmaster/blob/master/sockets.js#L118 also the paragraph above that

**Comment by Hirtenknogger** [comment]
No ich mean the fingerprint in the TURN messages (see fingerprint: https://github.com/coturn/coturn/wiki/turnserver)

**Comment by fippo** [comment]
see https://tools.ietf.org/html/rfc5389#section-8 then. I don't think chrome adds one for messages relayed via turn but does add them for regular ice stuff
