### ISSUE TITLE
BUG - 1080p never sending

### ISSUE THREAD

**Issue by shamun** [andyet/SimpleWebRTC#453]
I have been trying to send 1080p with 30fps (720p and lower resolution worked always). But 1080p is not sending accurate width and height.

This is what chrome://webrtc-internals/ keep showing, where requested to use 1080p but sending lower height and width.

![screen shot 2016-06-20 at 15 41 23](https://cloud.githubusercontent.com/assets/107349/16196317/d8a8524c-36fd-11e6-81a0-452bdfa65a46.png)

**Comment by fippo** [comment]
your bandwidth is not sufficient. Or the bandwidth estimate is not yet high enough to show that you could be sending 1080p.

Not a simplewebrtc issue either way.

**Comment by shamun** [comment]
I put PC1 and PC2 into CABLE on same router, Connection was made local PC to local PC. 
Still 1080p never worked. `chrome://webrtc-internals/` drops 1080p resolution, after 1 minute automatically to some awkward resolution. 100% BUG, should be tested and reported.

But when i used 720p it worked. 

Can you also please report it, same result with AppRTC (https://apprtc.appspot.com/r/997229711?debug=loopback&minre=1920x1080&r=watthe ). Thank you.
