### ISSUE TITLE
use dataChannel when user has no camera or microphone

### ISSUE THREAD

**Issue by artofspeed** [andyet/SimpleWebRTC#458]
is it possible to still use dataChannel to transmit data between peers, when they don't have camera or microphone?

thanks!

**Comment by fippo** [comment]
yes, see the [filetransfer example](https://simplewebrtc.com/notsosimple.html#filetransfer) for some hints on how to do that.

**Comment by artofspeed** [comment]
is it possible to text chat between peers, not just file upload?

**Comment by fippo** [comment]
see the sendDirectly and sendDirectlyToAll methods.

**Comment by artofspeed** [comment]
thanks, this works
