### ISSUE TITLE
Firefox NotSupportedError: track in constructed stream not yet supported (see Bug 1259236).

### ISSUE THREAD

**Issue by itree** [andyet/SimpleWebRTC#461]
This happens on Firefox 47.0.1 (works find in chrome)

When another user joins this shows up in the console. As of know SimpleWebRTC does NOT work in latest version of Firefox. Only in Chrome.  

> NotSupportedError: track in constructed stream not yet supported (see Bug 1259236).

RTCPeerConnection.prototype.addTrack()
 PeerConnection.js:1059
RTCPeerConnection.prototype.addStream/<()
 PeerConnection.js:1027
forEach()
 self-hosted:232
RTCPeerConnection.prototype.addStream()
 PeerConnection.js:1027
[64]</TraceablePeerConnection.prototype.addStream()
 simplewebrtc.bundle.js:10164
bound ()
 self-hosted:752
Peer/<()
 simplewebrtc.bundle.js:13754
forEach()
 self-hosted:232
Peer()
 simplewebrtc.bundle.js:13753
[83]</WebRTC.prototype.createPeer()
 simplewebrtc.bundle.js:14588
[81]</SimpleWebRTC.prototype.joinRoom/<()
 simplewebrtc.bundle.js:14312
[58]</Socket.prototype.onack()
 simplewebrtc.bundle.js:9306
[58]</Socket.prototype.onpacket()
 simplewebrtc.bundle.js:9231
[7]</module.exports/<()
 simplewebrtc.bundle.js:376
[8]</Emitter.prototype.emit()
 simplewebrtc.bundle.js:514
[56]</Manager.prototype.ondecoded()
 simplewebrtc.bundle.js:8781
[7]</module.exports/<()
 simplewebrtc.bundle.js:376
[8]</Emitter.prototype.emit()
 simplewebrtc.bundle.js:514
[61]</Decoder.prototype.add()
 simplewebrtc.bundle.js:9867
[56]</Manager.prototype.ondata()
 simplewebrtc.bundle.js:8771
[7]</module.exports/<()
 simplewebrtc.bundle.js:376
[8]</Emitter.prototype.emit()
 simplewebrtc.bundle.js:514
[13]</</Socket.prototype.onPacket()
 simplewebrtc.bundle.js:1140
[13]</</Socket.prototype.setTransport/<()
 simplewebrtc.bundle.js:958
[8]</Emitter.prototype.emit()
 simplewebrtc.bundle.js:514
[14]</Transport.prototype.onPacket()
 simplewebrtc.bundle.js:1565
[14]</Transport.prototype.onData()
 simplewebrtc.bundle.js:1557
[19]</WS.prototype.addEventListeners/this.ws.onmessage()
 simplewebrtc.bundle.js:2620
 simplewebrtc.bundle.js:10164:0

**Comment by fippo** [comment]
simplewebrtc.com/demo.html works fine here in Firefox.

**Comment by itree** [comment]
hmmm, notice you are using latest-v2.js, 

I just did a build 
> npm install; node build.js;
Then I'm using the simplewebrtc.bundle.js

I'm using the latest code from the github 

Are you guys using a branch or tag on simplewebrtc.com/demo.html ?

**Comment by grsh** [comment]
with "simplewebrtc.bundle.js" I can reproduce in my local .

**Comment by fippo** [comment]
latest-v2 is usually updated whenever a new version is published to npm

**Comment by itree** [comment]
Ok, so there seems to be a bug in the build process. in build.js ?

**Comment by fippo** [comment]
a bundle from master works fine here with the index.html test page. Can you compare options?

**Comment by grsh** [comment]
@fippo  Yes with index.html page it is working perfect. 
 I have confirm with firefox 47.0.1.
But seems like some trick . if I am using simplewebrtc.bundle.js in my own portal then it is giving that log and video from another peer is not added..
I will do more investigation tomorrow and will share my more feedback

**Comment by grsh** [comment]
@fippo  here it is .
When we use `autoAdjustMic: true` only then we have that in console and which the problem .
thing is that when we use **autoAdjustMic** then it is calling **GainController** and from GainController has code `stream.addTrack`. which is causing problem.
https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.bundle.js#L5323
https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.bundle.js#L5584

In **index.html** it is using `autoAdjustMic: false` so it is not causing same error.
https://github.com/andyet/SimpleWebRTC/blob/master/index.html#L55

**Comment by fippo** [comment]
don't use that feature, it has been removed from the documentation for a reason.

**Comment by grsh** [comment]
@fippo  okay thanks for the feedback and support.

**Comment by itree** [comment]
@grsh thanks.  I can confirm that adding the autoAdjustMic is indeed what is causing the problem for firefox.
