### ISSUE TITLE
createRoom is nessesary?

### ISSUE THREAD

**Issue by alexey2baranov** [andyet/SimpleWebRTC#464]
What difference between createRoom and joinRoom? Does createRoom is necessary before joining ?

**Comment by tgabi333** [comment]
You will find the anwser here: https://github.com/andyet/signalmaster/blob/master/sockets.js

`createRoom` is creating a new room checking for that name if it's taken or not.

`joinRoom` doesn't do any checks, you'll be in that room, no matter if it's an existing room with participants or a not existent (which will create that room - socket.io behavior)
