### ISSUE TITLE
HTTP not supported

### ISSUE THREAD

**Issue by marcogreselin** [andyet/SimpleWebRTC#467]
Hello, from version 47 of Chrome, `getUserMedia` is no longer supported over HTTP. Is there a workaround? Is it possible to embed this in an HTTP website (the JavaScript is actually hosted in an HTTPS environment...).

**Comment by fippo** [comment]
No, this is per origin which will still be HTTP. See http://www.tokbox.com/blog/the-impact-of-googles-new-chrome-security-policy-on-webrtc/ for a pretty good explanation of the issue.

**Comment by tgabi333** [comment]
AFAIK there is no workaround for that

**Comment by marcogreselin** [comment]
This is pretty bad for the app that I was building because it was supposed to be embedded on other websites and these are not usually HTTPS.

**Comment by marcogreselin** [comment]
It says: consider switching your application to a secure origin, such as HTTPS. Such as means there are other secure origins that would be accepted?

**Comment by tgabi333** [comment]
Secure origins: https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features
