### ISSUE TITLE
new event localVideoAdded

### ISSUE THREAD

**Issue by alexey2baranov** [andyet/SimpleWebRTC#471]
Hello dear friends!

We ask you to add new event localVideoAdded(localVideoEl) very same with videoAdded. This new event is very important for some kind of apps with multiple webcams on one host machine.

**Comment by tgabi333** [comment]
There is an event called `localStream` what is suitable for you.

**Comment by alexey2baranov** [comment]
thank you for reply/ I do not see this type of event into https://github.com/andyet/SimpleWebRTC#events

**Comment by alexey2baranov** [comment]
Looks like this event fired but not documented. anyway it does not handle video element like videoAdded( videoEl, peer) so no way to arrange video elements on the screen

**Comment by alexey2baranov** [comment]
OK we are trying to find corresponding video elemtnt/ Looks like this event fired before video element created, don't it?

**Comment by tgabi333** [comment]
It's not an elegant solution, but try to use a setTimeout

**Comment by alexey2baranov** [comment]
Maybe one of the way is to prevent default video element and then inside localStream event  manual creating <video>  with src=localStream ?

**Comment by tgabi333** [comment]
setTimeout should work.

**Comment by alexey2baranov** [comment]
setTimeout is very very dependent of CPU and RAM. it will be plan "B" if other ones do not success

**Comment by alexey2baranov** [comment]
OK/ if we deside to set timeout, what interval do you recommend us?

**Comment by tgabi333** [comment]
It should work with 0. That will allow the other event handlers to run and make the dom modification (eg: insert the new video element).

**Comment by alexey2baranov** [comment]
hire is our final code. and looks like it works))
```

                        webrtc.on('localStream', function (stream) {
                            setTimeout(function(){
                                let video= $('#localVideos video:not([id])').attr('id', eachDevice.deviceId).get(0);
//managing video ...

                            },0);

```

**Comment by alexey2baranov** [comment]
> You can still find the corresponding video element in the document

how correct do this in multicam app?

**Comment by xdumaine** [comment]
@alexey2baranov You'd have to associate the video element with the stream you want to use. Set an id/class/etc.

**Comment by alexey2baranov** [comment]
I have tried this way. But the video had very low fps (near 5fps) . The default video that was created by SimpleWebRTC is normal near 30fps.
I had changed localVideoEl in SimpleWebRTC config to empty string to prevent default video but get the same result on manualy created video 5fps

**Comment by fippo** [comment]
set autoplay to true on the video element you create

**Comment by alexey2baranov** [comment]
now it works like a charm

**Comment by alexey2baranov** [comment]
thank you very much!
