### ISSUE TITLE
SimpleWebRTC with Cordova on Android

### ISSUE THREAD

**Issue by ramsestom** [andyet/SimpleWebRTC#473]
Hi. I am trying to use simpleWebRTC inside a cordova (ionic) app on Android. Unfortunately, when trying to init a call, webrtc throw a localMediaError of type NavigatorUserMediaError,DevicesNotFoundError
I am using a Crosswalk WebView in my ionic app so webrtc is supposed to be supported by the browser rendering my cordova app (anyway, receving a webrtc call from my pc to the android device running the app works fine so webrtc seems to work). The problem is probably more a cordova related issue (camera access rights not correctly defined or something like this) but if anyone has already succeed to run simpleWebRTC inside a cordova app on android, I would be more than pleased to have his feedback.

**Comment by Pato91** [comment]
Hi... did anyone resolve the simplewebrtc issue with ionic? I would be more delighted if someone shared a snippet or piece of code on how to use it with ionic... I am new to webrtc and I have tried to read about some implementations both using the browser support for webrtc(which worked well in the browser not the emulator in ionic 3) and the platform support but I haven't understood enough to make it work on different platforms(mainly android) and it would be great if someone share an JS code snippet of how to use the simplewebrtc with ionic 3. Thanks

**Comment by xdumaine** [comment]
@ramsestom @Pato91 this doesn't sound specific to this library, so I'd encourage you to reopen this ticket on the ionic/cordova side, or the relevant plugin. You'll likely get a helpful response over there. If you're able to get another webrtc page going (try any of https://github.com/webrtc/samples), and still have trouble with SimpleWebRTC, please let us know.

**Comment by Pato91** [comment]
Thank you so much @ramsestom ... I appreciate the help. Let me try that out and if there are any concerns, I will be sure to consult again. Once again, thanks
