### ISSUE TITLE
ScreenSharing Problems

### ISSUE THREAD

**Issue by un-versed** [andyet/SimpleWebRTC#479]
I'm trying to use the screenshare from SimpleWebRTC demo, but it's not working,, (https://simplewebrtc.com/demo.html) - https required for screensharing to work 

Someone knows how to fix it? I need this quickly for job. I'm getting alright with video and audio, but screenshare i have problems. 
Thanks

**Comment by fippo** [comment]
you need an extension that is published in the chrome webstore. There is none that allows this for simplewebrtc.com.

You might want to take a look at https://github.com/otalk/getScreenMedia/tree/master/chrome-extension-sample

**Comment by BL4CKC1PH3R** [comment]
@fippo Where i need to run this? `google-chrome --load-and-launch-app=/path/to/this/directory`

**Comment by tgabi333** [comment]
In your desktop command line

**Comment by borhanreo** [comment]
@fippo 
At first you have to do that
1: download https://github.com/otalk/getScreenMedia/tree/master/chrome-extension-sample
2: open file manifest.json and change with bold
{
  **"name": "Your Extention Name",**
  **"description": "Description",**
  "version": "0.0.1",
  "manifest_version": 2,
  "minimum_chrome_version": "34",
  "icons": {
  },
  "permissions": [
    "desktopCapture"
  ],
  "background": {
    "scripts": ["background.js"]
  },
  "content_scripts": [ {
    "js": [ "content.js" ],
    **"matches": [ "https://192.168.2.116/*" ]**
  }],
  "externally_connectable": {
      "matches": [
          **"https://192.168.2.116/*"**
      ]
  }
}
4: and Save it then goto your chrome browser
5: write this "chrome://settings/" text in chrome address box
6: click extension
7: tick Developer mode
8:load unpacked extension
9: locate your  chrome-extension-sample folder location

**Comment by fippo** [comment]
@BL4CKC1PH3R ^^
