### ISSUE TITLE
Black box after ends video call

### ISSUE THREAD

**Issue by amalinaaziz93** [andyet/SimpleWebRTC#481]
Once the user ends the video call, the local video turns to black box. The black box cannot be removed or hidden.  I am using webrtc.stopLocalVideo() and webrtc.leaveRoom(). This only happens in iOS devices and not in browser and android.

How to remove the black box or prevent it from appearing?

**Comment by tgabi333** [comment]
Which app do you use in iOS?

**Comment by amalinaaziz93** [comment]
I am using Apache cordova with cordova-plugin-iosrtc

**Comment by amalinaaziz93** [comment]
I finally solved the issue. I set the codes to refresh the video and it works. Thank you!
