### ISSUE TITLE
No video on firefox

### ISSUE THREAD

**Issue by itrae8** [andyet/SimpleWebRTC#484]
Hi there ! i'm currently working on a project which is supposed to work on chrome and firefox. I have no issue making a call only on chrome or firefox. When i try to call from chrome to firefox or the reverse case I only get the audio and the chrome video.  Do you have an idea how i could fix that please ? 
thank you for your answers ;)

**Comment by grsh** [comment]
Hello !
@itrae8  I think you are opening Both browser in same Computer.
Which is causing the problem, because of the Camera device is accessed by one browser so another browser is not able to access it .  try calling from 2 different Computer/system and use different browser I am sure it will work

**Comment by itrae8** [comment]
Thank you very much, I'll test it out but this is surely the case. When i tried talky.io from firefox i indeed got the video from it. You saved my day @grsh thank you.
