### ISSUE TITLE
signalmaster for TURN and STUN

### ISSUE THREAD

**Issue by rugk** [andyet/SimpleWebRTC#485]
You can already use [signalmaster](https://simplewebrtc.com/notsosimple.html#sandbox-server) for the signalling server, which is great as this is the [weak link in the chain](https://security.stackexchange.com/questions/94284/how-secure-is-firefox-hello/105716#answer-105716) in WebRTC.
However it would be nice, if you could also use your own STUN and TURN server.

**Comment by fippo** [comment]
you can configure signalmaster to give use your own stun/turn servers [here](https://github.com/andyet/signalmaster/blob/master/config/development.json#L15-L26). What is the issue?

**Comment by rugk** [comment]
Ah, all right, so they are automatically be used when signalmaster is used. Thanks for your information.
