### ISSUE TITLE
React-Native

### ISSUE THREAD

**Issue by mobileDevNativeCross** [andyet/SimpleWebRTC#486]
Could I use this lib in React-Native app?
Thank you

**Comment by valentinvichnal** [comment]
There is a good WebRTC lib for ReactNative: https://github.com/oney/react-native-webrtc
Probably it needs some config to connect signalmaster and to a browser client using SimpleWebRTC

**Comment by chuckhacker** [comment]
We're currently trying to shim SimpleWebRTC to run in RN and interface with react-native-webrtc. We have a browser implementation and a native mobile implementation that we'd like to maintain parity with. Will keep you posted.

**Comment by xdumaine** [comment]
Unfortunately I'm not familiar with react native. If anyone is interested in doing this, and runs into specific problems or questions, please re-open this ticket with specific details. Thanks for your interest in the lib!
