### ISSUE TITLE
Issue when updating to new version

### ISSUE THREAD

**Issue by theDude30** [andyet/SimpleWebRTC#497]
Hi,
I recently updated the project to the latest version ( i previously used the one that uses socket.io 0.X).
After updating one side can publish and receive the audio/video, but the other side cannot receive the audio/video stream,I'm getting "ICEConnectionStateFailed" (I've attached the webrtc-internal dump).
(https://github.com/andyet/SimpleWebRTC/files/432298/webrtc_internals_dump.txt)

I tested on the same computer, same chrome browser(different tabs).
I'm using TURN/STUN (based on restund) as in the previous versions(that are still working).

**Comment by fippo** [comment]
the only failure I can see is in the connection labeled 3993-67 and that seems to be after the connection was up and then disconnected for 10 seconds. Might be a browser issue.
