### ISSUE TITLE
Unrecognized video stream problem

### ISSUE THREAD

**Issue by Volkanugr** [andyet/SimpleWebRTC#498]
Hi All ,

last week , i setup basic server in DO(DigitalOcean) everything works good 
but now problems with peer connection occurs ; video stream is lost(Black Screen) 
i try to change stun but it's not working also i try the work with turn server (i read the some documentation peoples are talk turn server is good ) but still not working 

I am confused simplewebrtc website is working but my website is not working 

thanks

**Comment by fippo** [comment]
this (most likely) means your TURN server is not working. Check the credentials used on https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice which will try to tell you whether there is an issue with them.

**Comment by blackcrack** [comment]
blackysgate.net/webrc works ..
but what i see, the video it's wrong turned ,
it means the screen it is flipped (or like i can say..)
(Please confirmation and make a issue plz)

best regards
Blacky

**Comment by fippo** [comment]
@blackcrack use css to adjust rotation as you see fit?

**Comment by Volkanugr** [comment]
`  function WebRTC(opts) {
                var self = this;
                var options = opts || {};
                var config = this.config = {
                    debug: false,
                    // makes the entire PC config overridable
                    peerConnectionConfig: {
                      //  iceServers: [{'urls': 'stun:stun.l.google.com:19302'}]
                        iceServers: [
                            {
                                'url': 'stun:stun.l.google.com:19302'
                            },
                            {
                                'url': 'turn:46.101.246.24:3478',
                                'credential': 'blubox11',
                                'username': 'voxporta'
                            },

                            ]

                    },
                    peerConnectionConstraints: {
                        optional: []`

my ice server configratiıon like this code but while i was sniffing the eth0 no packets sent turn server

**Comment by Volkanugr** [comment]
hey guys , i have a good news for this issue

**This is turn server problem** we are trying about 2 weeks but no one can pass NAT

other turn servers not working well we are success with coturn

Thanks
