### ISSUE TITLE
problem of sending message between peers

### ISSUE THREAD

**Issue by zhao-zilong** [andyet/SimpleWebRTC#502]
Hi All!
without broadcast, which function i can use to send a message from a peer to another?

thanks in advance

**Comment by zhao-zilong** [comment]
just need to read the code, sorry to bother. peer.send(message,payload)

**Comment by xdumaine** [comment]
@zhao-zilong You can also use `peer.sendDirectly` to send your message via the datachannel.

**Comment by zhao-zilong** [comment]
@xdumaine   thank you, but in a simplewebrtc application, how can i get a datachannel? is there a function like peer.getchannel()?
