### ISSUE TITLE
Simplewebrtc v2.2.1 : Chrome 54 and stream.onendet

### ISSUE THREAD

**Issue by StudioInteractive** [andyet/SimpleWebRTC#506]
Used Lib: Simplewebrtc v2.2.1

Problem:
The method stream.onended never called in Chrome. So the localScreens Array still have streams from previus screensharings. 
Tested on FF 49 and it works as expected.

LocalMedia.prototype.startScreenShare = function (cb) {
    var self = this;
    getScreenMedia(function (err, stream) {
        if (!err) {
            self.localScreens.push(stream);

            // TODO: might need to migrate to the video tracks onended
            // Firefox does not support .onended but it does not support
            // screensharing either
            stream.onended = function () {
                var idx = self.localScreens.indexOf(stream);
                if (idx > -1) {
                    self.localScreens.splice(idx, 1);
                }
                self.emit('localScreenStopped', stream);
            };
            self.emit('localScreen', stream);
        }

        // enable the callback
        if (cb) {
            return cb(err, stream);
        }
    });
}

**Comment by janwendt** [comment]
#487 I have the same issue with Chrome M54. With M53 it is no Problem.

**Comment by tgabi333** [comment]
Fixed with 2.2.2 release
