### ISSUE TITLE
Questions about Vanilla WebRTC

### ISSUE THREAD

**Issue by cyclingLinguist** [andyet/SimpleWebRTC#513]
Hey guys, I'm sorry if this is the wrong place to put this question but I'm not sure where else I can ask it.

I'm trying to build my own basic video and audio webRTC powered chat. So far I've been able to get it to work over the same network but not over the internet. I've used your demos however and they do work. I was wondering if anyone would mind explaining what your library does over and beyond what vanilla webRTC does. Also I'd be thrilled to find someone who'd be willing to analyze my method of doing things and tell me what I'm doing wrong. 

Here's my code: http://pastebin.com/JWZVQjzM

**Comment by fippo** [comment]
the examples on https://simplewebrtc.com use a TURN server in addition to a STUN server. See https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/ for a good tutorial
