### ISSUE TITLE
Better than webRTC.io or different ?

### ISSUE THREAD

**Issue by hilde2** [andyet/SimpleWebRTC#517]
Hi , I'm trying to use a UDP like communication for client/server game, si I thought using Web rtc will be good.
WebRTC.io  lib seems appropriate but not updated
And I can't find an example for how to use this lib like this case ?

Does this lib support UDP like connection with data channels ? Is this a good idea ?

**Comment by tgabi333** [comment]
Generally yes, it could work using DataChannels for a game. But in this case you don't need SimpleWebRTC, this repo is a good starting point if you wish to create audio/video transmissions. 

You should use libraries such as [adapter](https://github.com/webrtc/adapter) shimming browser differences and (socket.io)[https://github.com/socketio/socket.io/] or any other realtime communication libraries to transfer SDPs and build up your custom logic for connections.

**Comment by hilde2** [comment]
I will look directly at webrtc/adapter, thanks for the help !
