### ISSUE TITLE
How to enable Dual Track Audio

### ISSUE THREAD

**Issue by km147** [andyet/SimpleWebRTC#518]
What is the best prctice to enable dual track audio as currently we can only pass mono. I understand within the SDP it simply requires that the tracks are specified as two, this example I have extracted from a change we made to your code a year ago but I can see there has been a complete re-write:

rtpmap = "a=rtpmap:111 opus/48000/2";
sdp.push(rtpmap);

Could we force dual track to get stereo [2] regardless of the detected bandwidth but I am keen to know best practice.

Since we can only get mono, is it the case that getAudioTracks() supports dual track and we are not interfacing correctly?

We are working on this from Jan 9th, if anyone else is interested in this pls let me know and we can share ideas! Any help in pointing us in the right direction is greatly appreciated!

PS. Thanks so much to Henrik for this contribution and ongoing support!

**Comment by fippo** [comment]
the "2" in the channels is the default in opus. If you want stereo, you need to add stereo=1 to the a=fmtp linie that belongs to the opus codec before calling setLocalDescription.

That being said, this kind of sdp munging is not supported by simplewebrtc so you're on your own.

**Comment by km147** [comment]
:) Ah, mmmm now things are making a lot more sense! So to access the list of codecs and change the order in which they are loaded (which is related) you have previously stated you need to change this in signal master where m= Would you be a diamond and indicate the file name or I'll need another day to hedge closer :) Thanks.

**Comment by km147** [comment]
Found two interesting documents to get us on our way!
https://datatracker.ietf.org/doc/draft-ietf-mmusic-sctp-sdp/
https://www.ietf.org/proceedings/89/slides/slides-89-mmusic-11.pdf
