### ISSUE TITLE
Signaling/TURN/STUN Servers: Video Does Not Connect Successfully From Certain Locations

### ISSUE THREAD

**Issue by vinodmap** [andyet/SimpleWebRTC#521]
Hello, I'm trying to get simplewebrtc working in different locations.  There are some locations that the video does not work from (one example is by using the public WiFi at Starbucks, the video does not work, but the text chat does work).  I've essentially used the snippets from the main site (https://simplewebrtc.com/).  The constructor I'm using is from there:
var webrtc = new SimpleWebRTC({
  localVideoEl: 'localVideo',
  remoteVideosEl: 'remotesVideos',
  autoRequestMedia: true
});

However, I did see the comment in the Signaling server section on that page stating this uses "the sandbox server and is only for development and testing purposes. This server does not provide media relay facilities so there might be connectivity issues."  

I have two questions:

1) using the sandbox server, in certain locations, the text chat (using e.g., sendToAll('chat', {message: 'hello', nick: 'user1')});) does work but the video does not work.  I'm trying to determine whether this is because of a signaling/STUN/TURN server issue or if it is something else.  If it is, why would the text chat work, but not the video?

2) Is the signaling server different from the STUN/TURN servers?  On the web page, there are two separate sections (first is Signaling server and the second is STUN and TURN server) for these.  I have setup an AWS server with a public AMI image (see http://turnserver.open-sys.org/downloads/v4.5.0.5/turnserver-4.5.0.5-amazon-aws-ec2-x86_64.txt, image ami-b7b613d7).  I believe this image includes both the turn and stun functionality, but does it also include the signaling server functionality, or is that separate?

I'm trying to diagnose this problem and help with parsing out these issues would help a great deal.  Thank you, and happy new year!

V

**Comment by fippo** [comment]
1. textchat using *sendToAll* is done via the signaling channel so it works when both clients are connected to the signaling server.

2. see https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/ for a pretty good explanation about signaling servers and stun/turn servers. They are separate.

See http://testrtc.com/webrtc-api-trace/ for an explanation of how to verify that your stun/turn server works and is used (this will not work with the sandbox signaling server)

**Comment by vinodmap** [comment]
Thank you fippo for the quick response.  I will review these links and will follow-up if I still have questions.  Thanks.

**Comment by vinodmap** [comment]
Thanks, I read through the tutorial/links you sent; they provided a good background/base.  So, what I understand from your comment, the text chat works because the text messaging is being sent/relayed through the signaling channel which both are connected to (and the communication is not peer to peer).  But, the video/audio is peer to peer direct between the two clients, where the public IP addresses/ports are determined by the STUN server, and if this is not successful, then the audio/video is relayed through the TURN server.  Please correct me if this is not accurate.   If so, I now understand why the text chat works.   Now, a follow-up on why the audio-video did not connect.   Below, I have two snippets of the Wiresharks output that I captured at home (everything connects great) and then at Starbucks (audio/video does not work, but text chat does).

Here is at Home:
![wireshark-home_network-works](https://cloud.githubusercontent.com/assets/24858762/21583764/9322df14-d043-11e6-9e37-1b36ac005c12.JPG)


Here is at Starbucks:
![wireshark-starbucks-does_not_connect](https://cloud.githubusercontent.com/assets/24858762/21583766/ab2e4300-d043-11e6-8f5a-ce7054578e47.JPG)

From these packets, and the tutorial, I see the STUN packets being exchanged and I see that Google provides a public STUN server at stun.l.google.com:19302 (which in the Wireshark is at IP addr 173.194.xxx.xxx in both images).  **Question 1**: **(a)** Does Google also provide a public turn server if the stun is not successful?  **(b)** Is this the reason it is not working, because it is only applying the STUN aspect here, and when the STUN fails, there is no TURN server?   **(c)** why does the Starbucks WireShark give a Binding Success Response XOR-MAPPED-ADDRESS of 74.87.39.204:52617 if there is later an ICMP packet that says Destination unreachable (is it because on the attempt to use that address, it was unsuccessful) ?  

**Question 2**: Can the signaling server that I setup run on the same machine as the TURN/STUN server?  In other words, can I run the signaling server (signalmaster from https://github.com/andyet/signalmaster) on the same AWS EC2 instance that is running my TURN/STUN server (AWS VM/AMI image b7b613d7)?

Thanks again.

**Comment by vinodmap** [comment]
Hello Philipp, happy new year, thank you for your response.  If you are able to respond on my follow-up post, that would be really really helpful to clearing things up.  Essentially, my questions in the post are:    
   - is the reason that the audio/video fails because google only provides a public stun server (which I believe fails as below), and not a turn server (stun.l.google.com:19302)?  Note, you can see in the second Wireshark below which seems to show that the stun process fails (there is a Binding Success Response xor-mapped-address, but then it later says ICMP packet destination unreachable, not sure why there is a success response, but then unreachable)
   - I am setting up an AWS EC2 instance running a turn/stun server (AWS VM/AMI image b7b613d7).  Can the signaling server (signalmaster from https://github.com/andyet/signalmaster) be run on the same machine as where the turn/stun server is running or does it need to be on separate machines?   


Wireshark at Home (works):
Wireshark at Starbucks (fails):

**Comment by fippo** [comment]
1) note that the stun packets have different usernames. The first one is a request for the public ip from the stun server and does not have any username. The other requests have a username and are used by ICE to probe the P2P connection.
The latter does not work in the starbucks case.

2) it is possible but you won't be able to run both signalmaster and the turn server on the same port (443). But you really want turn servers to be distributed all over the world later.

**Comment by vinodmap** [comment]
Thanks. 

1. would the next step be since the stun does not work, to go to a turn server?  But since Google does not have a public turn server, it just fails altogether?

2. got it (eventually would want many distributed turn servers).  For now, would I be able to configure one of them (either signalmaster or turn) to run on a port other than 443 ?

**Comment by fippo** [comment]
1) yes, the browser would gather candidates from the TURN server and connect that way.
2) yes.

**Comment by vinodmap** [comment]
Great, thanks so much.  I am working on setting up the signaling + turn/stun servers.
