### ISSUE TITLE
Add "Answer to call"

### ISSUE THREAD

**Issue by Denschik** [andyet/SimpleWebRTC#523]
Hello everybody!
I would like to add the ability to answer calls like in Skype([screenshot](http://content.gcflearnfree.org/topics/189/vid_incoming_popup_update.jpg)) or as in this [example](https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/). But I recently started to learn webrtc and simplewebrtc, and I have a problem with added ability to answer calls.
I think, need controlling moment between send offer and create answer in rtcpeerconnection. But I do not know how to make it through SimpleWebrtc.

P.S. Sorry, if my english so bad.

**Comment by fippo** [comment]
one of the design concepts of this library is that many participants join the same room. All calls in that room are automatically answered.

If you want to implement explicitly accepting, you can implement that by joining the room only after both parties agreed to have a conversation.

The alternative is to only use the peer object but that is slightly more complicated. Basically you call createPeer later than its done [here](https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.js#L94)
