### ISSUE TITLE
Safari giving error, how to fix it?

### ISSUE THREAD

**Issue by shamun** [andyet/SimpleWebRTC#527]
While using https://cdn.temasys.com.sg/adapterjs/0.13.x/adapter.debug.js, i am getting following error:

```
TypeError: audioContext.createMediaStreamSource is not a function. (In 'audioContext.createMediaStreamSource(stream)', 'audioContext.createMediaStreamSource' is undefined)
```

**Comment by fippo** [comment]
file a bug on the temasys plugin.

**Comment by shamun** [comment]
OK - reported: https://github.com/Temasys/AdapterJS/issues/250 , please do a follow up, i am planning to make the Safari, IE compatible with with Temasys for SimpleWebRTC, so that community have stable answer to follow up.

For the record Safari Temasys plugin is working  when i use https://plugin.temasys.com.sg/demo/src/content/getusermedia/gum/, but AppRTC and SimpleWebRTC is not working)
