### ISSUE TITLE
leaveRoom not calling Peer.end() on all webrtc peer elements

### ISSUE THREAD

**Issue by handsfelloff** [andyet/SimpleWebRTC#530]
LeaveRoom contains a bug where the Peer cleanup iterator slices the array `this.webrtc.peers.shift().end();` that following the slice calls `Peer.end()` within which `Peer.prototype.handleStreamRemoved` method modifies the peers array `this.parent.peers.splice(this.parent.peers.indexOf(this), 1);` resulting in a double element removal thus skipping connection closing code (causing Peer heap leak I have reported)
Within `LeaveRoom` rather than slicing the iterator just call `Peer.end` which takes care of the removal `this.webrtc.peers[0].end();`

I submit the following suggested fix to leaveRoom:
```
SimpleWebRTC.prototype.leaveRoom = function () {
    if (this.roomName) {
        this.connection.emit('leave');
        while (this.webrtc.peers.length) {
            this.webrtc.peers[0].end();
        }
        if (this.getLocalScreen()) {
            this.stopScreenShare();
        }
        this.emit('leftRoom', this.roomName);
        this.roomName = undefined;
    }
};
```

**Comment by tgabi333** [comment]
This was fixed with this commit: https://github.com/andyet/SimpleWebRTC/commit/ba387a9cdd554f24023ee2ab632da759db5d7254
