### ISSUE TITLE
Screensharing: localScreenStopped event not fired on FF 50 

### ISSUE THREAD

**Issue by greg-man** [andyet/SimpleWebRTC#531]
Title says it all... 

I think this issue is caused by the latest commit (update localmedia dependency to work with chrome 54+), as it now works on chrome. 

Could fix it by adding:

```
var idx = this.webrtc.localScreens.indexOf(stream);
if (idx > -1) {
    if (webrtcSupport.prefix === 'moz') {
        this.emit('localScreenStopped', stream);
    }
    this.webrtc.localScreens.splice(idx, 1);
}
```

after https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.bundle.js#L18304

but I think, this should be investigated further by someone who has a deeper knowledge of the underlying procedure.

Regards
Greg  

EDIT: maybe the last commit wasn't finished yet as there is a [comment](https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.bundle.js#L18311) saying that this.webrtc.localScreen should be deleted but the necessary code is missing.

**Comment by tgabi333** [comment]
The workaround for firefox is implemented here: https://github.com/otalk/localmedia/commit/f6b1808fe18b48bf2426aab2d4117c315ffb4724

**Comment by tgabi333** [comment]
See: https://github.com/andyet/SimpleWebRTC/pull/541

**Comment by tgabi333** [comment]
2.2.3 released :)

**Comment by greg-man** [comment]
Many thanks tgabi!!!

**Comment by greg-man** [comment]
Issue came up again using latest simplewebrtc bundle and Firefox 55. 

Seems that shouldWorkAroundFirefoxStopStream() function should apply here as well or am I missing something?
