### ISSUE TITLE
Screensharing: button disabled due to incorrect webrtc.capabilities check in Firefox

### ISSUE THREAD

**Issue by mjprins** [andyet/SimpleWebRTC#535]
On my Firefox (50.1.0) the demo page (https://simplewebrtc.com/demo.html) does not enable the "share screen" button.

It is set on disabled due to the following check:
` if (!webrtc.capabilities.screenSharing) {
                button.disabled = 'disabled';
  }`

_webrtc.capabilities.screenSharing_ does not exist, but _webrtc.capabilities.supportScreenSharing_ does. If I enable the button by removing the disabled property of the button, I can use the screen sharing capabilites.

Note, this might require adding "simplewebrtc.com" to "media.getusermedia.screensharing.allowed_domains" and setting "media.getusermedia.screensharing.enabled "  in about:config

**Comment by fippo** [comment]
Thanks, PR for fixing that is up. Note that Firefox is going to remove the whitelisting requirement soon (I think FF52 or FF53)
