### ISSUE TITLE
Deprecation error: RTCIceServer url deprecated use 'urls'

### ISSUE THREAD

**Issue by ImmanuelSamuel** [andyet/SimpleWebRTC#536]
Deprecation error.

**Comment by fippo** [comment]
Deprecation warning. Where are you getting this, all instances I know of have long since been removed.

**Comment by ImmanuelSamuel** [comment]
html:
var webrtc = new SimpleWebRTC({// we don't do video
    localVideoEl: '',
    remoteVideosEl: '',
    // dont ask for camera access
    autoRequestMedia: false,
    // dont negotiate media
    receiveMedia: {
        offerToReceiveAudio: 0,
        offerToReceiveVideo: 0
    }
  });

  webrtc.joinRoom('ptlj');

  webrtc.on('data', function (datatemp) {
    // you can name it anything
    alert(1);
  });

  setInterval(()=>{
    webrtc.sendToAll('data', 1);
  },1000);

var webrtc = new SimpleWebRTC({// we don't do video
    localVideoEl: '',
    remoteVideosEl: '',
    // dont ask for camera access
    autoRequestMedia: false,
    // dont negotiate media
    receiveMedia: {
        offerToReceiveAudio: 0,
        offerToReceiveVideo: 0
    }
  });

//////////////////ERROR in this Line if I take it out its fine ////////////////////
  webrtc.joinRoom('ptlj');

  webrtc.on('data', function (datatemp) {
    // you can name it anything
    alert(1);
  });

  setInterval(()=>{
    webrtc.sendToAll('data', 1);
  },1000);

**Comment by fippo** [comment]
@nlf can you take a look if the sandbox server uses an outdated config?

@ImmanuelSamuel please run your own copy of https://github.com/andyet/signalmaster -- this should make the issue go away.

**Comment by ImmanuelSamuel** [comment]
Ok thank you.

**Comment by fippo** [comment]
i updated the sandbox server so this should be fixed.
