### ISSUE TITLE
how to share entire screen Screen share mozilla

### ISSUE THREAD

**Issue by vishnudasgs** [andyet/SimpleWebRTC#545]
In mozilla when i start to share the screen, i did't find the option to select the **entire screen** to share in   "window to share" popup

**Comment by fippo** [comment]
Firefox currently allows you to pick either the screen or a window. You'll basically need to change
https://github.com/otalk/getScreenMedia/blob/master/getscreenmedia.js#L106
to 'screen'.

startScreenShare doesn't allow passing down those options to the localmedia and getscreenmedia packages currently. Patches welcome!

**Comment by vishnudasgs** [comment]
Thank you very much.. fippo
