### ISSUE TITLE
Unable to reconnect after disconnect is called

### ISSUE THREAD

**Issue by newelement** [andyet/SimpleWebRTC#549]
I'm trying to toggle between audio and video peers. When I call webrtc.disconnect() then reconnect using webrtc = new SimpleWebRTC( opts ), it seems the socket server no longer connects.

**Comment by fippo** [comment]
Have you tried this?
https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.js#L13

Might have changed in socket.io 1.x to { forceNew: true }

**Comment by newelement** [comment]
I totally missed being able to pass socketio config. That works. Thanks!
