### ISSUE TITLE
Running my own signaling server

### ISSUE THREAD

**Issue by IJGXD** [andyet/SimpleWebRTC#55]
Hi,

I know your provided signaling server is for testing purpeses only and that is why I want to create my own server. 

Is that the NodeJS server software I need to run?
https://github.com/andyet/signalmaster/blob/master/server.js
If so, what is the 'config' object presented in it and how (e.g. where) can I change it (in order to modify the port)?

Thanks a lot,
Iddo

**Comment by weirdalsuperfan** [comment]
My signal server can't find the dev_config file that's located in its folder (getting a no config files found error)...I put the signalmaster code here: root/test/test1/signalmaster-master
and I'm trying to test a simplewebrtc page located in root/test/test1/ (sourcing the code latest/js from git) 
I tried installing getconfig and then I created a blank file called default.json and put it in root/config/ (the same level as node_modules). Can you tell me how to get my signal server running properly? Thanks.

**Comment by tomerefrati** [comment]
Had some problems, solved it with sudo (You need root privileges in order to use port 443).
sudo node server.js
