### ISSUE TITLE
mozilla screen share capabilities check error

### ISSUE THREAD

**Issue by vishnudasgs** [andyet/SimpleWebRTC#552]
Hi,
  My screen sharing in Mozilla is working correctly but the issue is on screen share capabilities check.
capability check not detecting screen share plugin installed or not i use the following for the check

webrtc.capabilities.supportScreenSharing // always getting true either plugin installed or not

webrtc.capabilities.screenSharing// always getting  false either plugin installed or not.

**Comment by fippo** [comment]
There is no simple way to detect this capability as long as Firefox uses a whitelist.
The whitelist and the need for a plugin will be gone in Firefox 52 though.
