### ISSUE TITLE
Audio Streaming Still Happens even if the Mic is Muted and Relayed When Mic is unmuted!

### ISSUE THREAD

**Issue by PATRONANALYSIS** [andyet/SimpleWebRTC#560]
The case is that if Mic is muted on a machine, then voice doesn't go through to the other peers in group connection however when mic is later turned on, then what all the peer said while his/her mic was muted starts getting relayed to the other peers in the group connection. Thus, the voice is still recorded somewhere if your mic is muted and whenever in that connection, you would unmute your mic then all what you said (while your mic was muted) will be relayed to the other peers. Please help how we can fix this issue.

**Comment by xdumaine** [comment]
I'm very skeptical of this one. This lib (nor any of it's dependencies) does not do any recording. How are you seeing/measuring this? By viewing packets/traffic, or are you actually hearing the audio? Can you set up a demo page that shows the issue?

**Comment by PATRONANALYSIS** [comment]
Hi Xander, we actually heard this audio. Let me detail you the case further. You are absolutely correct that there is no recording capability as set in the library or any of its dependencies. However, this case emerged for us, as we were testing with one Peer logged on through Mozilla Firefox on Ubuntu System (Ubuntu 12) and another on a Google Chrome Browser on Windows 7 Operating System. In that case, this scenario occurred so there is something pertaining to Ubuntu Operating System which might have led to this issue. The demo which we used to test is: https://simplewebrtc.com/audio.html?under-a-rough-snow

On Windows to Windows, there were no such issues encountered at our end and everything worked absolutely fine. Thus thought of getting some valuable input on this.

**Comment by xdumaine** [comment]
That might be good to create a Chrome bug. I'd also check with appr.tc or appear.in to see if the issue occurs there.

**Comment by fippo** [comment]
getting a chrome://webrtc-internals log would be helpful as well. See http://testrtc.com/webrtc-internals-parameters/ for a description.

**Comment by PATRONANALYSIS** [comment]
@xdumaine, we checked https://appr.tc and https://appear.in and this specific issue occurs in that case as well. Nevertheless considering it to be a Browser Specific issue, we are ignoring the same as of now. 

@fippo, thanks for sharing the internal parameters details. We are studying the same and will definitely get back in case if there be any help required.
