### ISSUE TITLE
Error: NavigatorUserMediaError     at latest-v2.js:2 WebRTC Screen Share on Chrome 

### ISSUE THREAD

**Issue by mrjainvimal** [andyet/SimpleWebRTC#562]
Hello,

I tried to implement video & audio chat using simplewebrtc library, I works awesome. But when trying diving deep & going for screen share I got error & bugs, the first bug I found out is  as per the documentation it is ` webrtc.capabilities.screenSharing` but when I searched on google it come up with this `webrtc.capabilities.supportScreenSharing`.

When I start debugging the code I got this error Error: NavigatorUserMediaError at latest-v2.js:2 WebRTC .

Just for additional information, I had a chrome extension for this,  i deployed it on server with ssl, I guess no issue of insecure origin.

I will really appreciate if any one can guide to have a successful demo of screen sharing using simplewebrtc library.

**Comment by tgabi333** [comment]
@mrjainvimal try to find this section of code and try debug it:

https://github.com/otalk/getScreenMedia/blob/master/getscreenmedia.js#L28

**Comment by mrjainvimal** [comment]
When I start debugging the code I got this error Error: NavigatorUserMediaError at latest-v2.js:2 WebRTC .

webrtc.shareScreen(function (err) {
if (err) {
console.log(err);
setButton(true);
} else {
setButton(false);
}
});
