### ISSUE TITLE
Compatibility issue with Firefox 52.0.1

### ISSUE THREAD

**Issue by arcifius** [andyet/SimpleWebRTC#564]
Can't establish a connection in Firefox... When it tries to join a room or somebody enters a room created by it the following line crashes:
`this.peerconnection = new window.RTCPeerConnection(config, constraints);`
All I got from console is a "NS_ERROR_UNEXPECTED: "
Hope somebody can help me figure out what is happening...

PS: Chrome to Chrome works fine...

**Comment by fippo** [comment]
https://simplewebrtc.com/video -- can you reproduce there? Works fine for me.

**Comment by arcifius** [comment]
First of all, thanks for the quick reply. In fact the demo above works fine on both, going to run more tests on my project, I'm using audio only (just to keep it simple), the code of this demo is hosted here on github? It would be nice to analyse it... I'll post my advance here as soon as possible

**Comment by fippo** [comment]
its over [here](https://github.com/andyet/SimpleWebRTC/blob/gh-pages/video.html) on the gh-pages branch

**Comment by kaneua** [comment]
I'm here with the same issue. NS_ERROR_UNEXPETED.

**Comment by fippo** [comment]
how do the config and constraints arguments look like?

**Comment by kaneua** [comment]
They look like just an example on SimpleWebRTC website.

```vl_.webrtc = new SimpleWebRTC({
        localVideoEl: 'vl_uservideo',
        remoteVideosEl: 'vl_camvideo',
        autoRequestMedia: true
});```

**Comment by fippo** [comment]
no, the ones passed down to RTCPeerConnection in the line you've shown in the first post

**Comment by fippo** [comment]
are you using turns by chance? See https://bugzilla.mozilla.org/show_bug.cgi?id=1056934#c61

**Comment by arcifius** [comment]
Yes, i'm only using TURN server (STUN don't solve my problem)... I've changed my confs and can't figure out why it is not even creating a room... It keeps requesting _https://mysignalmasterip:9000/socket.io/_ but on Chrome everything works fine... I'm initializing the object this way:

```
this.webrtc = new SimpleWebRTC({
                localVideoEl: 'localVideo',
                remoteVideosEl: '',
                autoRequestMedia: false,
                url: 'https://174.138.92.135:9000',
                media: { audio: true, video: false },
                iceTransportPolicy: 'relay',
                peerConnectionConfig: { 'iceServers': [turn] }
            });
```

**Comment by arcifius** [comment]
Okay, i'm using only TURN servers because STUN don't solve my goal... How can i log the config on this line?
`this.peerconnection = new window.RTCPeerConnection(config, constraints);`
If I got it right, seems firefox don't have support for TURN, isnt it? ;S

**Comment by fippo** [comment]
Firefox does support TURN, it has not (so far) supported TURN/TLS but that was added in FF53 afaik
Easiest way is to set a breakpoint on that line and do a console.log(config, constraints)

**Comment by arcifius** [comment]
I'm just poking around trying to find a solution maybe something could be done here...

```
if (detectedBrowser === 'firefox') {
        if (constraints && constraints.optional) {
            this.wtFirefox = 0;
            constraints.optional.forEach(function (constraint) {
                if (constraint.andyetFirefoxMakesMeSad) {
                    self.wtFirefox = constraint.andyetFirefoxMakesMeSad;
                    if (self.wtFirefox > 0) {
                        self.firefoxcandidatebuffer = [];
                    }
                }
            });
        }
    }

    this.pc = new Peerconn(config, constraints); (this one ends up on the previous line error)
```

**Comment by arcifius** [comment]
Going to update my firefox from 52.0.2 to 53 and test it again as soon as possible, i'll keep u posted

**Comment by fippo** [comment]
where do you get the error? The turn thing should only land in FF53 and you initially reported an issue with FF52

Without a reproduction its hard to fix the actual issue.

**Comment by arcifius** [comment]
Well, i'm not a master jedi of code but hope you can understand what i'm doing here:
https://github.com/arcifius/simplewebrtc-client

**Comment by fippo** [comment]
this does not work (neither in Chrome nor in Firefox):
```
var pc = new RTCPeerConnection({iceServers: [{'url': 'turn:someturn@0.0.0.0', 'username': '', 'credential': ''}]});
```
First, use "urls" instead of "url" (Firefox kindly asks you)
Second: "someturn" belongs into the username.
Third, 0.0.0.0 likely invalid as a hostname. 
Fourth, an empty credential is unlikely to work

**Comment by arcifius** [comment]
First of all thanks so much for the attention and support... Second I've changed this:

```javascript
var pc = new RTCPeerConnection({iceServers: [
    {'url': 'turn:someturn@0.0.0.0', 'username': '', 'credential': ''}
]});
```
Because I didn't wanted to show everyone my TURN (I'm paying for it at digital ocean)... Just replace the wrong information with informations of a TURN you have access...

I'll remove the username from the url and change to url to urls as you mentioned above... Just can't do it right now but I'll keep you posted

**Comment by fippo** [comment]
@taylor-b do you have an issue somewhere for making chrome reject the old turn:user@host thing? This was required in 2012, accepting it in 2017 seems... not good.

**Comment by fippo** [comment]
@arcifius if you use static passwords you should be aware that everyone can grab them from JS and use them. That is why signalmaster supports created ones based on shared secrets. See also the "webrtc usage" section on https://github.com/coturn/coturn/wiki/turnserver

Closing this, configuration issue.
