### ISSUE TITLE
audio chat demo  explanation needed

### ISSUE THREAD

**Issue by infantilo** [andyet/SimpleWebRTC#565]
hi,
i'm stuck with the the audio chat demo:
I can connect and see the nicknames and screenshots, BUT no audio at all!

I'll need to stream the output of an web audio stream (context.createDynamicsCompressor) to another browser, receive it there and connect the received stream to the my audio chain (e.g. context.createGain()) AND vice versa.

PLZ, could someone give me an hint, how to get this working?
MANY thanks for advice!

**Comment by xdumaine** [comment]
@infantilo are you able to run the example page and get audio? maybe post your code or a link to a sample, or chrome://webrtc-internals dump.

**Comment by infantilo** [comment]
Many THX for reply!!
This is the webrtc dump:
[webrtc_internals_dump.txt](https://github.com/andyet/SimpleWebRTC/files/893928/webrtc_internals_dump.txt)

**Comment by fippo** [comment]
if you import the log on http://fippo.github.io/webrtc-dump-importer/ you can see that the ice connection between both clients fails (and there is no working relay server).
My guess is that one of the clients is on a restricted network and requires a turn server. And you don't get those for free.

**Comment by infantilo** [comment]
oh..i see... the dump importer is great...didn't know about it, sorry.
so, i'll need to set up an turn sever...
once more, THX for helping me!
