### ISSUE TITLE
screen sharing not working in chrome 57

### ISSUE THREAD

**Issue by theDude30** [andyet/SimpleWebRTC#566]
Hi,
it looks like "chrome.runtime.sendMessage" is not available anymore.
do you have any idea how to communicate between webpage and the extension without chrome.runtime ?

**Comment by fippo** [comment]
I don't see any intent to deprecate chrome.runtime.sendMessage on https://developer.chrome.com/extensions/messaging

**Comment by theDude30** [comment]
never mind, please ignore.
