### ISSUE TITLE
Check if Camera and Microphone are available

### ISSUE THREAD

**Issue by VeeK727** [andyet/SimpleWebRTC#567]
I'm using the standard snippets available on the Readme page and I've gone through the notsosimple.html tutorials as well but didn't find any way of checking if the computer has the camera and microphone at all.

My users are likely to be on old desktops without any inbuilt camera and/or microphone. I was wondering if it would be possible to detect that and display a message to inform the user. Currently it just sits there blank.

You can also check the demo page which does the same thing.

**Comment by fippo** [comment]
see https://webrtc.github.io/samples/src/content/devices/input-output/ for an example how to use the enumerateDevices API

**Comment by fippo** [comment]
alternaively https://simplewebrtc.com/notsosimple.html#device-selection
