### ISSUE TITLE
ERR_INSECURE_RESPONSE on demo page and my app

### ISSUE THREAD

**Issue by ldenoue** [andyet/SimpleWebRTC#570]
The demo is broken for me: https://simplewebrtc.com/demo.html I get 

GET https://sandbox.simplewebrtc.com/socket.io/?EIO=3&transport=polling&t=1493574062719-1 net::ERR_INSECURE_RESPONSE

Laurent

**Comment by fippo** [comment]
@nlf can you take a look and replace the cert? its a startcom cert which is probably no longer trusted by chrome :-/

**Comment by sonlexqt** [comment]
+1 same thing here

**Comment by vinodmap** [comment]
I'm getting the same error as well.  I was able to temporarily fix this by going to https://sandbox.simplewebrtc.com/socket.io/?EIO=3&transport=polling&t=1493574062719-1 in Chrome and clicking on proceed.  But, will I have to do this on every machine I am accessing this from?

**Comment by fippo** [comment]
have you considered running your own version of https://github.com/andyet/signalmaster ? The sandbox server is not for production usage.

**Comment by vinodmap** [comment]
thanks.  I am running my own stun and turn servers, but was having issues getting the signaling server to work recently.  I will have to re-visit that.

**Comment by nlf** [comment]
i've replaced the certificate with one that should be more chrome-friendly, i'm gonna go ahead and close this but do let me know if there are any other certificate related issues
