### ISSUE TITLE
ScreenRecording of Remote stream

### ISSUE THREAD

**Issue by BitRulez** [andyet/SimpleWebRTC#571]
I want to record the remote camera stream within MediaRecorder object.

I try to create the MediaRecorder object with the stream variable that i get there: 

```
navigator.mediaDevices.getUserMedia(constraints).
      then(gotStream);

function gotStream(stream) {
    window.stream = stream; // make stream available to console
}
```

this function was called in the videoAdded event, so i suppose that this is the remote stream, but when i start recording (after the assignament of stream) it record my local camera stream and not the remote camera stream.

Is there a way to assign/get the remote stream?

**Comment by fippo** [comment]
if you want to access the remote stream why are you calling getUserMedia (which gets you the local media). This should work:
```
webrtc.on('videoAdded', function (video, peer) {
  // hook up MediaRecorder with peer.stream
});
```

**Comment by BitRulez** [comment]
You're right! it work, thanks!

**Comment by baynojunemark24** [comment]
Hi @BitRulez,

I know it kinda old but may I know that if you managed the recording?

Thanks.
