### ISSUE TITLE
Connection to signaling server "ws://echo.websocket.org/"

### ISSUE THREAD

**Issue by 3wkit** [andyet/SimpleWebRTC#573]
How to make the connection to communicate with the signaling server "ws://echo.websocket.org/"?

**Comment by tgabi333** [comment]
For signaling server you should use exactly a copy of this repo: https://github.com/andyet/signalmaster

**Comment by 3wkit** [comment]
But how can I run the signaling server "ws://echo.websocket.org/" without node.js enviroment?

**Comment by tgabi333** [comment]
SimpleWebRTC offers a peer-to-peer audio/video transfer. If you like to use on your own website you must have these dependencies:

1, nodejs backend for coordinating the peers. This is implemented via signalmaster.
2, TURN servers which enables peers to transmit video through firewalls. (See eg: xirsys service)

SimpleWebRTC sets up a default configuration of a signalmaster instance using for demo purposes. 
(see: https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.js#L12)

**Comment by aviabey** [comment]
you need to deploy the server at https://github.com/andyet/signalmaster on your echo.websocket.org server. If you can't install signalmaster server on your echo.websocket.org server, then try free node deployment services like heroku, but I haven't use heroku for deploying node servers, so I'm not 100% sure heroku will work out for you.
