### ISSUE TITLE
Share Screen without chrome-extensions

### ISSUE THREAD

**Issue by roy2651** [andyet/SimpleWebRTC#576]
hello,I git clone this demo and node server.js
but I click  share screen , it doesn't work .
I find this can use chrome-extensions with https://github.com/otalk/getScreenMedia.git ,then I modify mainfest.json and add this in chrome ,also no work
I find many demos in sharescreen with chrome-extension  such as webrtc-experiments
Does it has demos in Electron or in web without chrome-extensions?
THKS and god bless u

**Comment by stiv-yakovenko** [comment]
Its not possible to share screen with no extension on Chrome.

**Comment by xdumaine** [comment]
Chrome requires extensions. Electron may work with the right config flags but won't have screen picker.
