### ISSUE TITLE
Not usable as an npm package

### ISSUE THREAD

**Issue by nicooga** [andyet/SimpleWebRTC#584]
I've installed the package via npm. When I require the file via absolute path I get this error:

~~~js
import SimpleWebRTC from 'simplewebrtc/out/simplewebrtc.bundle.js';
~~~~
> Processing of node_modules/simplewebrtc/out/simplewebrtc.bundle.js failed. Error: Could not load module '../utils.js' from '/home/nepto/Source/freelance/cognituz/front/node_modules/simplewebrtc/out'. Make sure the file actually exists.

... which makes sense this module is triying to `require` a relative linked file './utils' which is not present. This is what is in the folder of the package (some files ommited):

~~~bash
$ tree node_modules/simplewebrtc
├── out
│   ├── simplewebrtc.bundle.js
│   └── simplewebrtc-with-adapter.bundle.js # this file tries to require './utils'
├── src
│   ├── peer.js
│   ├── simplewebrtc.js
│   ├── socketioconnection.js
│   └── webrtc.js
~~~
I am missing something?

It seems this package was never set up to be consumed by a static site builder tool like brunch, browserify or webpack. Otherwise I'd expect examples on README to tell you to `npm i --save-dev simplewebrtc` and `import`/`require` the package.

I cannot find a workaround for this "issue" other than throwing the towel and using the file hosted at https://simplewebrtc.com/latest-v2.js.

**Comment by tianhaoz95** [comment]
`import SimpleWebRTC from 'simplewebrtc/src/simplewebrtc.js'`

might be a temp solution I think if you don't want production build for just now.

**Comment by fippo** [comment]
the bundle is not for use with npm

**Comment by nicooga** [comment]
Thanks, will be trying again this weekend!
