### ISSUE TITLE
Unable to run application using npm run test-page, showing below error 

### ISSUE THREAD

**Issue by kul1010** [andyet/SimpleWebRTC#586]
I am unable to run application using npm run test-page, showing below error 
===============In Windows 7===============
$ npm run test-page

> simplewebrtc@3.0.0 test-page D:\asergis\eg\SimpleWebRTC
> open https://localhost:8443/test/ && stupid-server -s

'open' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simplewebrtc@3.0.0 test-page: `open https://localhost:8443/test/ && stu           pid-server -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simplewebrtc@3.0.0 test-page script.
npm ERR! This is probably not a problem with npm. There is likely additional log           ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pankaj.k\AppData\Roaming\npm-cache\_logs\2017-06-21T08_53_           51_466Z-debug.log
===================In Ubuntu==============
sudo npm run test-page

> simplewebrtc@3.0.0 test-page /var/www/SimpleWebRTC
> open https://localhost:8443/test/ && stupid-server -s

sh: 1: stupid-server: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! simplewebrtc@3.0.0 test-page: `open https://localhost:8443/test/ && stupid-server -s`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the simplewebrtc@3.0.0 test-page script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pankaj/.npm/_logs/2017-06-21T09_41_34_158Z-debug.log

**Comment by xdumaine** [comment]
@kul1010 I don't have access to a computer for a couple days but could you check out the linked PR? It's just that I added a helper command that isn't available on your system.

**Comment by kul1010** [comment]
right now showing
=============In window Git Bash============
pankaj.k@YEN-PC MINGW64 /d/asergis/eg/SimpleWebRTC (master)
$ npm run test-page

> simplewebrtc@3.0.0 test-page D:\asergis\eg\SimpleWebRTC
> echo "open https://localhost:8443/test/" && stupid-server -s

"open https://localhost:8443/test/"
'stupid-server' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simplewebrtc@3.0.0 test-page: `echo "open https://localhost:8443/test/" && stupid-server -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simplewebrtc@3.0.0 test-page script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
=============In Ubuntu============

also error at ubuntu

**Comment by fippo** [comment]
did you run `npm install`

**Comment by kul1010** [comment]
Thanks a lot!!!!!! now working fine at Ubuntu and windows 7 both.
Kindly tell me its not in react, can you provide react version of current project.

**Comment by kul1010** [comment]
But right now i am installing on my server using; using putty ssh on centos. So showing errors.
[pankaj.kulshrestha@www-test-01 SimpleWebRTC]$ sudo npm i

> git-validate@2.2.2 install /var/www/html/pankaj/nodejs_proj/SimpleWebRTC/node_modules/git-validate
> node bin/install

fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/var/www/html/pankaj/nodejs_proj/SimpleWebRTC/.git/hooks/pre-commit'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at Object.exports.installHooks (/var/www/html/pankaj/nodejs_proj/SimpleWebRTC/node_modules/git-validate/lib/utils.js:248:12)
    at Object.<anonymous> (/var/www/html/pankaj/nodejs_proj/SimpleWebRTC/node_modules/git-validate/bin/install.js:3:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Linux 3.10.0-514.21.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "i"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! git-validate@2.2.2 install: `node bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-validate@2.2.2 install script 'node bin/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the git-validate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs git-validate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls git-validate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/pankaj/nodejs_proj/SimpleWebRTC/npm-debug.log
