### ISSUE TITLE
SimpleWebRTC or Similar for VOIP

### ISSUE THREAD

**Issue by vinodmap** [andyet/SimpleWebRTC#604]
This may not be the right place to ask this question, I apologize if so.  Does SimpleWebRTC have any hook to be a host for a VOIP server?  I am using SimpleWebRTC to do a network of two way video communications.  But, does this system also have a way to plug in just regular phone calls?  For example, does this system have a way for someone to call into a regular phone number (e.g., a 1-800 # or other), and then the server can either connect them via video or by just audio.  So it would be computer audio on the receiving end and phone on the other.  Or, would this be handled better by something like Asterisk?

**Comment by fippo** [comment]
A library like https://github.com/versatica/JsSIP might be better suited along with asterisk or freeswitch

**Comment by vinodmap** [comment]
Thank you for the pointer in the right direction
