### ISSUE TITLE
TURN working fine but lib throwing iceFailed

### ISSUE THREAD

**Issue by arcifius** [andyet/SimpleWebRTC#608]
Hello, i've been trying to integrate this lib on a project of mine... But things are going bad ;S
Monitoring  the process on chrome, it passes through onAddStream and start to call addIceCandidate a couple times then
icecandidate (srflx) with
icecandidate (srflx)sdpMid: audio, sdpMLineIndex: 0, candidate: candidate:1291336141 1 udp 1685921535 191.161.173.221 62432 typ srflx raddr 192.168.43.21 rport 62432 generation 0 ufrag YBts network-id 1 network-cost 10

![image](https://user-images.githubusercontent.com/11210923/29197733-44631fea-7e14-11e7-804d-6e6f4cf1f5f7.png)

and iceconnectionstatechange shows failed '-'
can you please help me? At least give me some direction

**Comment by arcifius** [comment]
In my project, when a user enters a room that isn't created yet the room got created... But if two users try to access together the room is created by one and the other can't join, but after some seconds with another attempt the other user was able to join... Maybe there is a delay for creating and joining rooms that i'm ignoring?

**Comment by fippo** [comment]
Your TURN server is not working as you don't get relay candidates. See [here](https://testrtc.com/webrtc-api-trace/) for a more lengthy description of the how and why

**Comment by arcifius** [comment]
Maybe not... I'm using COTURN and when tested at
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice

I got the following
![image](https://user-images.githubusercontent.com/11210923/29213985-f30fb1ae-7e7b-11e7-8280-8e3896b92be1.png)

I'll implement a mecanism that will keep trying to join the room for X seconds, hope this will solve the issue

**Comment by fippo** [comment]
how are you integrating your turn server with simplewebrtc - by running your own signalmaster? Check what servers are passed to the peerconnection constructor

**Comment by arcifius** [comment]
Well, actually I don't use it directly but I believe it is configured from the constructor of simplewebrtc
```javascript
state.webrtc = new SimpleWebRTC({
                detectSpeakingEvents: false,
                enableDataChannels: true,
                autoAdjustMic: false,
                autoRequestMedia: false,
                localVideoEl: ownerElementID,
                remoteVideosEl: '',
                url: App.config.voip.signalmaster,
                media: { audio: true, video: false },
                iceTransportPolicy: 'relay',
                peerConnectionConfig: { 'iceServers': [App.config.voip.turn] }
});
```
And yes i'm running my own signalmaster, App.config.voip.turn contains
```javascript
{
    'urls': 'turn:webapp.soullab.com.br',
    'username': '###', // I've hidden username because I don't have any mecanism for auth yet
    'credential': '###' // same here, just to not make my turn public...
}
```

My signalmaster have some configs too but I believe they are being overrided by client
```javascript
{
  "isDev": false,
  "server": {
    "port": 8888,
    "secure": true,
    "key": "/opt/sslcert/webappkey.pem",
    "cert": "/opt/sslcert/webappcert.pem",
    "password": "hiddenpassword"
  },
  "rooms": {
    "/* maxClients */": "/* maximum number of clients per room. 0 = no limit */",
    "maxClients": 0
  },
  "stunservers": [
    {
      "url": "stun:stun.l.google.com:19302"
    }
  ],
  "turnservers": [
    {
      "urls": ["turn:52.67.208.26"],
      "secret": "turnserversharedsecret",
      "expiry": 86400
    }
  ]
}
```

**Comment by fippo** [comment]
no, server-sent stun and turn servers override client-side ones. Because storing turn credentials in JS code is harmful.

**Comment by arcifius** [comment]
There is any way to temporary configure my signalmaster to send turn like i'm using on the client? I'll spend sometime on auth token later, but right now i just want to put everything to work smoothly

**Comment by fippo** [comment]
no configuration, you'll have to change the code that generates the credentials for https://github.com/andyet/signalmaster/blob/master/sockets.js#L123

**Comment by arcifius** [comment]
Thanks a lot for all the quick and valuable responses! I've changed that and everything seems to be working fine now, i'll run more tests and very soon will study a nice way to add the auth tokens... I appreciate your attention and time spent with me.

Cheers
