### ISSUE TITLE
"RTCIceServer.url is deprecated! Use urls instead" & "onaddstream is deprecated! Use peerConnection.ontrack instead."

### ISSUE THREAD

**Issue by callancarr** [andyet/SimpleWebRTC#610]
Getting two errors in the console:

```
RTCIceServer.url is deprecated! Use urls instead.  latest-v2.js:5
onaddstream is deprecated! Use peerConnection.ontrack instead.
```
Here is how I initialize the client. I've replaced the URL for my turn server. As mine currently is configured without security and I don't want to publicize it :P

App.webrtc.client = new SimpleWebRTC({
      localVideoEl: 'localVideo',
      remoteVideosEl: 'remotesVideos',
      autoRequestMedia: true,
      audio: true,
      url: "my_turn_server",
    });

**Comment by fippo** [comment]
The sandbox signalmaster server (which you should not use in production) was still using the old .url syntax. I've restarted it so this should be gone.

onaddstream: this is just a warning from Firefox. There is no plan to deprecate that callback just yet.

**Comment by callancarr** [comment]
@fippo sorry I meant to say my signal master server (which is also running coturn and is being used a turn server)

I have to admit after a very long time trying to get this all working I have utterly failed.

I'll show you my signal master config and hopefully you can show me where I've gone wrong, I keep getting the above errors despite using my own signalmaster server (not using the sandbox)

here is my production.json config. Note I have replaced my domain with ******, the real version points to a dns name which points to the signalling server itself on a port where coturn is running. Note that with this configuration I am able to get some connections over WebRTC going, but many fail and I get the error "Ice failed, your turn server is broken" in firefox.

```
{
  "isDev": false,
  "server": {
    "port": 80,
    "/* secure */": "/* whether this connects via https */",
    "secure": true,
    "key": "/etc/letsencrypt/live/signal.emeraldchat.com/privkey.pem",
    "cert": "/etc/letsencrypt/live/signal.emeraldchat.com/cert.pem",
    "password": null
  },
  "rooms": {
    "/* maxClients */": "/* maximum number of clients per room. 0 = no limit */",
    "maxClients": 0
  },
  "stunservers": [
    {
      "url": "stun:stun.*****.com"
    }
  ],
  "turnservers": [
    {
      "urls": ["turn:signal.****.com"],
      "secret": "emerald",
      "expiry": 86400
    }
  ]
}
```

**Comment by callancarr** [comment]
@fippo As far as I am aware I am using the correct configurations, I am still receiving this error. I have the most up to date versions of SimpleWebRTC and signal master.

**Comment by callancarr** [comment]
I repaired the issue, just in case other people find this issue it is not related to SimpleWebRTC but related to your signalmaster server.

```
{
  "isDev": false,
  "server": {
    "port": 80,
    "/* secure */": "/* whether this connects via https */",
    "secure": true,
    "key": "/etc/letsencrypt/live/signal.*****.com/privkey.pem",
    "cert": "/etc/letsencrypt/live/signal.*****.com/cert.pem",
    "password": null
  },
  "rooms": {
    "/* maxClients */": "/* maximum number of clients per room. 0 = no limit */",
    "maxClients": 0
  },
  "stunservers": [
    {
      **"urls": ["stun:signal.*****.com"]**
    }
  ],
  "turnservers": [
    {
      "urls": ["turn:signal.****.com"],
      "secret": "****",
      "expiry": 86400
    }
  ]
}
```

So to clarify to fix this you need to replace "url": "stun:signal.*****.com" with **"urls": ["stun:signal.*****.com"]**

**Comment by callancarr** [comment]
I repaired the issue, just in case other people find this issue it is not related to SimpleWebRTC but related to your signalmaster server.

```
{
  "isDev": false,
  "server": {
    "port": 80,
    "/* secure */": "/* whether this connects via https */",
    "secure": true,
    "key": "/etc/letsencrypt/live/signal.*****.com/privkey.pem",
    "cert": "/etc/letsencrypt/live/signal.*****.com/cert.pem",
    "password": null
  },
  "rooms": {
    "/* maxClients */": "/* maximum number of clients per room. 0 = no limit */",
    "maxClients": 0
  },
  "stunservers": [
    {
      **"urls": ["stun:signal.*****.com"]**
    }
  ],
  "turnservers": [
    {
      "urls": ["turn:signal.****.com"],
      "secret": "****",
      "expiry": 86400
    }
  ]
}
```

So to clarify to fix this you need to replace "url": "stun:signal.*****.com" with **"urls": ["stun:signal.*****.com"]**

**Comment by fippo** [comment]
I updated the sample config in https://github.com/andyet/signalmaster/pull/110
