### ISSUE TITLE
Safari 11 beta with local video disabled

### ISSUE THREAD

**Issue by tobiasps** [andyet/SimpleWebRTC#615]
I am testing the Safari 11 beta on macOS and iOS11 with SimpleWebRTC works with the latest adapter.js when doing 2 way video. 

However, In my application I am doing one way video, so on the receiving end I am have:
`webrtc = new SimpleWebRTC({
            remoteVideosEl: 'remoteVideos',
            autoRequestMedia: true,
            adjustPeerVolume: false,
            url: signal,
            media: {
                audio: false,
                video: false
            },
            receiveMedia: {
                offerToReceiveAudio: 1,
                offerToReceiveVideo: 1
            }
        });`

If I connect to the room on the receiving client first and then connect the sending client it works as it should. But if the sending client is already connected before the receiver connects no video is added with Safari 11 beta. This works with Chrome/Firefox/Opera. The difference seems to that Safari only sends an short offer with `a=group:BUNDLE data`, whereas Chrome i.e. sends a long offer with `a=group:BUNDLE audio video data`.

I'm not sure if this is an issue in SimpleWebRTC or a bug in Safari. If it is a bug in Safari, it would be great to report it - I'm not sure I have all the insights to create a good bug report though.

**Comment by tobiasps** [comment]
I found this bug report in webkit. Is it related? https://bugs.webkit.org/show_bug.cgi?id=173458

**Comment by fippo** [comment]
yes. This will be fixed by https://github.com/webrtc/adapter/issues/661 eventually.
