### ISSUE TITLE
Adding signalmaster

### ISSUE THREAD

**Issue by alexruskovski** [andyet/SimpleWebRTC#617]
Hello,

I just install signalmaster as the readme says. After pointing it from Simplewebrtc constructor the application is not able to establish connection between two clients. Am I doing something wrong, this is the  way Im pointing it:
```
var webrtc = new SimpleWebRTC({
			localVideoEl: 'localVideo',
			remoteVideosEl: 'remoteVideos',
			autoRequestMedia: true,
                        url:'https://12.12.12.12:8888'
		});
```

If anyone had similar problem, please guide me how to point the signal server. Thanks

**Comment by alexruskovski** [comment]
My bad, signaling server should be pointed out from ./src/simplewebrtc.js config array.

**Comment by alitna** [comment]
hi , i have same problem .. how can i fix that ??
