### ISSUE TITLE
Integrating TwilioTURN server with SimpleWebRTC

### ISSUE THREAD

**Issue by vishnusudhakarreddy** [andyet/SimpleWebRTC#619]
Hi,

I am Vishnu, I have took  TURN server details from Twilio. So I want to integrate my TURN server details in SimpleWebRTC. 

I tried the following steps.

1. I had checked my TURN server details by using https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ and it successfully executed

2. I had installed signal master and given my TURN server details in development.json and ran the server using node server.js

3. Changed my simpleWebRTC function like the below

var configuration =  {
                            "iceServers":[
                              {
                                "url": "stun:mydomain.com:3478?transport=udp"
                              },
                              {
                                "url": "turn:mydomain:3478",
                                "username": "myusername",
                                "credential": "password"
                              }
                            ]
                          }

 var webrtc = new SimpleWebRTC({
                    // the id/element dom element that will hold "our" video
                    localVideoEl: 'localVideo',
                    // the id/element dom element that will hold remote videos
                    remoteVideosEl: '',
                    // immediately ask for camera access
                    autoRequestMedia: true,
                    debug: false,
                    detectSpeakingEvents: true,
                    url: "https://signal.mydomain.com:443",
                    peerConnectionConfig: configuration
                }); 

After this I tested my webRTC application but it is not supporting TURN server. Can any one suggest it would be great help for me.  

Thanks in advance.

**Comment by fippo** [comment]
Passing ICE servers that way is not supported. You need to deliver your credentials from [the server](https://github.com/andyet/signalmaster/blob/master/sockets.js#L102)

Alternatively you choose to ignore that but then you're on your own.
