### ISSUE TITLE
WEBRTC with php

### ISSUE THREAD

**Issue by Znany** [andyet/SimpleWebRTC#620]
Hello, im running the /test/ folder with command: npm run test-page
What i want to do is change the index.html to --> index.php to add some php to script. But when i change it and run command npm run test-page and enter it, the page is not opening as index and when i click on that file it starts downloading. Im on mozilla. Debian 9 PHP 7.0.19-1 (cli)

**Comment by tgabi333** [comment]
npm run test-page cannot run php codes.

For using php you have to use your existing webserver, copy the test codes there.

**Comment by Znany** [comment]
The problem is, when i access file index.html from my normal webserver not started with npm.. (i use apache2) then 2 persons cant connect . The script is working but they cant connect. The file only works when i run it from npm run test-page but then i cant add php files

**Comment by Znany** [comment]
Ah maybe the problem is that with npm run test-page the page is https and without it( normal webserver) the page is http.... I think now i know why i dont work but if im wrong then tell me..
