### ISSUE TITLE
Doesn't request for camera/audio access

### ISSUE THREAD

**Issue by vincaslt** [andyet/SimpleWebRTC#623]
I'm trying to check out the demo, and the app does not request camera access at all, so the call does not start. This is the demo: https://simplewebrtc.com/demo.html and I've checked it on Opera and Chrome.

**Comment by vincaslt** [comment]
Apparently it works not for some reason :/

**Comment by fippo** [comment]
cross-check with https://webrtc.github.io/samples/src/content/getusermedia/gum/ which is about as basic as it can get wrt cam/mic accesss

**Comment by vincaslt** [comment]
It worked too. I figgure maybe my webcam was disconnected at the time, as it provides input for both audio and video.
