### ISSUE TITLE
Problem using current version of simplewebrtc

### ISSUE THREAD

**Issue by MatthieuHPP** [andyet/SimpleWebRTC#629]
Hello,

I am using Ubuntu 16.04, Node 6.11 and the last version of Simplewebrtc

The module "Bindings", depending on "engine.io-client@1.5.4" requires the use of "fs" that is not existing anymore. I have replaced it by "fs-extra" but obtains new errors...

Do you know way to overcome this problem ?

First error :1st_place_medal: 
```
This dependency was not found:

* fs in ./node_modules/bindings/bindings.js

To install it, you can run: npm install --save fs
```
New errors :

```
 warning  in ./node_modules/bindings/bindings.js

76:22-40 Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/bindings/bindings.js

76:43-53 Critical dependency: the request of a dependency is an expression

```

**Comment by forgotpw1** [comment]
Seeing his same error. How did you resolve @MatthieuHPP ?
