### ISSUE TITLE
is there any example code for text chating?

### ISSUE THREAD

**Issue by saintthor** [andyet/SimpleWebRTC#631]
thanks.

**Comment by saintthor** [comment]
another question.
on(ev, fn)
where can i see the document for all the evs?

**Comment by samelie** [comment]
If two clients are in a room: `webrtc.sendToAll("chat", {text:"have a nice day"})`

Listen for messages:

```
webrtc.connection.on("message", function(data) {
    switch (data.type) {
      case "chat":
        break
    }
  })
```

**Comment by saintthor** [comment]
thanks.

what about private chatting?

**Comment by blackcrack** [comment]
@saintthor a good idea
an an ajax chat as "Spoiler" an "switch down" chat with a Status line if there some new news " you have new ($jchatlines=) 1 new chat message line" (with an animated gif or png, i think to an 
alarmlight or something (_You have 2 new Message lines_) ![alarmgif](http://static-files1.modthesims2.com/images/smilies/alarm.gif) ) [Let show]<-Button for let sliding down... 
or something for give link's, pictures and so on further if we have a Video session, 
maybe with PHPBB Codes support and an small pluginsystem where make a 
possibility where it is later possible to have a support for many plugins . 
Only as small suggestion/idea interpolation ;)
best regards
Blacky

**Comment by saintthor** [comment]
sorry. i just want to know if there is a feature for private chatting in SimpleWebRTC.
i am familiar with chat room or im built by other technologies.

**Comment by blackcrack** [comment]
Hi @saintthor 
not sorry, it's a good idea what i have also before an couples month ..
an chat for giving further files and text informations like url's or something.. this is good, because all over Video works not, it's need a other form of information Sharing, because write on a small letter a url and hold it in the camera.. this is crap.. and more complicate as copy&past in a text-chat .. and then completes everything .

**Comment by xdumaine** [comment]
I'm not sure what's going on with these comments. It's very hard to understand what's being said. To summarize, however: you can implement chat on top of SimpleWebRTC using sendDirectly and sendDirectlyToAll. Anything beyond that is beyond the scope of this library.
