### ISSUE TITLE
Sometimes one-way video connection only established

### ISSUE THREAD

**Issue by TheChuckster** [andyet/SimpleWebRTC#636]
Sometimes when the user connects, I only see the user's video in one direction, what is a good way to help me diagnose this? AFAIK, no video element gets created on the affected user's end which suggests that no stream gets added.

Are there ways for me to check whether signalling is at fault and/or ICE?! If the affected user refreshes their page, almost always, a working two-way video connection is successfully established. This problem even occurs when both users have great Internet connections. Despite our best efforts at customer service, documentation, and user education, many of our users simply get thrown off by the problem (when they see no video) and do not know to even refresh the page even though this almost always ends up fixing it.

To fix this, I had to end up adding a watch dog to check if there are no video elements after some time limit which then resolves the issue by reconstructing and reconnecting SimpleWebRTC. This is a hack though. 

Ideally, SimpleWebRTC is more resilient to establishing two-way connections at all times. I've noticed that I need to have this watchdog too for data channels because sometimes a video connection gets established, but data sent via data channels is not reaching one of the users (even on reliable, ordered channels).

I am sorry this sounds very vague. If you have any suggested diagnostics for me to run, I am happy to do so. Would pasting chrome://webrtc-internals be helpful to you? I am running my own STUN and TURN (coturn) servers, along with signalmaster.

**Comment by fippo** [comment]
check https://testrtc.com/webrtc-internals-documentation/ which shows some debugging techniques and things to watch for.

**Comment by TheChuckster** [comment]
Okay, it also looks like ICE negotiation takes a really long time. Any advice on speeding this up?

**Comment by fippo** [comment]
i have been suspecting a chrome bug for quite a while. Do you have a webrtc-internals dump? You can visualize it here: https://fippo.github.io/webrtc-dump-importer/

**Comment by TheChuckster** [comment]
So, does this problem not occur in other browsers like Firefox?

**Comment by fippo** [comment]
the firefox folks have written their own ICE stack.

**Comment by TheChuckster** [comment]
Sorry for bombarding you with questions. Is there a bug report for Chrome? Are they working on a fix? Can it be consistently repro'd?

**Comment by fippo** [comment]
https://bugs.chromium.org/p/webrtc/issues/detail?id=5813 is what I am suspecting. Nobody is working on investigating it afaik.

**Comment by TheChuckster** [comment]
Here is a dump from Chrome
[159.89.200.167-1510219632815.log](https://github.com/andyet/SimpleWebRTC/files/1457085/159.89.200.167-1510219632815.log)

**Comment by TheChuckster** [comment]
^ Sorry, updated with the correct log.

Yes, from `webrtc-dump-importer`, it looks like it is using a relay server when it really shouldn't be. Hm.

**Comment by chuckhacker** [comment]
Here is another example of a one-way session

**Comment by fippo** [comment]
ah... unfortunately you need to have webrtc-internals open before the call or the dump is mostly meaningless :-/

prflx-prflx as candidate pair looks quite odd.

**Comment by chuckhacker** [comment]
[webrtc_internals_dump (4).txt](https://github.com/andyet/SimpleWebRTC/files/1458804/webrtc_internals_dump.4.txt)

**Comment by chuckhacker** [comment]
^ there is another one with webrtc-internals open before the call

**Comment by chuckhacker** [comment]
I just sent you some direct messages on gitter

**Comment by chuckhacker** [comment]
[webrtc_internals_dump (5).txt](https://github.com/andyet/SimpleWebRTC/files/1458817/webrtc_internals_dump.5.txt)

**Comment by chuckhacker** [comment]
These last few times, when I refreshed, the ice connection state became connected and I saw a peer but on my end, I still did not see any video or audio.

I am using my mobile hotspot in Seoul, and the far end is using ethernet in California.

**Comment by chuckhacker** [comment]
FWIW, I've been doing some more digging, and AppRTC with the same STUN/TURN servers is working perfectly under the same network conditions. I am using Collider instead of signalmaster, though.

**Comment by fippo** [comment]
oh... looks like your TURN server is handing out 172.31.x.x addresses as relay addresses.
That is in the private address space. Surprising this works at at all...
