### ISSUE TITLE
File Transfers Not working not even demo

### ISSUE THREAD

**Issue by visrey** [andyet/SimpleWebRTC#649]
File Transfers are failing.
They are failing at the receiving end.

```
Uncaught SyntaxError: Unexpected token o in JSON at position 1 
at RTCDataChannel.channel.onmessage .    1895
```

**Comment by fippo** [comment]
looks like chrome 58+ broke this. @tgabi333 @xdumaine does this ring a bell?

**Comment by tgabi333** [comment]
havent seen yet, we are not using datachannel at all, sorry.

**Comment by tgabi333** [comment]
it works for me here with chrome 63: https://simplewebrtc.com/filetransfer.html?hello

**Comment by fippo** [comment]
hrm. Oddly it works if I have one normal window and the other one opened in incognito mode...

**Comment by fippo** [comment]
@visrey are you trying to transfer a file between two tabs?

**Comment by visrey** [comment]
Yep
Got it.
Working on different machines.
Thank you.
Curious to know why it stopped all of sudden today. It was working for me till yesterday in two tabs.

**Comment by fippo** [comment]
i could reproduce so its not just you. Filed https://bugs.chromium.org/p/chromium/issues/detail?id=795865 because *something* is wrong here
