### ISSUE TITLE
React with Webpack issue

### ISSUE THREAD

**Issue by clustersnake** [andyet/SimpleWebRTC#650]
I'm having the following message in console: Uncaught TypeError: Cannot read property 'WebSocket' of undefined. the weird thing is I installed it in a vanilla react app without webpack and it runs perfect

**Comment by vicmiletsky** [comment]
Hey @clustersnake 

Just ran into a similar issue. Check out this thread: https://github.com/websockets/ws/issues/478

A quick workaround would be excluding `ws/lib/browser.js` from babel rule. This `ws` somehow ends up among dependencies of SimpleWebRTC and this `browser.js` doesn't work correctly in strict mode. Strict mode is automatically added by webpack/babel and this is why it works for you without webpack.

```javascript
// Example of a webpack rule that will fix the issue
{
  test: /\.js$/,
  exclude: [ /ws\/lib\/browser\.js/ ],
  use: [
    {
      loader: 'babel-loader',
      options: { 
        // ... 
      }
  // ...
```

**Comment by clustersnake** [comment]
Thank you very much @vicmiletsky That solved my problem :D
