### ISSUE TITLE
Black screens on iPhone ios 11 safari

### ISSUE THREAD

**Issue by dfabreguette-ap** [andyet/SimpleWebRTC#659]
Hi,
I recently upgraded SimpleWebRTC to v3.0.1 with latest adapter.js to allow ios users to be use new rtc feature of safari 11.
It looks like it works fine with iPad Air 2 but not on iPhone 6, I only get a black screen, but others can still hear and see me.
The thing is I don't have any error. I found this issue https://bugs.webkit.org/show_bug.cgi?id=176843 talking about "autoplay"  and adding "playsinline" attribute to video elements. What do you guys suggest ? How can I solve the problem ?
Thank you so much for such good plugin !

**Comment by fippo** [comment]
have you added playsinline to the element? https://simplewebrtc.com/notsosimple.html#basic-overlay shows how to get hold of the element.

**Comment by dfabreguette-ap** [comment]
Everything worked fine after I upgraded to latest SimplWebRTC with adapter.js !
Thanks !

**Comment by mikailyazici** [comment]
i hav try but ist not work for me. can you sare with as my your example include?
