### ISSUE TITLE
cant connect to turn

### ISSUE THREAD

**Issue by mortenbirkelund** [andyet/SimpleWebRTC#661]
When i leave the turn server empty, and test my signalmaster installation, the video feed is sent perfect . However, when i add my turn server setup nothings happens (the video feed arent sent) and no informations is visible in "about:webrtc"

I have setup coturn on the server with the following config (ip is changed for security).

```
# you can listen ports 3478 and 5349 instead of 80/443
listening-port=3478

listening-ip=123.123.123.123

relay-ip=123.123.123.123
external-ip=123.123.123.123

realm=sub.domain.dk
server-name=sub.domain.dk

fingerprint
lt-cred-mech

use-auth-secret
static-auth-secret=test

no-stdout-log
log-file=var/log/turnserver/turn.log

total-quota=100
bps-capacity=0
stale-nonce

cipher-list="ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AES:RSA+3DES:!ADH:!AECDH:!MD5"
no-loopback-peers
no-multicast-peers

```

and the following is the signalmaster configuration

```
{
  "isDev": false,
  "server": {
    "port": 8888,
    "/* secure */": "/* whether this connects via https */",
    "secure": true,
    "key": "config/sslcerts/key.pem",
    "cert": "config/sslcerts/cert.pem",
    "password": null
  },
  "rooms": {
    "/* maxClients */": "/* maximum number of clients per room. 0 = no limit */",
    "maxClients": 0
  },
  "stunservers": [
    {
      "urls": "stun:stun.l.google.com:19302"
    }
  ],
  "turnservers": [
    {
      "urls": ["turn:123.123.123.123:3478?transport=tcp"],
      "secret": "test",
      "expiry": 86400
    }
  ]
}

```

When i test here, the turn server is working just fine. 
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

And this is what signalmaster sends to the webrtc client 
![billede](https://user-images.githubusercontent.com/8955039/35488494-4b1d3ad0-048a-11e8-93f0-f583bec42e60.png)

I have spend more time than i care to admit on this error, so i really hope that someone can point me to what could be the problem.

**Comment by fippo** [comment]
signalmaster does not support static credentials, only the shared secret mechanism. https://gist.github.com/bradleythughes/907a9b30cb451a1b5f969982fc2130de has some hints on the config, @bradleythughes should be able to point to the coturn documentation for this

**Comment by mortenbirkelund** [comment]
@fippo could the problem be because the webrtc page is https, the signal server is https but the turn server is only http? Should all of these use the same protocol?

**Comment by mortenbirkelund** [comment]
Solved. The solution was to use https for the turn server and then use a letsencrypt instead of openssl, as it is verified. 
I think the problem was that the browser did not allow http content to be loaded from a https page, and when i enabled the https, then the browser did not trust the certificate. 

So currently i am using Certbot to create the openssl certificates, and then using the webhook feature, i can a script that copies the certificate to the signalmaster folder and set permission.
