### ISSUE TITLE
Screen sharing only working once.

### ISSUE THREAD

**Issue by ee11131** [andyet/SimpleWebRTC#662]
I have a videoconference app with the latest simplewebrtc.bundle.js and the latest adapter.js. I am using the Chrome extension: https://chrome.google.com/webstore/detail/screen-capturing/ajhifddimkapgcifgcodmmfdlknahffk?utm_source=chrome-app-launcher-info-dialog to enable screen sharing by users in Chrome.
It works fine the first time I do it, but if I stop the screen sharing and then share it again, the user sending the screen is able to see its screen perfectly but for the receiving user nothing happens.
When analyzing chrome dev tools for the sending user, comparing the first screen share (which works) with the second (which does not) there are some webrtc events that are clearly missing.
![screen1-2](https://user-images.githubusercontent.com/33349294/35562538-97fa777e-05ab-11e8-9630-33f70167151e.jpg)

As you can see with this picture, the second case is missing the sending candidates part. What can be the cause of this issue?

**Comment by ee11131** [comment]
Fixed with this:
https://github.com/andyet/SimpleWebRTC/issues/642

**Comment by fippo** [comment]
same issue, closing
