### ISSUE TITLE
Does Edge really suppport WebRTC!!

### ISSUE THREAD

**Issue by satish4linux** [andyet/SimpleWebRTC#672]
Hi Everyone,

This is my second issue submission in this forum. I'm working on the basics of WebRTC and testing the things that can be possible using this awesome API. I implemented a Simple Video Chat Web Application using the WebRTC API and It's working successfully when I tested on Chrome and Mozilla. But, The issue comes when I start testing the same for Edge!
I explored a lot about it and tried many different `adapter.js` codes for making my code compatible with Edge ( including the `adapter.js` library provided by Microsoft in it's [Announcement on WebRTC support in Edge, January 2017](https://blogs.windows.com/msedgedev/2017/01/31/introducing-webrtc-microsoft-edge/#suJoUY7kKUDzRSi3.97) ). Unfortunately, none of them worked for me. The one provided by Microsoft at the release time did worked for once when I tried a cross Edge-Chrome Communication ( audio only, though ) but, it isn't working for the other Edge-Chrome or Edge-Mozilla Connections. So, here is my problem...
Does Edge really have full support for WebRTC ( for audio as well as video communication )?? And if yes, then please help me out with this. Thanks in advance :)

Regards,

Satish

**Comment by fippo** [comment]
since you posted the same to discuss-webrtc I assume it is not related to simplewebrtc.

**Comment by didlie** [comment]
Edge does not fully support data or text over webrtc... Microsoft owns Skype
