### ISSUE TITLE
This is a useless, fully obfuscated repository

### ISSUE THREAD

**Issue by didlie** [andyet/SimpleWebRTC#677]
This is a useless, fully obfuscated repository. Most of the dependency references are fictitious and the structure has been internally destroyed. The final v2 build was never made available on github, and the closest precursor that probably doesn't work completely is pre-v2 release. The actual version 2 that is given in the README  index.html example is a link to the developer website and the actual NodeJs runtime is not available anywhere in this repo in its working form. You will never get a standalone javascript file out of the mess of fictitious dependencies. My best advice is dispose of this code and write your own.

**Comment by fippo** [comment]
actual nodejs runtime? you mean https://github.com/andyet/signalmaster? 
But yeah... :wave:
