### ISSUE TITLE
Add a distribution as a single server-independent javascript file that runs in the browser

### ISSUE THREAD

**Issue by didlie** [andyet/SimpleWebRTC#678]
Dependency on Node is destroying all the good work done in Javascript and removing access to it for the core real stable application developers. Stable means: an application that has code (dependencies) that do not dynamically load from disparate repositories. Get the code, compile it, stabilize it, and make it available to client browsers without dependence on Node servers.!.!.!

**Comment by didlie** [comment]
maintain your depencies in a stable way, as files hosted in your distribution, and compile them to run as javascript was intended, from PHP!

**Comment by fippo** [comment]
have you heard of browserify? There is no runtime dependency. Also didn't you consider this repository useless in #677? Go elsewhere.

**Comment by ibc** [comment]
> and compile them to run as javascript was intended, from PHP!

Excuse me, are you completely crazy?

**Comment by blackcrack** [comment]
Hey Iñaki alias @ibc ..  

this can you also say other.. 
sei scandaloso
e altrettanto stupido
look in the mirror.. this was only a idea.
you could say: "this comes not in question, because must not all be in java" 

si ?

best regards
Blacky

**Comment by ibc** [comment]
Amazing. Thanks.
