### ISSUE TITLE
Black out idle users

### ISSUE THREAD

**Issue by balupton** [andyet/SimpleWebRTC#68]
Would be great if users could mark themselves as idle, which will then kill their audio, make their video black and white, and update their video every 10 seconds.

[Sqwiggle](http://sqwiggle.com/) implements this, and it works very well.

It will also help with #64

It would also allow us (Bevry) to be able to provide a virtual office for our DocPad community, which is getting quite large. Sqwiggle can't do this for us, as we wish for our virtual office to be open, where anyone can join.

**Comment by tgabi333** [comment]
PR's are always welcomed! :)
