### ISSUE TITLE
Local video not showing up for iOS in cordova/ionic

### ISSUE THREAD

**Issue by sergei202** [andyet/SimpleWebRTC#685]
In Chrome and Safari, everything is fine.  But when built into a native app using ionic, local video doesn't show up no the device, --though the video is still sent to the other party.

I'm using the latest version of SimpleWebRTC and the latest version of cordova-plugin-iosrtc.
I've also tried various combinations of `playsinline` and `autoplay`.

![ios-issues](https://user-images.githubusercontent.com/15058464/38058264-e031742e-32a7-11e8-8b2e-7d5ef0ab2406.png)

If anyone else has had this problem and found a solution, I would really appreciate any pointers!

**Comment by forgotpw1** [comment]
Any new developments on this @sergei202?

There is a newer version of socket.io-client which relies on a newer version of socket.io. 

Without knowing too much about this topic myself I am wondering if simplewebrtc handles re-connection better with a newer version of socket.io

**Comment by sergei202** [comment]
@forgotpw1: I still haven't found a solution to this yet.

I don't think updating socket.io will help since it works fine on other devices.
But when using a Ionic/Cordova iOS build, the iOS device will send local video, but not display it.

I'll be jumping back on this next week and will post any progress I make.

**Comment by sergei202** [comment]
@forgotpw1: I finally got this working.

I had to call `observeVideo()` on the `joinRoom()` callback:
```js
if(this.platform.is('ios') && typeof cordova !== 'undefined') { // If iOS and Cordova
    var localVideo = document.getElementById('localVideo');
    cordova.plugins.iosrtc.observeVideo(localVideo);
}
```
