### ISSUE TITLE
Error occur at SimpleWebRtc object constructor

### ISSUE THREAD

**Issue by destar77** [andyet/SimpleWebRTC#697]
[JavaScript Error: "TypeError: window.arguments is undefined" {file: "chrome://global/content/alerts/alert.js" line: 41}]
prefillAlertInfo@chrome://global/content/alerts/alert.js:41:1
@chrome://global/content/alerts/alert.xul:64:1

The error occur when I am start running at geckofx(firefox) browser at winform(C#).
I tried with my simplewebrtc client, talky.io and https://simplewebrtc.com/demo.html
Can anyone help me this error?
Init alert is called and after init is never called. Here is the code.
<code>
window.alert("Init SimpleWebRTC");
// create our webrtc connection
var webrtc = new SimpleWebRTC({
	// the id/element dom element that will hold "our" video
	localVideoEl: 'localVideo',
	// the id/element dom element that will hold remote videos
	remoteVideosEl: '',
	// immediately ask for camera access
	autoRequestMedia: true,
	debug: false,
	detectSpeakingEvents: true
	,url: 'https://10.1.40.77:8888/'
	//,peerConnectionConfig: { 'iceServers': [] }
	//,media: mediaOptions
});
window.alert("After init SimpleWebRTC");
</code>

**Comment by fippo** [comment]
does this simple snippet work in that browser?
```
function foo() {
  console.log(arguments);
}
foo();
```
?

**Comment by destar77** [comment]
i can do that and alert some message inside the foo function.
Sorry @fippo 
that javascript error is coming out from that browser then i close it. But at that browser I cannot see the debugging mode becoz it is embedded in the application.
So I alert the window before new SimpleWebRTC is build. After that nth happen.
For talky.io cannot create room and https://simplewebrtc.com/demo.html create button is disable.
I believe that browser is using firefox. At pure firefox can work.

**Comment by hokuco** [comment]
@destar77 if this issue has been resolved can you close this issue?
