### ISSUE TITLE
All SimpleWebRTC applications and official demos fail with a "Uncaught DOMException: Failed to construct 'RTCPeerConnection': '$STUNSERVER_URL' is not a valid URL."

### ISSUE THREAD

**Issue by edtarber** [andyet/SimpleWebRTC#702]
Since today the error above appears in all my webrtc applications as well as in all official demos.
in the pcConfig there always are entries like "urls" : "$STUNSERVER_URL" ... it seems like a placeholder is not properly "replaced".

Weird thing is, that there were no cod changes.

**Comment by cgunston** [comment]
Yeah I am having the exact same issue. I noticed on the SimpleWebRTC website that https://simplewebrtc.com/latest-v3.js is now being used. I was using latest-v2.js and getting your error. After updating to latest-v3 I am now receiving:
Failed to construct 'RTCPeerConnection': Both username and credential are required when the URL scheme is "turn" or "turns".

Any help would be greatly appreciated!

**Comment by cgunston** [comment]
Thanks for that. Looks like I'm gonna need to look at setting up a signalling server.

Did you follow any particular tutorial?

Thanks

**Comment by edtarber** [comment]
I just followed the instructions on the signalmaster github page
the only thing I had to do differently was to provide links to my website's official SSL certificates in the config file ... self signed certificates won't work with most browsers

**Comment by cgunston** [comment]
Ok thanks for that.

Hopefully the sandbox signalling server will also be fixed.

**Comment by fippo** [comment]
the sandbox server should be back soon. But please, do not rely on this...

**Comment by one000mph** [comment]
Hi @edtarber and @cgunston. We migrated the sandbox server recently and had to update some endpoints. Sorry about the outage. It is back now, but as @fippo says we don't recommend relying on it!

**Comment by cgunston** [comment]
@one000mph Thank you for the update!
