### ISSUE TITLE
ES6 import of simplewebrtc impossible

### ISSUE THREAD

**Issue by lawlietmester** [andyet/SimpleWebRTC#705]
ES6 import of simplewebrtc impossible.

I attached example code [here](https://github.com/andyet/SimpleWebRTC/files/2026371/npm.import.bug.zip). Webpack-stream is same as Webpack 3.

OS: Win10, no Python installed

Log:

> $ gulp
> [16:29:59] Requiring external module babel-register
> [16:30:00] Using gulpfile D:\Projects\Screen Sharing\Receiver Site\npm import bug\gulpfile.babel.js
> [16:30:00] Starting 'default'...
> 
> internal/streams/legacy.js:59
>       throw er; // Unhandled stream error in pipe.
>       ^
> Error: ./node_modules/getscreenmedia/getscreenmedia.js
> Module not found: Error: Can't resolve 'webrtc-adapter' in 'D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\getscreenmedia'
> resolve 'webrtc-adapter' in 'D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\getscreenmedia'
>   Parsed request is a module
>   using description file: D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\getscreenmedia\package.json (relative path: .)
>     Field 'browser' doesn't contain a valid alias configuration
>   after using description file: D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\getscreenmedia\package.json (relative path: .)
>     resolve as module
>       D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\getscreenmedia\node_modules doesn't exist or is not a directory
>       D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\node_modules doesn't exist or is not a directory
>       D:\Projects\Screen Sharing\Receiver Site\node_modules doesn't exist or is not a directory
>       D:\Projects\Screen Sharing\node_modules doesn't exist or is not a directory
>       D:\Projects\node_modules doesn't exist or is not a directory
>       D:\node_modules doesn't exist or is not a directory
>       looking for modules in D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules
>         using description file: D:\Projects\Screen Sharing\Receiver Site\npm import bug\package.json (relative path: ./node_modules)
>           Field 'browser' doesn't contain a valid alias configuration
>         after using description file: D:\Projects\Screen Sharing\Receiver Site\npm import bug\package.json (relative path: ./node_modules)
>           using description file: D:\Projects\Screen Sharing\Receiver Site\npm import bug\package.json (relative path: ./node_modules/webrtc-adapter)
>             no extension
>               Field 'browser' doesn't contain a valid alias configuration
>               D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\webrtc-adapter doesn't exist
>             .js
>               Field 'browser' doesn't contain a valid alias configuration
>               D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\webrtc-adapter.js doesn't exist
>             .json
>               Field 'browser' doesn't contain a valid alias configuration
>               D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\webrtc-adapter.json doesn't exist
>             as directory
>               D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\webrtc-adapter doesn't exist
> [D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\getscreenmedia\node_modules]
> [D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\node_modules]
> [D:\Projects\Screen Sharing\Receiver Site\node_modules]
> [D:\Projects\Screen Sharing\node_modules]
> [D:\Projects\node_modules]
> [D:\node_modules]
> [D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\webrtc-adapter]
> [D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\webrtc-adapter.js]
> [D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\webrtc-adapter.json]
> [D:\Projects\Screen Sharing\Receiver Site\npm import bug\node_modules\webrtc-adapter]
>  @ ./node_modules/getscreenmedia/getscreenmedia.js 3:14-39
>  @ ./node_modules/localmedia/localmedia.js
>  @ ./node_modules/simplewebrtc/src/webrtc.js
>  @ ./node_modules/simplewebrtc/src/simplewebrtc.js
>  @ ./test.js

**Comment by fippo** [comment]
adapter.js is a peerdependency, you seem not to have installed it?

**Comment by lawlietmester** [comment]
Yes, I have not installed it
