### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by CMor1184** [andyet/SimpleWebRTC#719]
Hi the last commit was six month ago....
Is there anybody who support and work on the project?

Thanks!

**Comment by fippo** [comment]
this project has been in need for a full-time maintainer for around three years.

Not sure why you think its dead, what is broken?

**Comment by xdumaine** [comment]
@CMor1184 Echo what fippo said - it's not *dead* but the maintainers do have significant other things going on, and we don't get much outside contribution in way of fixes or improvements, only issues reported.
