### ISSUE TITLE
URGENT - new BUG on Google chrome 67

### ISSUE THREAD

**Issue by shamun** [andyet/SimpleWebRTC#720]
When the browser is not in incognito mode i get following (on incognito mode it works without following error):

![image](https://user-images.githubusercontent.com/107349/42074956-f2cba306-7b6e-11e8-91de-53a8bedabeb1.png)

**Comment by fippo** [comment]
you're using adblock?

**Comment by shamun** [comment]
I just now noticed that all my OSX/Windows Google chrome have AdBlock on. 
I will switch it off and re-test with latest version. If i face the problem again i will let you know. 
Thank you
