### ISSUE TITLE
isVideoEnabled() not working

### ISSUE THREAD

**Issue by Rakesh777** [andyet/SimpleWebRTC#723]
I am trying to check if video is enabled or not. I am trying to call `webrtc.isVideoEnabled()` function, but it says `isVideoEnabled()` in not defined.

**Comment by fippo** [comment]
try webrtc.webrtc.isVideoEnabled()

**Comment by Rakesh777** [comment]
Okay that worked. Thank you @fippo 

This library is great, but it really needs detailed documentation. Having hard time understanding things.
