### ISSUE TITLE
Incoming videos not playing

### ISSUE THREAD

**Issue by ilysorc** [andyet/SimpleWebRTC#730]
I have already made an application, but remote videos are not working now. Is there anyone living in it?

**Comment by orkank** [comment]
I got the same problem, sometimes remote videos do not play automatically, I fix it with video.play() when "videoAdded" action called.

`
  if (peer && peer.pc) {
    var connstate = document.createElement('div');
    connstate.className = 'connectionstate';
    container.appendChild(connstate);
    peer.pc.on('iceConnectionStateChange', function (event) {
      switch (peer.pc.iceConnectionState) {
        case 'connected':
        case 'completed': // on caller side
        video.play();
        break;
      }
    }
  }
`

**Comment by orkank** [comment]
I got the similar problem. When the remote video is loaded, It does not play automatically and I fix it with video.play(); when remote is connected/completed.

**Comment by wardhanster** [comment]
I might be miles away from the actual problem, but here is my 2 cents.
if you are trying to establish connection between chrome instances then
it might be the chrome version you are trying to work with has disabled auto play for videos.
you have to manually play the video as @orkank suggested.
If you are experiencing this on safari browser - you need to add inline parameter.
Hope it helps.

**Comment by ilysorc** [comment]
I solved this problem. I am working with ReactJs and ReactJs is using autoPlay instead of autploy. The problem was fixed when I changed AutoPlay with autoPlay attribute.
