### ISSUE TITLE
Cannot Access My Signal Server Without Going to Socket.io link and Clicking Advanced --> Proceed on Browser

### ISSUE THREAD

**Issue by vinodmap** [andyet/SimpleWebRTC#731]
Hello, I have setup a signalserver at https://54.xxx.xx.xxx/socket.io/.  When I go to this address, I get a Not Secure/Private warning in the browser.  (i.e., it does not recognize the SSL certificate in sslcerts).  If I press proceed in the Browser, it goes to the page and I get:

> {"code":0,"message":"Transport unknown"}

as expected.  But, if I don't do the Advanced --> Proceed on every browser this runs from, video does not come up.  How can I modify this such that I do not have to do this?  Do I need to use my own SSL certificate that is recognized, or is there another way around this?

**Comment by fippo** [comment]
you need a valid certificate. https://letsencrypt.org/ gets you one.
