### ISSUE TITLE
where are the old demo files?

### ISSUE THREAD

**Issue by hokuco** [andyet/SimpleWebRTC#736]
@fippo  sorry to be a bother, but do you know where the old demo files are hosted? I just needed to look at the audio demo to check something.

**Comment by fippo** [comment]
still at https://github.com/andyet/SimpleWebRTC/tree/gh-pages

**Comment by hokuco** [comment]
thanks!, by the way, one last thing, how do you get your own client id(rather than getting the peer.id)?
