### ISSUE TITLE
File transfer with SimpleWebRTC

### ISSUE THREAD

**Issue by cmar0ck** [andyet/SimpleWebRTC#738]
Hi all,

I'm trying to implement a file transfer function with SimpleWebRTC but since https://simplewebrtc.com/filetransfer is not available anymore, I'm a bit at a loss.
Could you point me to a documentation / sample code, please?

**Comment by hokuco** [comment]
I made this lil' thread just in case something like that happened:
#736

**Comment by hokuco** [comment]
if this helped please close the thread...

**Comment by cmar0ck** [comment]
This helps, thanks a lot!
